import React from "react";
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame} from "remotion";
import {loadFont as loadDisplay} from "@remotion/google-fonts/BricolageGrotesque";

const {fontFamily:display}=loadDisplay("normal",{weights:["600","700","800"],subsets:["latin"]});
const mono='"Space Mono","SFMono-Regular",Consolas,monospace';
const ui='-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",Arial,sans-serif';
const P={paper:"#FBF7F0",ink:"#141318",blue:"#2F5BFF",coral:"#FF5A47",citrus:"#E8FF5A",mint:"#35D6A4",white:"#FFFDF8",grey:"#E8E3DA"};
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
const q=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],clamp);
const gate=(f:number,a:number,b:number,c:number,d:number)=>q(f,a,b)*(1-q(f,c,d));
const pop=(f:number,at:number)=>spring({frame:f-at,fps:30,config:{damping:18,stiffness:380,mass:.7}});
type Format={vertical:boolean};

const Paper:React.FC<{tone?:string}>=({tone=P.paper})=><AbsoluteFill style={{background:tone,overflow:"hidden"}}>
  <AbsoluteFill style={{opacity:.11,backgroundImage:`linear-gradient(${P.ink} 1px,transparent 1px),linear-gradient(90deg,${P.ink} 1px,transparent 1px)`,backgroundSize:"46px 46px"}}/>
  <AbsoluteFill style={{opacity:.1,mixBlendMode:"multiply",backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='130' height='130'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.86' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.3'/%3E%3C/svg%3E\")"}}/>
</AbsoluteFill>;

const Type:React.FC<{children:React.ReactNode;size:number;color?:string;style?:React.CSSProperties}>=({children,size,color=P.ink,style})=><div style={{fontFamily:display,fontWeight:800,fontSize:size,lineHeight:.9,letterSpacing:0,color,...style}}>{children}</div>;

const Stamp:React.FC<{children:React.ReactNode;color?:string;size?:number;rotate?:number}>=({children,color=P.citrus,size=28,rotate=-2})=><div style={{display:"inline-block",background:color,border:`5px solid ${P.ink}`,boxShadow:`7px 8px 0 ${P.ink}`,padding:"12px 18px",fontFamily:mono,fontWeight:700,fontSize:size,transform:`rotate(${rotate}deg)`,color:P.ink}}>{children}</div>;

const Phone:React.FC<{vertical:boolean;side:"asmi"|"business";title:string;connected?:boolean;frame:number}>=({vertical,side,title,connected,frame})=>{const w=vertical?430:390,h=vertical?890:800,r=60;return <div style={{width:w,height:h,position:"relative",filter:"drop-shadow(0 35px 35px rgba(20,19,24,.3))",transform:`rotate(${side==="asmi"?-3:3}deg) translateY(${Math.sin(frame/18+(side==="asmi"?0:2))*8}px)`}}><div style={{position:"absolute",inset:-8,borderRadius:r+8,background:"linear-gradient(100deg,#343438 0%,#F1EEE7 10%,#6D6C70 27%,#17171A 58%,#D6D1C8 84%,#38383B 100%)",boxShadow:"inset 0 0 0 2px rgba(255,255,255,.85),inset 0 0 0 7px #19191B"}}/><div style={{position:"absolute",inset:6,borderRadius:r-4,background:"linear-gradient(180deg,#303136,#050506 72%)",overflow:"hidden",color:P.white,fontFamily:ui,textAlign:"center"}}><div style={{height:48,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 24px",fontWeight:700,fontSize:14}}><span>9:41</span><span>▮▮▮　◒　86</span></div><div style={{paddingTop:vertical?100:70}}><div style={{width:vertical?125:110,height:vertical?125:110,borderRadius:"50%",background:side==="asmi"?P.coral:P.blue,margin:"0 auto 25px",display:"grid",placeItems:"center",fontSize:42,fontWeight:800}}>{side==="asmi"?"a":"H"}</div><div style={{fontSize:vertical?36:32,fontWeight:700}}>{title}</div><div style={{fontSize:19,color:connected?P.mint:"#B7B7BC",marginTop:12}}>{connected?"connected · real call":"calling…"}</div></div><div style={{position:"absolute",left:0,right:0,bottom:vertical?120:95,display:"flex",justifyContent:"center",gap:26}}>{["mute","keypad","audio"].map((x,i)=><div key={x} style={{fontSize:13,display:"grid",justifyItems:"center",gap:7}}><span style={{width:64,height:64,borderRadius:"50%",background:"rgba(255,255,255,.14)",display:"grid",placeItems:"center",fontSize:20}}>{["—","•••","◖"][i]}</span>{x}</div>)}</div><div style={{position:"absolute",left:"50%",bottom:28,transform:"translateX(-50%)",width:72,height:72,borderRadius:"50%",background:connected?P.mint:P.coral,display:"grid",placeItems:"center",fontSize:28}}>☎</div><div style={{position:"absolute",top:13,left:"50%",transform:"translateX(-50%)",width:105,height:29,borderRadius:30,background:"#000"}}/></div></div>};

const Cable:React.FC<{vertical:boolean;progress:number;resolved?:boolean}>=({vertical,progress,resolved})=><svg style={{position:"absolute",inset:0,width:"100%",height:"100%",zIndex:1}} viewBox={vertical?"0 0 1080 1920":"0 0 1920 1080"}><path d={vertical?"M 280 575 C 820 500 230 1180 800 1120":"M 520 520 C 760 120 1160 940 1400 520"} fill="none" stroke={resolved?P.mint:P.ink} strokeWidth={vertical?18:14} strokeLinecap="round" strokeDasharray="1900" strokeDashoffset={1900-progress*1900}/><circle cx={vertical?800:1400} cy={vertical?1120:520} r={vertical?28:24} fill={resolved?P.mint:P.coral} stroke={P.ink} strokeWidth="8"/></svg>;

const Proof:React.FC<Format>=({vertical})=>{const f=useCurrentFrame();const outcomes=["BOOKED","QUOTE HELD","DETAILS FOUND","CALL BACK READY"];return <AbsoluteFill style={{opacity:gate(f,0,3,112,120)}}><Paper/><div style={{position:"absolute",left:vertical?60:100,top:vertical?300:170,width:vertical?940:1200}}><Type size={vertical?92:112} style={{transform:`translateX(${(1-pop(f,0))*-500}px) rotate(-2deg)`}}>asmi has been handling</Type><Type size={vertical?92:112} color={P.blue} style={{transform:`translateX(${(1-pop(f,8))*500}px) rotate(1deg)`}}>the real world</Type><Type size={vertical?74:86} style={{marginTop:28,opacity:pop(f,18)}}>for thousands of people.</Type><Type size={vertical?78:92} color={P.coral} style={{marginTop:vertical?110:50,opacity:pop(f,54),transform:"rotate(-2deg)"}}>then something changed.</Type></div><div style={{position:"absolute",left:vertical?50:125,right:vertical?50:100,bottom:vertical?300:105,display:"flex",gap:16,flexWrap:"wrap"}}>{outcomes.map((x,i)=><div key={x} style={{opacity:pop(f,8+i*8),transform:`translateY(${(1-pop(f,8+i*8))*35}px) rotate(${i%2?-2:2}deg)`}}><Stamp color={[P.mint,P.citrus,P.coral,P.blue][i]} size={vertical?21:20}>{x}</Stamp></div>)}</div></AbsoluteFill>};

const AiReveal:React.FC<Format>=({vertical})=>{const f=useCurrentFrame();const local=f-108;const first=local<165;const caption=local<145?"I'm an AI calling on behalf of John.":"Yes, of course. I can help you with a booking…";return <AbsoluteFill style={{opacity:gate(f,106,114,532,540)}}><Paper tone={first?P.citrus:P.blue}/><Cable vertical={vertical} progress={q(local,0,60)}/><div style={{position:"absolute",left:vertical?55:90,top:vertical?270:130,zIndex:8,transform:`scale(${.7+.3*pop(local,0)})`}}><Stamp color={P.coral} size={vertical?35:30}>AI CALLING.</Stamp></div><div style={{position:"absolute",right:vertical?55:90,top:vertical?1020:130,zIndex:8,transform:`scale(${.7+.3*pop(local,115)})`}}><Stamp color={P.blue} size={vertical?35:30} rotate={2}>AI ANSWERING.</Stamp></div><div style={{position:"absolute",left:vertical?85:390,top:vertical?430:180,zIndex:5,transform:`scale(${vertical?.72:.68})`,transformOrigin:"top left"}}><Phone vertical={vertical} side="asmi" title="asmi" connected frame={f}/></div><div style={{position:"absolute",right:vertical?85:390,top:vertical?1110:180,zIndex:5,transform:`scale(${vertical?.72:.68})`,transformOrigin:"top right"}}><Phone vertical={vertical} side="business" title="Herman's" connected frame={f}/></div><div style={{position:"absolute",left:vertical?55:530,right:vertical?55:530,bottom:vertical?240:70,zIndex:10,background:P.paper,border:`5px solid ${P.ink}`,boxShadow:`8px 9px 0 ${P.ink}`,padding:vertical?"24px 28px":"18px 25px",fontFamily:mono,fontSize:vertical?25:23,fontWeight:700,lineHeight:1.3,textAlign:"center"}}><span style={{color:first?P.coral:P.blue}}>{first?"ASMI: ":"HERMAN'S: "}</span>“{caption}”</div><div style={{position:"absolute",left:vertical?55:750,top:vertical?1520:725,zIndex:10,opacity:pop(local,225)}}><Type size={vertical?57:67} color={P.white} style={{textShadow:`5px 6px 0 ${P.ink}`,transform:"rotate(-2deg)"}}>yeah. that's happening now.</Type></div></AbsoluteFill>};

const Useful:React.FC<Format>=({vertical})=>{const f=useCurrentFrame();const local=f-530;const facts=["FULLY VEGAN","ROTATING BUFFET","AUGUST 21","GUEST COUNT NEEDED"];return <AbsoluteFill style={{opacity:gate(f,526,534,642,650)}}><Paper tone={P.mint}/><div style={{position:"absolute",left:vertical?60:100,top:vertical?330:160,width:vertical?900:780}}><Type size={vertical?97:112} style={{transform:"rotate(-2deg)"}}>not a demo.</Type><Type size={vertical?70:78} color={P.blue} style={{marginTop:24}}>a real question.<br/>a useful answer.</Type></div><div style={{position:"absolute",right:vertical?60:120,top:vertical?760:125,width:vertical?760:720,display:"grid",gridTemplateColumns:vertical?"1fr":"1fr 1fr",gap:22}}>{facts.map((x,i)=><div key={x} style={{opacity:pop(local,i*12),transform:`translateX(${(1-pop(local,i*12))*120}px) rotate(${i%2?-2:2}deg)`}}><Stamp color={[P.citrus,P.coral,P.paper,P.blue][i]} size={vertical?27:25}>{x}</Stamp></div>)}</div></AbsoluteFill>};

const Garden:React.FC<Format>=({vertical})=>{const f=useCurrentFrame();const local=f-640;const progress=q(local,0,70);return <AbsoluteFill style={{opacity:gate(f,638,644,790,798)}}><Paper tone={P.coral}/><Cable vertical={vertical} progress={progress} resolved={local>110}/><div style={{position:"absolute",left:vertical?55:100,top:vertical?310:145,zIndex:5,width:vertical?950:960}}><Type size={vertical?84:100} color={P.white} style={{textShadow:`6px 7px 0 ${P.ink}`,transform:"rotate(-2deg)"}}>the conversation<br/>moves the real world.</Type></div><div style={{position:"absolute",left:vertical?80:240,top:vertical?760:500,zIndex:6,opacity:pop(local,5)}}><Stamp color={P.paper} size={vertical?33:30}>REAL CALL</Stamp></div><div style={{position:"absolute",right:vertical?65:230,top:vertical?1040:400,zIndex:6,display:"grid",gap:20}}>{["5,000 SQ YD","THURSDAY · 2 PM","ESTIMATE SLOT HELD"].map((x,i)=><div key={x} style={{opacity:pop(local,35+i*25),transform:`translateX(${(1-pop(local,35+i*25))*180}px)`}}><Stamp color={i===2?P.mint:P.citrus} size={vertical?27:27} rotate={i-1}>{x}</Stamp></div>)}</div><div style={{position:"absolute",left:vertical?55:430,right:vertical?55:430,bottom:vertical?250:70,zIndex:7,background:P.ink,color:P.white,padding:"20px 25px",fontFamily:mono,fontWeight:700,fontSize:vertical?25:21,lineHeight:1.3,textAlign:"center"}}>“We will hold that spot for you until then.”</div></AbsoluteFill>};

const End:React.FC<Format>=({vertical})=>{const f=useCurrentFrame();const local=f-786;const icon=vertical?62:50;return <AbsoluteFill style={{opacity:q(f,784,792)}}><Paper/><div style={{position:"absolute",left:vertical?55:110,top:vertical?300:155,width:vertical?950:1500}}><Type size={vertical?83:105} style={{opacity:pop(local,0),transform:"rotate(-2deg)"}}>the other side of the call</Type><Type size={vertical?83:105} color={P.blue} style={{opacity:pop(local,14)}}>is changing.</Type><Type size={vertical?90:116} color={P.coral} style={{marginTop:36,opacity:pop(local,34),transform:"rotate(1deg)"}}>the outcome isn't.</Type></div><div style={{position:"absolute",left:"50%",top:vertical?1130:620,width:vertical?720:700,height:vertical?220:180,transform:`translate(-50%,-50%) scale(${.6+.4*pop(local,65)})`,filter:"invert(1)"}}><Img src={staticFile("brand/asmi-logo-white.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div style={{position:"absolute",left:0,right:0,top:vertical?1300:740,textAlign:"center",fontFamily:mono,fontWeight:700,fontSize:vertical?25:23,opacity:pop(local,82)}}>built for the real world. whoever answers.</div><div style={{position:"absolute",left:0,right:0,top:vertical?1440:845,display:"flex",alignItems:"center",justifyContent:"center",gap:18,fontFamily:display,fontWeight:800,fontSize:vertical?48:42,opacity:pop(local,98)}}><span>text asmi.</span><span style={{width:icon,height:icon,borderRadius:13,background:"#34C759",color:P.white,display:"grid",placeItems:"center",fontSize:icon*.55}}>●</span><span style={{width:icon,height:icon,borderRadius:"50%",background:"#25D366",color:P.white,display:"grid",placeItems:"center",fontSize:icon*.52}}>☎</span></div></AbsoluteFill>};

export const AiToAiFilm:React.FC<Format>=({vertical})=><AbsoluteFill style={{background:P.paper,overflow:"hidden"}}>
  <Proof vertical={vertical}/><AiReveal vertical={vertical}/><Useful vertical={vertical}/><Garden vertical={vertical}/><End vertical={vertical}/>
  <Audio src={staticFile("audio/bgm-v9.mp3")} volume={(f)=>interpolate(f,[0,80,105,120,520,535,635,645,785,800,890],[.72,.92,.86,.12,.12,.88,.78,.12,.12,.86,.42],clamp)}/>
  <Sequence from={120} durationInFrames={450}><Audio src={staticFile("audio/ai-calls/hermans-ai-excerpt.mp3")} volume={1.25}/></Sequence>
  <Sequence from={650} durationInFrames={174}><Audio src={staticFile("audio/ai-calls/gardening-hold-excerpt.mp3")} volume={1.3}/></Sequence>
  {[4,55,108,225,535,642,720,790,850].map((at,i)=><Sequence key={at} from={at}><Audio src={staticFile(i%2?"audio/sfx/wa-pop.mp3":"audio/sfx/imessage-receive.mp3")} volume={.18}/></Sequence>)}
</AbsoluteFill>;