import React from "react";
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {loadFont as loadDisplay} from "@remotion/google-fonts/BricolageGrotesque";

const {fontFamily:display}=loadDisplay("normal",{weights:["500","600","700","800"],subsets:["latin"]});
const mono='"Space Mono","SFMono-Regular",Consolas,monospace';
const UI='-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",Arial,sans-serif';
const P={paper:"#FBF7F0",ink:"#141318",blue:"#2F5BFF",coral:"#FF5A47",citrus:"#E8FF5A",mint:"#35D6A4",violet:"#8B5CF6",white:"#FFFDF8",grey:"#E8E3DA"};
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
const ease=(x:number)=>1-Math.pow(1-x,4);
const q=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{...clamp,easing:ease});
const windowed=(f:number,a:number,b:number,c:number,d:number)=>q(f,a,b)*(1-q(f,c,d));
const pop=(f:number,at:number,fps:number)=>spring({frame:f-at,fps,config:{damping:18,stiffness:380,mass:.7}});
const z=(n:number)=>({zIndex:n});

type V={vertical:boolean};

const Paper:React.FC<{tone?:string;grid?:boolean}>=({tone=P.paper,grid=true})=> <AbsoluteFill style={{background:tone,overflow:"hidden"}}>
  {grid&&<AbsoluteFill style={{opacity:.12,backgroundImage:`linear-gradient(${P.ink} 1px, transparent 1px),linear-gradient(90deg,${P.ink} 1px,transparent 1px)`,backgroundSize:"44px 44px"}}/>}
  <AbsoluteFill style={{opacity:.12,mixBlendMode:"multiply",backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.28'/%3E%3C/svg%3E\")"}}/>
</AbsoluteFill>;

const ImpactWord:React.FC<{children:React.ReactNode;color?:string;size:number;rotate?:number;style?:React.CSSProperties}>=({children,color=P.ink,size,rotate=0,style})=><div style={{fontFamily:display,fontSize:size,fontWeight:800,lineHeight:.86,letterSpacing:0,color,transform:`rotate(${rotate}deg)`,...style}}>{children}</div>;

const Hook:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const words=[{t:"the most irritating",a:0,b:18,c:P.ink,s:vertical?106:150,x:vertical?58:110,y:vertical?470:230,r:-2},{t:"assistant.",a:17,b:37,c:P.blue,s:vertical?180:260,x:vertical?54:105,y:vertical?650:350,r:1},{t:"for them.",a:36,b:60,c:P.coral,s:vertical?150:220,x:vertical?70:108,y:vertical?880:585,r:-1}];return <AbsoluteFill><Paper/>{words.map((w,i)=>{const p=pop(f,w.a,30);const out=i<2?q(f,w.b,w.b+7):0;return <ImpactWord key={w.t} size={w.s} color={w.c} rotate={w.r} style={{position:"absolute",left:w.x,top:w.y,opacity:p*(1-out),transform:`translateX(${(1-p)*(i%2?-260:260)}px) rotate(${w.r}deg) scale(${.65+.35*p})`}}>{w.t}</ImpactWord>})}<div style={{position:"absolute",left:vertical?90:145,top:vertical?1115:755,width:q(f,43,57)*(vertical?760:1180),height:vertical?28:22,background:P.citrus,transform:"rotate(-2deg)"}}/></AbsoluteFill>};

const TASKS=[
  {t:"find a dentist",icon:"✚"},{t:"plan date night",icon:"♥"},{t:"book a car wash",icon:"◇"},{t:"coordinate carpool",icon:"↗"},
  {t:"order a birthday cake",icon:"♜"},{t:"get moving boxes",icon:"□"},{t:"book a haircut",icon:"✂"},{t:"cancel my gym",icon:"×"},
];
const TaskRush:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=windowed(f,48,58,140,154);const speed=q(f,48,152);return <AbsoluteFill style={{opacity:a,overflow:"hidden",background:P.citrus}}><div style={{position:"absolute",inset:0,transform:`rotate(-5deg) scale(1.12) translateY(${vertical?0:-30}px)`}}>{[0,1,2,3].map((row)=>{const ordered=[...TASKS.slice(row*2),...TASKS.slice(0,row*2),...TASKS.slice(row),...TASKS.slice(0,row)];return <div key={row} style={{position:"absolute",top:(vertical?310:90)+row*(vertical?330:225),left:0,right:0,height:vertical?210:150,background:row%2?P.paper:P.blue,color:row%2?P.ink:P.white,borderTop:`${vertical?7:5}px solid ${P.ink}`,borderBottom:`${vertical?7:5}px solid ${P.ink}`,display:"flex",alignItems:"center",gap:vertical?52:40,transform:`translateX(${(row%2?-1:1)*(speed*(vertical?1380:1700)-(vertical?720:1050))}px)`}}>{ordered.map((task,i)=><React.Fragment key={`${row}-${i}`}><span style={{width:vertical?82:65,height:vertical?82:65,flex:"0 0 auto",borderRadius:"50%",border:`${vertical?5:4}px solid currentColor`,display:"grid",placeItems:"center",fontFamily:display,fontSize:vertical?44:36,fontWeight:800}}>{task.icon}</span><span style={{fontFamily:display,fontWeight:800,fontSize:vertical?54:48,whiteSpace:"nowrap"}}>{task.t}</span></React.Fragment>)}</div>})}</div><div style={{position:"absolute",left:"50%",top:"50%",width:vertical?610:520,height:vertical?360:310,background:P.coral,border:`${vertical?9:7}px solid ${P.ink}`,transform:`translate(-50%,-50%) rotate(-4deg) scale(${.55+.45*pop(f,105,30)})`,boxShadow:`${vertical?20:15}px ${vertical?24:18}px 0 ${P.ink}`,display:"grid",placeItems:"center",opacity:q(f,102,112)}}><Img src={staticFile("cutouts/gymcard.png")} style={{position:"absolute",width:"38%",left:"4%",bottom:"-12%",transform:"rotate(-12deg)"}}/><ImpactWord size={vertical?95:82} color={P.white} style={{textAlign:"center",maxWidth:"74%"}}>cancel<br/>my gym.</ImpactWord></div></AbsoluteFill>};

const Status:React.FC<{dark?:boolean;s:number}>=({dark=true,s})=><div style={{height:52*s,display:"flex",alignItems:"center",justifyContent:"space-between",padding:`0 ${27*s}px`,fontFamily:UI,fontWeight:700,fontSize:15*s,color:dark?P.ink:P.white,position:"relative",zIndex:20}}><span>9:41</span><span style={{display:"flex",gap:7*s}}><b>▮▮▮</b><b>◒</b><span style={{border:"1px solid currentColor",borderRadius:4*s,padding:`0 ${4*s}px`}}>86</span></span></div>;
const Header:React.FC<{s:number;name:string;light?:boolean}>=({s,name,light})=><><Status s={s} dark={light}/><div style={{height:88*s,borderBottom:`1px solid ${light?"#D5D5D8":"#313137"}`,display:"flex",alignItems:"center",justifyContent:"center",color:light?P.ink:P.white,fontFamily:UI,position:"relative"}}><span style={{position:"absolute",left:22*s,color:P.blue,fontSize:34*s}}>‹</span><div style={{textAlign:"center",fontSize:16*s,fontWeight:600}}><div style={{width:40*s,height:40*s,margin:"0 auto 3px",borderRadius:"50%",background:name==="asmi"?P.coral:"#666",display:"grid",placeItems:"center",color:P.white,fontWeight:800}}>{name==="asmi"?"a":"MG"}</div>{name}</div></div></>;
const Bubble:React.FC<{s:number;mine?:boolean;children:React.ReactNode;light?:boolean}>=({s,mine,children,light})=><div style={{alignSelf:mine?"flex-end":"flex-start",maxWidth:"86%",background:mine?P.blue:(light?"#E9E9ED":"#2A2A2E"),color:mine?P.white:(light?P.ink:P.white),borderRadius:25*s,padding:`${13*s}px ${18*s}px`,fontFamily:UI,fontSize:25*s,lineHeight:1.22,boxShadow:"0 8px 18px rgba(0,0,0,.12)"}}>{children}</div>;

const AskScreen:React.FC<{s:number;local:number}>=({s,local})=><AbsoluteFill style={{background:"#000"}}><Header s={s} name="asmi"/><div style={{padding:`${30*s}px ${24*s}px`,display:"flex",flexDirection:"column",gap:15*s}}>{[
  [true,"they won't let me cancel my gym. i've tried twice.",0],[false,"send me your member ID.",11],[true,"GX-88214",23],[false,"got it. don't think about it again.",35]
].map(([mine,text,at],i)=>{const p=pop(local,Number(at),30);return <div key={i} style={{display:"flex",flexDirection:"column",opacity:p,transform:`translateY(${(1-p)*22}px) scale(${.94+.06*p})`}}><Bubble s={s} mine={Boolean(mine)}>{String(text)}</Bubble></div>})}</div></AbsoluteFill>;
const CallScreen:React.FC<{s:number;local:number;connected?:boolean}>=({s,local,connected})=><AbsoluteFill style={{background:"linear-gradient(180deg,#303136,#050506 72%)",color:P.white,fontFamily:UI}}><Status s={s} dark={false}/><div style={{textAlign:"center",paddingTop:100*s}}><div style={{fontSize:47*s,fontWeight:600}}>Mission Gym</div><div style={{fontSize:21*s,color:connected?P.mint:"#AAA",marginTop:10*s}}>{connected?"connected  00:18":local<28?"calling…":"voicemail"}</div><div style={{width:148*s,height:148*s,borderRadius:"50%",background:"linear-gradient(145deg,#7A7A7E,#303034)",display:"grid",placeItems:"center",margin:`${85*s}px auto`,fontSize:42*s,fontWeight:700}}>MG</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:27*s,padding:`0 ${78*s}px`}}>{["mute","keypad","audio","add call","FaceTime","contacts"].map((x,i)=><div key={x} style={{fontSize:14*s,display:"grid",justifyItems:"center",gap:7*s}}><span style={{width:76*s,height:76*s,borderRadius:"50%",background:"rgba(255,255,255,.15)",display:"grid",placeItems:"center",fontSize:22*s}}>{["—","•••","◖","+","□","◎"][i]}</span>{x}</div>)}</div></div><div style={{position:"absolute",left:"50%",bottom:55*s,transform:"translateX(-50%)",width:88*s,height:88*s,borderRadius:"50%",background:connected?P.mint:P.coral,display:"grid",placeItems:"center",fontSize:35*s}}>☎</div></AbsoluteFill>;
const TextScreen:React.FC<{s:number;local:number}>=({s,local})=><AbsoluteFill style={{background:"#000"}}><Header s={s} name="Mission Gym"/><div style={{padding:`${28*s}px ${23*s}px`,display:"flex",flexDirection:"column",gap:14*s}}>{[
 [true,"Hi — confirming cancellation for GX-88214. Please send written confirmation."],[false,"Cancellations must be completed in person."],[true,"Your agreement allows written notice. I've emailed it now."]
].map((x,i)=>{const p=pop(local,i*14,30);return <div key={i} style={{display:"flex",flexDirection:"column",opacity:p,transform:`translateX(${(1-p)*(i%2? -60:60)}px)`}}><Bubble s={s} mine={Boolean(x[0])}>{String(x[1])}</Bubble></div>})}</div></AbsoluteFill>;
const MailScreen:React.FC<{s:number}>=({s})=><AbsoluteFill style={{background:"#F8F8FA",color:P.ink,fontFamily:UI}}><Status s={s}/><div style={{height:70*s,borderBottom:"1px solid #D2D2D6",display:"flex",alignItems:"center",justifyContent:"space-between",padding:`0 ${22*s}px`,fontSize:22*s,color:P.blue}}><span>Cancel</span><b style={{color:P.ink}}>New Message</b><span style={{fontSize:30*s}}>↑</span></div>{[["To:","cancellations@missiongym.com"],["Subject:","Cancellation notice - GX-88214"]].map(x=><div key={x[0]} style={{padding:`${17*s}px ${21*s}px`,borderBottom:"1px solid #D8D8DC",fontSize:21*s,display:"flex",gap:11*s}}><span style={{color:"#777"}}>{x[0]}</span><span>{x[1]}</span></div>)}<div style={{padding:`${24*s}px`,fontSize:24*s,lineHeight:1.45}}><p>Hello,</p><p>Please accept this as written notice to cancel membership <b>GX-88214</b> under section 4.2.</p><p>Please confirm in writing and refund the final <b>$59 charge.</b></p><p>Thank you.</p></div></AbsoluteFill>;

const Phone:React.FC<{vertical:boolean;children:React.ReactNode;frame:number;pose?:number;scale?:number}>=({vertical,children,frame,pose=0,scale=1})=>{const w=vertical?650:430,h=vertical?1407:930,r=vertical?98:65;return <div style={{width:w,height:h,position:"relative",transformStyle:"preserve-3d",transform:`perspective(1900px) rotateY(${pose}deg) rotateZ(${Math.sin(frame/23)*.35}deg) scale(${scale})`,filter:"drop-shadow(0 50px 50px rgba(20,19,24,.35))"}}><div style={{position:"absolute",inset:-8,borderRadius:r+8,background:"linear-gradient(100deg,#343438 0%,#F1EEE7 10%,#6D6C70 27%,#17171A 58%,#D6D1C8 84%,#38383B 100%)",boxShadow:"inset 0 0 0 2px rgba(255,255,255,.85),inset 0 0 0 7px #19191B"}}/><div style={{position:"absolute",left:-15,top:h*.2,width:15,height:h*.16,borderRadius:"7px 0 0 7px",background:"linear-gradient(90deg,#333,#AAA)"}}/><div style={{position:"absolute",right:-15,top:h*.27,width:15,height:h*.16,borderRadius:"0 7px 7px 0",background:"linear-gradient(90deg,#AAA,#333)"}}/><div style={{position:"absolute",inset:6,borderRadius:r-4,background:"#000",overflow:"hidden",boxShadow:"inset 0 0 0 2px #050506"}}>{children}<div style={{position:"absolute",top:vertical?18:12,left:"50%",transform:"translateX(-50%)",width:vertical?124:82,height:vertical?36:24,borderRadius:30,background:"#000",zIndex:40}}/><div style={{position:"absolute",bottom:vertical?11:7,left:"50%",transform:"translateX(-50%)",width:vertical?126:83,height:vertical?5:3,borderRadius:4,background:"rgba(255,255,255,.85)",zIndex:40}}/></div></div>};

const FlashLabel:React.FC<{text:string;color:string;at:number;vertical:boolean}>=({text,color,at,vertical})=>{const f=useCurrentFrame();const p=pop(f,at,30);const out=q(f,at+12,at+19);return <ImpactWord size={vertical?170:190} color={color} rotate={at%2?-5:4} style={{position:"absolute",left:"50%",top:"50%",transform:`translate(-50%,-50%) rotate(${at%2?-5:4}deg) scale(${.25+p*1.05})`,opacity:p*(1-out),textShadow:`8px 9px 0 ${P.ink}`,whiteSpace:"nowrap",...z(60)}}>{text}</ImpactWord>};

const Chase:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const start=150;const end=528;const enter=pop(f,start,30);const phase=f<230?0:f<310?1:f<390?2:f<470?3:4;const starts=[150,230,310,390,470];const local=f-starts[phase];const s=vertical?1:.66;const children=[<AskScreen key="ask" s={s} local={local}/>,<CallScreen key="call" s={s} local={local}/>,<TextScreen key="text" s={s} local={local}/>,<MailScreen key="mail" s={s}/>,<CallScreen key="again" s={s} local={local} connected/>];const bg=[P.coral,P.blue,P.citrus,P.mint,P.blue][phase];const swipe=q(local,0,11);const pose=[-3,4,-4,3,0][phase];return <AbsoluteFill style={{opacity:windowed(f,142,150,520,535),overflow:"hidden",background:bg}}><div style={{position:"absolute",fontFamily:mono,fontWeight:700,fontSize:vertical?25:20,left:vertical?50:75,top:vertical?55:45,color:phase===2?P.ink:P.white,letterSpacing:0}}>{["ONE MESSAGE.","CALL.","TEXT.","EMAIL.","CALL AGAIN."][phase]}</div><div style={{position:"absolute",left:vertical?"50%":"70%",top:"51%",transform:`translate(-50%,-50%) translateX(${(1-enter)*(vertical?950:1200)}px) rotate(${(1-enter)*10}deg)`}}><Phone vertical={vertical} frame={f} pose={pose} scale={vertical?.91:1.0}>{children.map((child,i)=><div key={i} style={{position:"absolute",inset:0,opacity:i===phase?1:0,clipPath:i===phase?`inset(0 ${100-swipe*100}% 0 0 round ${vertical?90:58}px)`:undefined}}>{child}</div>)}</Phone></div>{phase>0&&phase<4&&<svg style={{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"none",...z(50)}}><path d={vertical?"M 885 1340 C 1040 1180 1020 760 900 590":"M 1540 760 C 1780 630 1750 290 1500 220"} fill="none" stroke={phase===1?P.coral:phase===2?P.blue:P.mint} strokeWidth={vertical?15:11} strokeLinecap="round" strokeDasharray="900" strokeDashoffset={900-q(local,0,22)*900}/></svg>}<FlashLabel text={phase===1&&local>28?"VOICEMAIL":phase===4&&local>20?"CONNECTED":""} color={phase===4?P.mint:P.coral} at={phase===1?258:490} vertical={vertical}/></AbsoluteFill>};

const Win:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=windowed(f,520,530,600,613);const lines=[{t:"cancelled.",at:528,c:P.ink},{t:"$59 refunded.",at:545,c:P.blue},{t:"GX-88214 confirmed.",at:562,c:P.ink}];return <AbsoluteFill style={{opacity:a,overflow:"hidden"}}><Paper/>{lines.map((x,i)=>{const p=pop(f,x.at,30);return <ImpactWord key={x.t} size={vertical?110-i*7:128-i*5} color={x.c} rotate={i===1?1:-1} style={{position:"absolute",left:vertical?60:140,top:(vertical?400:180)+i*(vertical?190:145),transform:`translateX(${(1-p)*(i%2?900:-900)}px) rotate(${i===1?1:-1}deg)`}}>{x.t}</ImpactWord>})}<div style={{position:"absolute",left:"50%",top:vertical?1100:700,transform:`translate(-50%,-50%) rotate(-3deg) scale(${pop(f,580,30)})`,border:`${vertical?9:7}px solid ${P.coral}`,color:P.coral,padding:vertical?"32px 42px":"25px 38px",fontFamily:display,fontSize:vertical?55:50,fontWeight:800,textTransform:"uppercase",whiteSpace:"nowrap",boxShadow:`8px 10px 0 ${P.ink}`}}>she doesn't stop until it's done.</div></AbsoluteFill>};

const MoreWins:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=windowed(f,600,610,680,693);const items=[["✚","dentist confirmed",P.blue],["♥","date night planned",P.coral],["□","moving boxes delivered",P.mint],["♜","cake ordered",P.citrus]];return <AbsoluteFill style={{opacity:a,background:P.ink,overflow:"hidden"}}><div style={{position:"absolute",top:vertical?540:300,left:0,display:"flex",gap:vertical?35:50,transform:`translateX(${interpolate(f,[600,690],[vertical?900:1500,vertical?-2200:-1600],clamp)}px) rotate(-2deg)`}}>{items.map((it,i)=><div key={i} style={{width:vertical?560:530,height:vertical?280:245,background:String(it[2]),border:`${vertical?8:6}px solid ${P.white}`,boxShadow:`15px 17px 0 ${P.white}`,display:"flex",alignItems:"center",gap:30,padding:35,boxSizing:"border-box"}}><div style={{fontSize:vertical?100:85,color:P.ink}}>{it[0]}</div><ImpactWord size={vertical?63:60} color={P.ink}>{it[1]}</ImpactWord></div>)}</div></AbsoluteFill>};

const Languages:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=windowed(f,678,686,758,770);const langs=[
  ["English","confirmed"],["Español","confirmado"],["हिन्दी","पुष्टि हो गई"],["中文","已确认"],["العربية","تم التأكيد"],["Français","confirmé"],
  ["Português","confirmado"],["日本語","確認済み"],["한국어","확인 완료"],["Deutsch","bestätigt"],["Bahasa","dikonfirmasi"],["Türkçe","onaylandı"],
];const orbit=q(f,680,758);const cols=vertical?2:4;return <AbsoluteFill style={{opacity:a,overflow:"hidden",background:P.blue,color:P.white}}><div style={{position:"absolute",inset:vertical?"95px 45px 430px":"48px 65px 255px",display:"grid",gridTemplateColumns:`repeat(${cols},1fr)`,gap:vertical?18:16,transform:`rotate(${(orbit-.5)*2}deg) scale(${1.08-.08*orbit})`}}>{langs.map(([language,text],i)=>{const p=pop(f,680+i*3,30);return <div key={language} style={{background:[P.coral,P.mint,P.citrus,P.paper][i%4],color:P.ink,border:`${vertical?5:4}px solid ${P.ink}`,boxShadow:`${vertical?7:5}px ${vertical?8:6}px 0 ${P.ink}`,padding:vertical?"18px 17px":"12px 16px",transform:`translateY(${(1-p)*(i%2?-120:120)}px) rotate(${Math.sin(i*7)*2}deg)`,opacity:p,display:"flex",flexDirection:"column",justifyContent:"center",minHeight:vertical?105:78}}><span style={{fontFamily:mono,fontSize:vertical?16:14,fontWeight:700,opacity:.65}}>{language.toUpperCase()}</span><span style={{fontFamily:UI,fontSize:vertical?30:27,fontWeight:800,whiteSpace:"nowrap"}}>{text}</span></div>})}</div><div style={{position:"absolute",left:"50%",bottom:vertical?95:43,transform:`translateX(-50%) scale(${.72+.28*pop(f,713,30)})`,background:P.ink,color:P.white,border:`${vertical?7:5}px solid ${P.citrus}`,boxShadow:`${vertical?13:9}px ${vertical?14:10}px 0 ${P.coral}`,padding:vertical?"23px 36px 25px":"17px 42px 18px",textAlign:"center",minWidth:vertical?790:760}}><div style={{display:"flex",alignItems:"baseline",justifyContent:"center",gap:vertical?18:15}}><ImpactWord size={vertical?155:150} color={P.citrus}>50+</ImpactWord><ImpactWord size={vertical?64:62} color={P.white}>languages.</ImpactWord></div><div style={{fontFamily:mono,fontSize:vertical?22:18,fontWeight:700,marginTop:8}}>different language. same chase.</div></div></AbsoluteFill>};

const Receipt:React.FC<{i:number;vertical:boolean;social?:boolean}>=({i,vertical,social})=>{const f=useCurrentFrame();const cols=vertical?10:18;const col=i%cols,row=Math.floor(i/cols);const reveal=pop(f,768+(i%17),30);const colors=social?[P.blue,P.coral,P.citrus,P.mint,P.violet]:[P.white,P.citrus,P.mint,P.coral];return <div style={{position:"absolute",left:`${(col+.5)*100/cols}%`,top:`${(row+.5)*100/(vertical?17:8)}%`,width:vertical?105:112,height:vertical?78:82,background:colors[i%colors.length],border:`2px solid ${P.ink}`,display:"grid",placeItems:"center",fontFamily:mono,fontWeight:700,fontSize:vertical?13:12,color:P.ink,transform:`translate(-50%,-50%) scale(${.25+.75*reveal}) rotate(${Math.sin(i*8.7)*4}deg)`,boxShadow:"4px 5px 0 rgba(20,19,24,.55)"}}>{social?(i%4===0?"▶ 8.4M":i%4===1?"♥ 912K":i%4===2?"↗ 4.1M":"● 2.7M"):(i%4===0?"DONE":i%4===1?"BOOKED":i%4===2?"REFUND":"CONFIRMED")}</div>};
const Proof:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const swap=q(f,833,846);const a=windowed(f,760,770,894,906);const count=vertical?170:144;const one=windowed(f,790,800,827,838),two=q(f,842,852);const plate:React.CSSProperties={background:P.paper,border:`${vertical?7:5}px solid ${P.ink}`,boxShadow:`${vertical?14:10}px ${vertical?16:12}px 0 ${P.ink}`,padding:vertical?"32px 38px":"25px 48px",transform:"rotate(-1deg)"};return <AbsoluteFill style={{opacity:a,overflow:"hidden",background:P.paper}}><div style={{position:"absolute",inset:"-4%",opacity:1-swap,transform:`scale(${1.35-.25*q(f,760,810)})`}}>{Array.from({length:count},(_,i)=><Receipt key={i} i={i} vertical={vertical}/>)}</div><div style={{position:"absolute",inset:"-4%",opacity:swap,transform:`scale(${1.3-.22*q(f,833,865)})`}}>{Array.from({length:count},(_,i)=><Receipt key={i} i={i} vertical={vertical} social/>)}</div><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",textAlign:"center",opacity:one}}><div style={plate}><ImpactWord size={vertical?245:275} color={P.ink}>20,000</ImpactWord><ImpactWord size={vertical?55:55} color={P.ink}>real-world tasks completed</ImpactWord><div style={{fontFamily:mono,fontSize:vertical?23:20,fontWeight:700,marginTop:20}}>IN THE PAST 30 DAYS</div></div></div><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",textAlign:"center",opacity:two}}><div style={plate}><ImpactWord size={vertical?350:380} color={P.ink}>30M</ImpactWord><ImpactWord size={vertical?56:58} color={P.ink}>people checked out asmi on socials</ImpactWord><div style={{fontFamily:mono,fontSize:vertical?23:20,fontWeight:700,marginTop:20}}>IN THE PAST 30 DAYS</div></div></div></AbsoluteFill>};

const End:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const p=pop(f,900,30),line=pop(f,920,30),cta=pop(f,940,30);return <AbsoluteFill style={{opacity:q(f,895,903)}}><Paper/><div style={{position:"absolute",left:"50%",top:vertical?680:295,width:vertical?820:930,height:vertical?300:310,transform:`translate(-50%,-50%) scale(${.5+.5*p}) rotate(${(1-p)*-5}deg)`,filter:"invert(1)"}}><Img src={staticFile("brand/asmi-logo-white.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><ImpactWord size={vertical?67:66} color={P.ink} style={{position:"absolute",left:0,right:0,top:vertical?1000:575,textAlign:"center",opacity:line,transform:`scale(${.85+.15*line})`}}>she doesn't stop until it's done.</ImpactWord><div style={{position:"absolute",left:0,right:0,top:vertical?1190:730,display:"flex",justifyContent:"center",alignItems:"center",gap:20,opacity:cta,transform:`translateY(${(1-cta)*35}px)`,fontFamily:mono,fontWeight:700,fontSize:vertical?25:21}}><span>text asmi.</span><span style={{width:vertical?54:47,height:vertical?54:47,borderRadius:13,background:P.blue,display:"grid",placeItems:"center",color:P.white,fontFamily:UI,fontSize:25}}>●</span><span style={{width:vertical?54:47,height:vertical?54:47,borderRadius:"50%",background:"#25D366",display:"grid",placeItems:"center",color:P.white,fontFamily:UI,fontSize:25}}>☎</span></div><div style={{position:"absolute",left:"50%",top:vertical?1340:825,width:q(f,925,950)*(vertical?760:1000),height:vertical?24:18,background:P.coral,transform:"translateX(-50%) rotate(-1deg)"}}/></AbsoluteFill>};

export const HighlightVideoV9:React.FC<V>=({vertical})=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:P.paper,overflow:"hidden"}}>
  <Hook vertical={vertical}/><TaskRush vertical={vertical}/><Chase vertical={vertical}/><Win vertical={vertical}/><MoreWins vertical={vertical}/><Languages vertical={vertical}/><Proof vertical={vertical}/><End vertical={vertical}/>
  <Audio src={staticFile("audio/bgm-v9.mp3")} volume={(x)=>interpolate(x,[0,8,515,522,535,750,770,885,945,959],[.9,1,1,.15,.92,.96,1,1,.82,.45],clamp)}/>
  <Sequence from={55}><Audio src={staticFile("audio/sfx/wa-pop.mp3")} volume={.22}/></Sequence>
  {[150,230,310,390,470,528,545,580,610,680,768,833,900,940].map((at,i)=><Sequence key={at} from={at}><Audio src={staticFile(i%3===0?"audio/sfx/imessage-receive.mp3":"audio/sfx/wa-pop.mp3")} volume={i===5?.38:.18}/></Sequence>)}
</AbsoluteFill>};
