import React from "react";
import {AbsoluteFill,Audio,Sequence,interpolate,spring,staticFile,useCurrentFrame,useVideoConfig} from "remotion";
import {loadFont as loadDisplay} from "@remotion/google-fonts/ArchivoBlack";
import {loadFont as loadSerif} from "@remotion/google-fonts/InstrumentSerif";

const {fontFamily:display}=loadDisplay("normal",{weights:["400"],subsets:["latin"]});
const {fontFamily:serif}=loadSerif("normal",{weights:["400"],subsets:["latin"]});
const C={night:"#090909",paper:"#F3F0E8",red:"#FF3B30",blue:"#0A84FF",green:"#30D158",grey:"#8E8E93",bubble:"#2C2C2E",mail:"#F7F7F8"};
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
const TOTAL=600;
const pop=(f:number,fps:number,d=0)=>spring({frame:f-d,fps,config:{damping:20,stiffness:260,mass:.65}});
const fade=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],clamp);

const Texture=()=> <AbsoluteFill style={{pointerEvents:"none",opacity:.16,mixBlendMode:"screen",backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.82' numOctaves='2'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.23'/%3E%3C/svg%3E\")"}}/>;
const Flash:React.FC<{at:number;color?:string}>=({at,color=C.paper})=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:color,opacity:interpolate(f,[at,at+1,at+4],[0,.75,0],clamp),pointerEvents:"none"}}/>};
const StatusBar:React.FC<{dark?:boolean}>=({dark})=><div style={{height:45,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 22px",fontFamily:"Arial",fontSize:16,fontWeight:700,color:dark?C.night:C.paper}}><span>9:41</span><span style={{letterSpacing:3}}>▮◉⌁</span></div>;
const Phone:React.FC<{vertical:boolean;children:React.ReactNode;light?:boolean;tilt?:number}>=({vertical,children,light,tilt=0})=><div style={{width:vertical?850:560,height:vertical?1370:830,borderRadius:vertical?78:55,background:light?C.mail:"#000",border:`${vertical?13:10}px solid #262629`,boxShadow:"0 34px 85px rgba(0,0,0,.55), inset 0 0 0 2px #4A4A4E",overflow:"hidden",position:"relative",transform:`rotate(${tilt}deg)`}}>{children}<div style={{position:"absolute",top:12,left:"50%",transform:"translateX(-50%)",width:vertical?235:154,height:vertical?48:32,borderRadius:30,background:"#050505",zIndex:10}}/></div>;

const Hook:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const one=pop(f,fps,2),two=pop(f,fps,34),them=pop(f,fps,65);return <AbsoluteFill style={{background:C.night,color:C.paper,overflow:"hidden"}}><Texture/><div style={{position:"absolute",left:vertical?55:95,top:vertical?400:160,width:vertical?920:1550}}><div style={{fontFamily:display,fontSize:vertical?122:142,lineHeight:.86,textTransform:"uppercase",transform:`translateX(${(1-one)*-150}px)`,opacity:one}}>the most irritating</div><div style={{fontFamily:display,fontSize:vertical?122:142,lineHeight:.86,textTransform:"uppercase",transform:`translateX(${(1-two)*150}px)`,opacity:two}}>assistant in the world.</div><div style={{marginTop:vertical?80:42,fontFamily:serif,fontStyle:"italic",fontSize:vertical?125:120,color:C.red,transform:`scale(${.65+them*.35})`,transformOrigin:"left",opacity:them}}>for them.</div></div><div style={{position:"absolute",right:40,bottom:30,fontFamily:"monospace",fontSize:14,color:C.grey}}>00:00:02:18</div><Flash at={62} color={C.red}/></AbsoluteFill>};

const ChatHeader=()=> <><StatusBar/><div style={{height:92,borderBottom:"1px solid #313134",display:"flex",alignItems:"center",justifyContent:"center",gap:12,fontFamily:"Arial",fontSize:20,fontWeight:600}}><span style={{position:"absolute",left:24,color:C.blue,fontSize:30}}>‹</span><span style={{width:45,height:45,borderRadius:"50%",background:C.red,display:"grid",placeItems:"center",fontWeight:700}}>a</span><span>asmi</span></div></>;
const Bubble:React.FC<{text:string;mine?:boolean;delay:number;vertical:boolean;small?:boolean}>=({text,mine,delay,vertical,small})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const a=pop(f,fps,delay);return <div style={{alignSelf:mine?"flex-end":"flex-start",maxWidth:"82%",background:mine?C.blue:C.bubble,color:C.paper,borderRadius:mine?"25px 25px 7px 25px":"25px 25px 25px 7px",padding:vertical?"17px 23px":"13px 18px",fontFamily:"Arial",fontSize:vertical?(small?30:37):(small?20:25),lineHeight:1.2,transform:`translateY(${(1-a)*30}px) scale(${.94+a*.06})`,opacity:a}}>{text}</div>};
const Ask:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const zoom=interpolate(f,[0,88],[1.06,1],clamp);return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 45%,#303035 0%,#111113 50%,#050505 100%)",display:"flex",alignItems:"center",justifyContent:"center",overflow:"hidden"}}><div style={{transform:`scale(${zoom})`}}><Phone vertical={vertical} tilt={vertical?-2:1}><AbsoluteFill style={{color:C.paper,background:"#000"}}><ChatHeader/><div style={{display:"flex",flexDirection:"column",gap:vertical?22:15,padding:vertical?"45px 28px":"29px 20px"}}><Bubble vertical={vertical} mine delay={3} text="they won’t let me cancel my gym. i’ve tried twice."/><Bubble vertical={vertical} delay={21} text="send me your member ID."/><Bubble vertical={vertical} mine delay={38} text="GX-88214"/><Bubble vertical={vertical} delay={55} text="got it. don’t think about it again."/></div><div style={{position:"absolute",bottom:24,left:22,right:22,height:53,border:"1px solid #4D4D50",borderRadius:28,color:C.grey,fontFamily:"Arial",fontSize:18,padding:"14px 18px"}}>iMessage</div></AbsoluteFill></Phone></div><div style={{position:"absolute",left:vertical?45:80,bottom:vertical?45:35,fontFamily:display,fontSize:vertical?35:31,color:C.paper,textTransform:"uppercase",opacity:fade(f,64,76)}}>one message. that’s it.</div></AbsoluteFill>};

const CallScreen:React.FC<{vertical:boolean;second:boolean;frame:number}>=({vertical,second,frame})=><Phone vertical={vertical} tilt={second?1.5:-1.5}><AbsoluteFill style={{background:"linear-gradient(#222225,#080809)",color:C.paper,fontFamily:"Arial"}}><StatusBar/><div style={{textAlign:"center",paddingTop:vertical?150:80}}><div style={{fontSize:vertical?58:40,fontWeight:600}}>Mission Gym</div><div style={{marginTop:12,fontSize:vertical?28:19,color:second?C.green:C.grey}}>{second?"connected · 00:18":frame<32?"calling…":frame<48?"on hold · 06:04":"voicemail"}</div><div style={{width:vertical?175:120,height:vertical?175:120,borderRadius:"50%",background:"#4A4A4E",display:"grid",placeItems:"center",fontSize:vertical?58:40,fontWeight:700,margin:`${vertical?120:65}px auto ${vertical?160:90}px`}}>MG</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:vertical?48:30,padding:`0 ${vertical?105:70}px`}}>{["mute","keypad","audio","add call","FaceTime","contacts"].map((x,i)=><div key={x} style={{display:"grid",justifyItems:"center",gap:9,fontSize:vertical?18:12}}><span style={{width:vertical?92:62,height:vertical?92:62,borderRadius:"50%",background:"#363639",display:"grid",placeItems:"center",fontSize:vertical?34:23}}>{["⌁","⊙","◖","+","▣","◉"][i]}</span>{x}</div>)}</div></div><div style={{position:"absolute",bottom:vertical?80:45,left:"50%",transform:"translateX(-50%)",width:vertical?98:68,height:vertical?98:68,borderRadius:"50%",background:C.red,display:"grid",placeItems:"center",fontSize:vertical?38:25}}>⌕</div></AbsoluteFill></Phone>;

const SmsScreen:React.FC<{vertical:boolean}>=({vertical})=><Phone vertical={vertical}><AbsoluteFill style={{background:"#000",color:C.paper}}><StatusBar/><div style={{height:90,borderBottom:"1px solid #303034",display:"grid",placeItems:"center",fontFamily:"Arial"}}><div style={{textAlign:"center"}}><b style={{fontSize:vertical?25:18}}>Mission Gym</b><div style={{fontSize:vertical?17:12,color:C.grey,marginTop:4}}>Text Message</div></div></div><div style={{display:"flex",flexDirection:"column",gap:vertical?22:15,padding:vertical?"45px 26px":"28px 18px"}}><Bubble vertical={vertical} mine delay={0} small text="Hi - confirming cancellation for membership GX-88214, effective today. Please send written confirmation."/><Bubble vertical={vertical} delay={12} small text="Cancellations have to be completed in person."/><Bubble vertical={vertical} mine delay={25} small text="Your agreement allows written notice. I’ve emailed it now."/></div><div style={{position:"absolute",bottom:25,left:22,right:22,height:52,border:"1px solid #4D4D50",borderRadius:26,color:C.grey,fontFamily:"Arial",fontSize:17,padding:"14px 18px"}}>Text Message</div></AbsoluteFill></Phone>;

const EmailScreen:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const sent=pop(f,30,22);return <Phone vertical={vertical} light><AbsoluteFill style={{background:C.mail,color:C.night,fontFamily:"Arial"}}><StatusBar dark/><div style={{height:70,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 22px",borderBottom:"1px solid #D8D8DC",color:C.blue,fontSize:vertical?25:18}}><span>Cancel</span><b style={{color:C.night}}>New Message</b><span style={{fontWeight:700,opacity:1-sent}}>Send</span></div><div style={{fontSize:vertical?27:18}}>{[["To:","cancellations@missiongym.com"],["Subject:","Cancellation notice - GX-88214"]].map(([a,b])=><div key={a} style={{display:"flex",gap:16,padding:vertical?"22px 25px":"15px 18px",borderBottom:"1px solid #D8D8DC"}}><span style={{color:C.grey}}>{a}</span><span>{b}</span></div>)}</div><div style={{padding:vertical?"38px 28px":"26px 20px",fontFamily:"Arial",fontSize:vertical?29:20,lineHeight:1.42}}><p>Hello,</p><p>Please accept this as written notice to cancel membership GX-88214, effective today, under section 4.2 of the agreement.</p><p>Please confirm the cancellation in writing and refund the final $59 charge.</p><p>Thank you.</p></div><div style={{position:"absolute",inset:0,background:C.mail,display:"grid",placeItems:"center",opacity:sent,pointerEvents:"none"}}><div style={{textAlign:"center"}}><div style={{fontSize:vertical?95:64,color:C.blue}}>✓</div><div style={{fontSize:vertical?33:22,fontWeight:700,marginTop:15}}>Message Sent</div></div></div></AbsoluteFill></Phone>};

const Chase:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const phase=f<50?0:f<105?1:f<160?2:3;const local=[f,f-50,f-105,f-160][phase];const a=pop(local,fps,0);return <AbsoluteFill style={{background:C.night,overflow:"hidden"}}><Texture/><div style={{position:"absolute",top:vertical?65:38,left:vertical?42:70,right:vertical?42:70,display:"flex",justifyContent:"space-between",alignItems:"center",zIndex:20,color:C.paper}}><div style={{fontFamily:display,fontSize:vertical?38:31,textTransform:"uppercase"}}>she starts chasing.</div><div style={{fontFamily:"monospace",fontSize:vertical?18:14,color:C.red}}>GX-88214 · {String(phase+1).padStart(2,"0")}/04</div></div><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",transform:`translateX(${(1-a)*(phase%2?180:-180)}px) scale(${.94+a*.06})`,opacity:a}}>{phase===0&&<CallScreen vertical={vertical} second={false} frame={local}/>} {phase===1&&<SmsScreen vertical={vertical}/>} {phase===2&&<EmailScreen vertical={vertical}/>} {phase===3&&<CallScreen vertical={vertical} second frame={local}/>}</div><div style={{position:"absolute",left:vertical?42:70,bottom:vertical?45:28,color:C.paper,fontFamily:"monospace",fontSize:vertical?21:16}}>{["CALL 01 · VOICEMAIL","SMS · WRITTEN REQUEST","MAIL · PAPER TRAIL","CALL 02 · CONNECTED"][phase]}</div>{[48,103,158].map(x=><Flash key={x} at={x}/>)}</AbsoluteFill>};

const translated=[{lang:"ES",text:"Confirme la cancelación por escrito."},{lang:"HI",text:"कृपया रद्दीकरण की लिखित पुष्टि करें।"},{lang:"中文",text:"请书面确认取消。"},{lang:"AR",text:"يرجى تأكيد الإلغاء كتابيًا."},{lang:"FR",text:"Veuillez confirmer l’annulation par écrit."},{lang:"日本語",text:"解約を書面で確認してください。"}];
const Language:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const index=Math.min(5,Math.floor(f/10));const lock=pop(f,fps,59);return <AbsoluteFill style={{background:C.night,color:C.paper,overflow:"hidden"}}><Texture/><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center"}}><div style={{width:vertical?900:1200,transform:`translateY(${interpolate(f,[0,58],[0,-80],clamp)}px)`,opacity:interpolate(f,[50,63],[1,0],clamp)}}><div style={{fontFamily:"Arial",fontSize:vertical?24:19,color:C.grey,marginBottom:18}}>Mission Gym · SMS</div><div style={{background:C.blue,borderRadius:"38px 38px 10px 38px",padding:vertical?"34px 38px":"27px 34px",fontFamily:"Arial",fontSize:vertical?48:42,lineHeight:1.18}}>{translated[index].text}</div><div style={{fontFamily:"monospace",fontSize:vertical?22:17,color:C.red,marginTop:18,textAlign:"right"}}>{translated[index].lang} · SENT</div></div></div><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",textAlign:"center",opacity:lock,transform:`scale(${.8+lock*.2})`}}><div><div style={{fontFamily:display,fontSize:vertical?190:205,lineHeight:.8}}>50+</div><div style={{fontFamily:display,fontSize:vertical?94:98,color:C.red,textTransform:"uppercase"}}>languages.</div><div style={{fontFamily:serif,fontStyle:"italic",fontSize:vertical?52:48,marginTop:28}}>same problem. still handled.</div></div></div><Flash at={58} color={C.red}/></AbsoluteFill>};

const Proof:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const a=pop(f,fps,2);return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 45%,#2A2A2D,#090909 68%)",display:"grid",placeItems:"center",overflow:"hidden"}}><Texture/><div style={{width:vertical?900:980,background:C.mail,borderRadius:vertical?38:28,boxShadow:"0 35px 100px rgba(0,0,0,.65)",overflow:"hidden",transform:`scale(${.78+a*.22}) rotate(${(1-a)*-4}deg)`,opacity:a}}><div style={{background:"#E8E8EA",padding:vertical?"24px 30px":"18px 25px",fontFamily:"Arial",fontSize:vertical?24:18,color:C.grey}}>MAIL · NOW</div><div style={{padding:vertical?"45px 42px":"34px 38px",fontFamily:"Arial",color:C.night}}><div style={{fontSize:vertical?28:21,color:C.grey}}>Mission Gym Member Services</div><div style={{fontSize:vertical?49:42,fontWeight:700,marginTop:16}}>Your membership has been cancelled.</div><div style={{height:1,background:"#D1D1D4",margin:"30px 0"}}/><div style={{display:"flex",justifyContent:"space-between",fontSize:vertical?34:29,fontWeight:700}}><span style={{color:C.green}}>$59 refunded</span><span>GX-88214</span></div></div></div><div style={{position:"absolute",bottom:vertical?85:50,fontFamily:display,fontSize:vertical?45:40,color:C.paper,textTransform:"uppercase",opacity:fade(f,20,32)}}>done. actually done.</div></AbsoluteFill>};

const End:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const a=pop(f,fps,1),line=pop(f,fps,18),cta=pop(f,fps,31);return <AbsoluteFill style={{background:C.night,color:C.paper,display:"flex",alignItems:"center",justifyContent:"center",textAlign:"center",overflow:"hidden",padding:vertical?55:90}}><Texture/><div style={{width:vertical?940:1500,transform:`scale(${.9+a*.1})`,opacity:a}}><div style={{fontFamily:serif,fontStyle:"italic",fontSize:vertical?210:205,lineHeight:.72}}>asmi</div><div style={{height:8,background:C.red,width:`${line*100}%`,margin:vertical?"45px auto 52px":"36px auto 38px"}}/><div style={{fontFamily:display,fontSize:vertical?72:80,lineHeight:.95,textTransform:"uppercase"}}>she doesn’t stop<br/>until it’s done.</div><div style={{display:"flex",justifyContent:"center",alignItems:"center",gap:18,marginTop:vertical?55:36,opacity:cta,fontFamily:"Arial",fontWeight:700,fontSize:vertical?25:20}}><span>text asmi</span><span style={{width:48,height:48,borderRadius:14,background:C.blue,display:"grid",placeItems:"center"}}>●</span><span style={{width:48,height:48,borderRadius:"50%",background:"#25D366",display:"grid",placeItems:"center"}}>☎</span></div></div></AbsoluteFill>};

export const HighlightVideo:React.FC<{vertical?:boolean}>=({vertical=false})=> <AbsoluteFill style={{background:C.night}}><Sequence from={0} durationInFrames={90}><Hook vertical={vertical}/></Sequence><Sequence from={90} durationInFrames={90}><Ask vertical={vertical}/></Sequence><Sequence from={180} durationInFrames={210}><Chase vertical={vertical}/></Sequence><Sequence from={390} durationInFrames={90}><Language vertical={vertical}/></Sequence><Sequence from={480} durationInFrames={60}><Proof vertical={vertical}/></Sequence><Sequence from={540} durationInFrames={60}><End vertical={vertical}/></Sequence><Sequence from={94} durationInFrames={25}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.55}/></Sequence><Sequence from={128} durationInFrames={25}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.42}/></Sequence><Sequence from={283} durationInFrames={25}><Audio src={staticFile("audio/sfx/wa-pop.mp3")} volume={.38}/></Sequence><Sequence from={478} durationInFrames={25}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.65}/></Sequence><Sequence from={538} durationInFrames={25}><Audio src={staticFile("audio/sfx/wa-pop.mp3")} volume={.75}/></Sequence><Audio src={staticFile("audio/bgm-v3.wav")} volume={(f)=>interpolate(f,[0,8,TOTAL-18,TOTAL-1],[0,.82,.82,0],clamp)}/></AbsoluteFill>;