import React from "react";
import {AbsoluteFill, Audio, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {loadFont as loadDisplay} from "@remotion/google-fonts/BricolageGrotesque";
import {loadFont as loadSerif} from "@remotion/google-fonts/InstrumentSerif";
import {loadFont as loadMono} from "@remotion/google-fonts/SpaceMono";

const {fontFamily: display}=loadDisplay("normal",{weights:["500","600","700","800"],subsets:["latin"]});
const {fontFamily: serif}=loadSerif("normal",{weights:["400"],subsets:["latin"]});
const {fontFamily: mono}=loadMono("normal",{weights:["400","700"],subsets:["latin"]});
const C={paper:"#FBF7F0",ink:"#141318",blue:"#2F5BFF",coral:"#FF5A47",citrus:"#E8FF5A",mint:"#35D6A4",cream:"#FFFDF8",dim:"#77727D",green:"#25D366"};
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
const S={hook:0,ask:90,chase:180,language:390,payoff:480,end:555};
const TOTAL=600;
const appear=(f:number,fps:number,d=0)=>spring({frame:f-d,fps,config:{damping:18,stiffness:240,mass:.7}});
const out=(f:number,a:number,b:number)=>interpolate(f,[a,b],[1,0],clamp);

const Grain=()=> <AbsoluteFill style={{pointerEvents:"none",opacity:.11,mixBlendMode:"multiply",backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.3'/%3E%3C/svg%3E\")"}}/>;
const Grid=()=> <AbsoluteFill style={{pointerEvents:"none",opacity:.28,backgroundImage:"linear-gradient(rgba(20,19,24,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(20,19,24,.07) 1px,transparent 1px)",backgroundSize:"32px 32px"}}/>;
const ChaseLine:React.FC<{progress:number;vertical:boolean}>=({progress,vertical})=><div style={{position:"absolute",left:vertical?74:110,top:vertical?245:112,width:vertical?12:"calc(100% - 220px)",height:vertical?"calc(100% - 490px)":12,background:C.coral,transform:vertical?`scaleY(${progress})`:`scaleX(${progress})`,transformOrigin:"top left",borderRadius:10,zIndex:1}}/>;

const Hook:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const a=appear(f,fps,5),reveal=appear(f,fps,55),slide=interpolate(f,[62,86],[0,vertical?-170:-100],clamp);return <AbsoluteFill style={{background:C.paper,overflow:"hidden"}}><Grid/><Grain/><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",textAlign:"center",padding:vertical?70:120,transform:`translateY(${slide}px)`}}><div><div style={{fontFamily:display,fontWeight:800,fontSize:vertical?105:124,lineHeight:.88,maxWidth:vertical?930:1500,opacity:a,transform:`scale(${.88+a*.12})`}}>the most <span style={{color:C.coral}}>irritating</span><br/>assistant in the world.</div><div style={{marginTop:vertical?65:44,fontFamily:display,fontWeight:800,fontSize:vertical?48:54,opacity:reveal,transform:`translateY(${(1-reveal)*35}px)`}}>annoying, but only to <span style={{background:C.citrus,padding:"2px 12px",border:`3px solid ${C.ink}`}}>them.</span></div></div></div></AbsoluteFill>};

const Ask:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const user=appear(f,fps,2),asmi=appear(f,fps,22);const steps=["CALL","TEXT","EMAIL","CALL AGAIN"];return <AbsoluteFill style={{background:C.blue,color:C.cream,overflow:"hidden",padding:vertical?"190px 56px 100px":"95px 125px"}}><Grain/><div style={{height:"100%",display:"flex",flexDirection:vertical?"column":"row",alignItems:"center",justifyContent:"center",gap:vertical?105:160}}><div style={{width:vertical?"100%":760}}><div style={{fontFamily:mono,fontSize:vertical?24:20,marginBottom:28,opacity:.8}}>MESSAGES · ASMI</div><div style={{marginLeft:"auto",maxWidth:vertical?800:700,background:C.cream,color:C.ink,borderRadius:"34px 34px 8px 34px",padding:vertical?"29px 34px":"23px 29px",fontFamily:display,fontSize:vertical?46:38,fontWeight:700,transform:`translateX(${(1-user)*120}px)`,opacity:user}}>cancel my gym. they keep dodging me.</div><div style={{marginTop:28,width:"fit-content",background:C.citrus,color:C.ink,borderRadius:"34px 34px 34px 8px",padding:vertical?"24px 34px":"19px 28px",fontFamily:display,fontSize:vertical?43:35,fontWeight:800,transform:`translateX(${(1-asmi)*-100}px)`,opacity:asmi}}>on it.</div></div><div style={{width:vertical?"100%":690}}><div style={{fontFamily:display,fontSize:vertical?63:72,fontWeight:800,lineHeight:.94}}>you ask once.<br/><span style={{color:C.citrus}}>she figures out the rest.</span></div><div style={{display:"flex",flexWrap:"wrap",gap:12,marginTop:40}}>{steps.map((x,i)=>{const s=appear(f,fps,35+i*7);return <React.Fragment key={x}><div style={{background:i===3?C.coral:C.cream,color:C.ink,border:`2px solid ${C.ink}`,padding:"13px 17px",fontFamily:mono,fontWeight:700,fontSize:vertical?19:17,transform:`scale(${.7+s*.3})`,opacity:s}}>{x}</div>{i<3&&<span style={{fontSize:28,opacity:s}}>→</span>}</React.Fragment>})}</div></div></div></AbsoluteFill>};

const PhoneSurface:React.FC<{vertical:boolean;status:string;second?:boolean}>=({vertical,status,second})=><div style={{width:vertical?760:560,height:vertical?550:470,background:C.ink,color:C.cream,borderRadius:vertical?66:48,border:`8px solid ${C.ink}`,boxShadow:`14px 16px 0 ${C.coral}`,padding:vertical?"42px 44px":"34px 38px",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"space-between"}}><div style={{width:130,height:25,borderRadius:20,background:"#302E35"}}/><div style={{textAlign:"center"}}><div style={{width:vertical?145:118,height:vertical?145:118,borderRadius:"50%",background:C.coral,display:"grid",placeItems:"center",fontFamily:display,fontSize:vertical?54:44,fontWeight:800,margin:"0 auto 22px"}}>BG</div><div style={{fontFamily:display,fontWeight:800,fontSize:vertical?48:40}}>bright gym</div><div style={{fontFamily:mono,fontSize:vertical?23:19,color:status.includes("voicemail")?C.coral:C.mint,marginTop:12}}>{second?"SECOND ATTEMPT · ":""}{status}</div></div><div style={{display:"flex",gap:34}}>{["mute","keypad","speaker"].map(x=><div key={x} style={{width:vertical?80:66,height:vertical?80:66,borderRadius:"50%",background:"#302E35",display:"grid",placeItems:"center",fontFamily:mono,fontSize:vertical?12:10}}>{x}</div>)}</div></div>;
const TextSurface:React.FC<{vertical:boolean}>=({vertical})=><div style={{width:vertical?790:650,background:C.cream,border:`4px solid ${C.ink}`,boxShadow:`13px 14px 0 ${C.blue}`,borderRadius:28,padding:vertical?38:30}}><div style={{fontFamily:mono,fontWeight:700,fontSize:vertical?20:16,borderBottom:`2px solid ${C.ink}`,paddingBottom:18}}>MESSAGES · BRIGHT GYM</div><div style={{marginTop:34,marginLeft:"auto",width:"83%",background:C.blue,color:C.cream,borderRadius:"24px 24px 7px 24px",padding:vertical?"24px 28px":"19px 24px",fontFamily:display,fontSize:vertical?31:25,fontWeight:600}}>confirming cancellation for membership #1842. effective today.</div><div style={{marginTop:24,width:"fit-content",background:"#E9E6E1",borderRadius:"24px 24px 24px 7px",padding:vertical?"21px 27px":"17px 22px",fontFamily:display,fontSize:vertical?29:23}}>please call member services.</div><div style={{fontFamily:mono,fontSize:vertical?18:14,color:C.coral,marginTop:24,textAlign:"right"}}>not useful. noted.</div></div>;
const MailSurface:React.FC<{vertical:boolean}>=({vertical})=><div style={{width:vertical?820:720,background:C.cream,border:`4px solid ${C.ink}`,boxShadow:`13px 14px 0 ${C.citrus}`,borderRadius:18,overflow:"hidden"}}><div style={{height:50,background:C.ink,display:"flex",alignItems:"center",gap:10,padding:"0 20px"}}>{[C.coral,C.citrus,C.mint].map(x=><i key={x} style={{width:13,height:13,borderRadius:"50%",background:x}}/>)}</div><div style={{padding:vertical?"35px 38px":"28px 32px",color:C.ink}}><div style={{fontFamily:mono,fontSize:vertical?19:15,lineHeight:2.1}}><b>TO</b> cancellations@brightgym.com<br/><b>SUBJECT</b> formal cancellation notice · #1842</div><div style={{height:2,background:C.ink,opacity:.15,margin:"20px 0"}}/><div style={{fontFamily:display,fontSize:vertical?31:24,lineHeight:1.28}}>Please accept this as formal notice to cancel the membership effective today. Written confirmation requested.</div><div style={{display:"flex",justifyContent:"space-between",marginTop:26,fontFamily:mono,fontWeight:700,fontSize:vertical?18:14,color:C.coral}}><span>SENT · 4:14 PM</span><span>✓ PAPER TRAIL</span></div></div></div>;

const Chase:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const phase=f<53?0:f<104?1:f<159?2:3;const local=[f,f-53,f-104,f-159][phase];const a=appear(local,fps,1);const status=phase===0?(local<28?"calling · 00:12":"voicemail · 00:41"):"calling · 00:18";return <AbsoluteFill style={{background:C.paper,overflow:"hidden"}}><Grid/><Grain/><ChaseLine progress={interpolate(f,[0,198],[0,1],clamp)} vertical={vertical}/><div style={{position:"absolute",top:vertical?80:48,left:vertical?55:100,fontFamily:display,fontWeight:800,fontSize:vertical?54:48}}>watch her chase them.</div><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",transform:`translateY(${(1-a)*80}px) scale(${.92+a*.08})`,opacity:a}}>{phase===0&&<PhoneSurface vertical={vertical} status={status}/>} {phase===1&&<TextSurface vertical={vertical}/>} {phase===2&&<MailSurface vertical={vertical}/>} {phase===3&&<PhoneSurface vertical={vertical} status={status} second/>}</div><div style={{position:"absolute",left:vertical?55:100,right:vertical?55:100,bottom:vertical?95:52,display:"flex",justifyContent:"space-between",alignItems:"end"}}><div style={{fontFamily:mono,fontWeight:700,fontSize:vertical?19:16,color:C.coral}}>{["CALL","TEXT","EMAIL","CALL AGAIN"][phase]}</div><div style={{fontFamily:display,fontWeight:800,fontSize:vertical?35:31,textAlign:"right",maxWidth:vertical?650:720,opacity:phase===3?appear(local,fps,15):0}}>they were hoping you’d forget. awkward.</div></div></AbsoluteFill>};

const languages=["English","Español","हिन्दी","中文","العربية","Français","Português","বাংলা","日本語","한국어","Deutsch","Türkçe","اردو","தமிழ்","Tiếng Việt","Italiano","Polski","ไทย","Bahasa","తెలుగు"];
const phrases=["cancelar la membresía","सदस्यता रद्द करें","取消会员资格","إلغاء العضوية","résilier l’abonnement","メンバーシップをキャンセル"];
const Language:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const gather=interpolate(f,[12,62],[0,1],clamp),lock=appear(f,fps,48);return <AbsoluteFill style={{background:C.ink,color:C.cream,overflow:"hidden"}}><Grain/>{languages.map((l,i)=>{const angle=i/languages.length*Math.PI*2+.35;const rX=vertical?430:790,rY=vertical?700:390;const x=Math.cos(angle)*rX*(1-gather*.45),y=Math.sin(angle)*rY*(1-gather*.45);const pulse=.86+.14*Math.sin(f/6+i);return <div key={l} style={{position:"absolute",left:"50%",top:"50%",fontFamily:display,fontWeight:700,fontSize:(vertical?30:27)+(i%4)*5,color:i%5===0?C.citrus:i%3===0?C.coral:C.cream,transform:`translate(calc(-50% + ${x}px),calc(-50% + ${y}px)) scale(${pulse})`,whiteSpace:"nowrap",opacity:interpolate(f,[i*1.2,i*1.2+10],[0,.85],clamp)}}>{l}</div>})}<div style={{position:"absolute",left:"50%",top:"50%",transform:`translate(-50%,-50%) scale(${.82+lock*.18})`,textAlign:"center",width:vertical?920:1200}}><div style={{fontFamily:mono,fontSize:vertical?26:21,color:C.mint,height:vertical?55:45}}>{phrases[Math.min(phrases.length-1,Math.floor(f/14))]}</div><div style={{fontFamily:display,fontWeight:800,fontSize:vertical?150:160,lineHeight:.8,opacity:lock}}>50+<br/><span style={{color:C.coral}}>languages.</span></div><div style={{fontFamily:display,fontWeight:700,fontSize:vertical?36:34,marginTop:vertical?50:35,opacity:lock}}>different language. same problem. still handled.</div></div></AbsoluteFill>};

const Payoff:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const slam=appear(f,fps,4);return <AbsoluteFill style={{background:C.mint,overflow:"hidden",padding:vertical?"150px 58px":"80px 120px"}}><Grid/><Grain/><div style={{height:"100%",display:"flex",flexDirection:vertical?"column":"row",alignItems:"center",justifyContent:"center",gap:vertical?80:150}}><div style={{fontFamily:display,fontWeight:800,fontSize:vertical?105:118,lineHeight:.82}}>done.<br/><span style={{color:C.coral}}>actually done.</span></div><div style={{width:vertical?"100%":700,background:C.cream,border:`5px solid ${C.ink}`,boxShadow:`16px 17px 0 ${C.ink}`,padding:vertical?"50px 48px":"42px 46px",transform:`rotate(-1.5deg) scale(${.82+slam*.18})`,opacity:slam}}><div style={{display:"flex",justifyContent:"space-between",fontFamily:mono,fontSize:vertical?20:17}}><span>BRIGHT GYM</span><span>4:22 PM</span></div><div style={{height:3,background:C.ink,margin:"30px 0"}}/><div style={{fontFamily:display,fontSize:vertical?82:76,fontWeight:800,lineHeight:.9}}>cancelled.</div><div style={{display:"flex",justifyContent:"space-between",gap:20,marginTop:32,fontFamily:display,fontSize:vertical?38:34,fontWeight:700}}><span>$0 next month.</span><span>no fee.</span></div><div style={{fontFamily:mono,fontWeight:700,fontSize:vertical?20:17,color:C.coral,marginTop:38}}>CONFIRMATION #BG-1842 ✓</div></div></div><div style={{position:"absolute",bottom:vertical?70:38,left:0,right:0,textAlign:"center",fontFamily:display,fontWeight:800,fontSize:vertical?35:31}}>turns out they do answer. eventually.</div></AbsoluteFill>};

const IMessage=()=> <div style={{width:54,height:54,borderRadius:16,background:C.blue,color:C.cream,display:"grid",placeItems:"center",fontSize:30}}>●</div>;
const WhatsApp=()=> <div style={{width:54,height:54,borderRadius:"50%",background:C.green,color:C.cream,display:"grid",placeItems:"center",fontSize:28}}>☎</div>;
const End:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const a=appear(f,fps,0),icons=appear(f,fps,11);return <AbsoluteFill style={{background:C.paper,display:"flex",alignItems:"center",justifyContent:"center",textAlign:"center",overflow:"hidden",padding:vertical?60:100}}><Grid/><Grain/><div style={{transform:`scale(${.75+a*.25})`,opacity:a}}><div style={{fontFamily:serif,fontStyle:"italic",fontSize:vertical?235:250,lineHeight:.75}}>asmi</div><div style={{height:13,width:vertical?510:600,background:C.coral,margin:"32px auto 35px",transform:`scaleX(${a})`,transformOrigin:"left"}}/><div style={{fontFamily:display,fontWeight:800,fontSize:vertical?57:60,lineHeight:.95}}>your annoying thing next.</div><div style={{display:"flex",justifyContent:"center",alignItems:"center",gap:18,marginTop:38,opacity:icons}}><span style={{fontFamily:mono,fontWeight:700,fontSize:vertical?22:19}}>TEXT ASMI</span><IMessage/><WhatsApp/></div></div></AbsoluteFill>};

export const HighlightVideo:React.FC<{vertical?:boolean}>=({vertical=false})=>{const frame=useCurrentFrame();const musicVolume=(f:number)=>interpolate(f,[0,10,TOTAL-20,TOTAL-1],[0,.7,.7,0],clamp);return <AbsoluteFill style={{fontFamily:display,background:C.paper}}><Sequence from={S.hook} durationInFrames={90}><Hook vertical={vertical}/></Sequence><Sequence from={S.ask} durationInFrames={90}><Ask vertical={vertical}/></Sequence><Sequence from={S.chase} durationInFrames={210}><Chase vertical={vertical}/></Sequence><Sequence from={S.language} durationInFrames={90}><Language vertical={vertical}/></Sequence><Sequence from={S.payoff} durationInFrames={75}><Payoff vertical={vertical}/></Sequence><Sequence from={S.end} durationInFrames={45}><End vertical={vertical}/></Sequence><Sequence from={S.ask+6} durationInFrames={24}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.75}/></Sequence><Sequence from={S.chase+54} durationInFrames={24}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.55}/></Sequence><Sequence from={S.chase+112} durationInFrames={24}><Audio src={staticFile("audio/sfx/wa-pop.mp3")} volume={.42}/></Sequence><Sequence from={S.payoff+4} durationInFrames={24}><Audio src={staticFile("audio/sfx/wa-pop.mp3")} volume={.8}/></Sequence><Sequence from={S.end+8} durationInFrames={22}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.65}/></Sequence><Audio src={staticFile("audio/bgm.mp3")} volume={musicVolume}/><div style={{position:"absolute",left:vertical?26:35,bottom:vertical?25:18,fontFamily:mono,fontSize:vertical?13:11,color:frame>=S.language&&frame<S.payoff?C.cream:C.ink,opacity:.38}}>ASMI / PERSONAL AI</div></AbsoluteFill>};
