import React from "react";
import {AbsoluteFill,Audio,Img,Sequence,interpolate,spring,staticFile,useCurrentFrame,useVideoConfig} from "remotion";
import {loadFont as loadDisplay} from "@remotion/google-fonts/BarlowCondensed";
import {loadFont as loadSerif} from "@remotion/google-fonts/InstrumentSerif";

const {fontFamily:display}=loadDisplay("normal",{weights:["500","600","700","800","900"],subsets:["latin"]});
const {fontFamily:serif}=loadSerif("normal",{weights:["400"],subsets:["latin"]});
const UI='-apple-system,BlinkMacSystemFont,"SF Pro Display","Helvetica Neue",Arial,sans-serif';
const C={ink:"#060607",paper:"#F6F2E9",red:"#FF453A",blue:"#0A84FF",blue2:"#007AFF",green:"#30D158",gold:"#F2B84B",grey:"#8E8E93",glass:"#111114",mail:"#F7F7F8"};
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
const E=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{...clamp,easing:t=>1-Math.pow(1-t,4)});
const O=(f:number,a:number,b:number)=>interpolate(f,[a,b],[1,0],clamp);
const S=(f:number,fps:number,d=0)=>spring({frame:f-d,fps,config:{damping:16,stiffness:220,mass:.72}});
const TOTAL=900;

const Texture=()=> <AbsoluteFill style={{opacity:.11,mixBlendMode:"screen",pointerEvents:"none",backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='190' height='190'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.75' numOctaves='2'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.15'/%3E%3C/svg%3E\")"}}/>;
const Stage=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:`radial-gradient(circle at ${45+Math.sin(f/67)*8}% ${40+Math.cos(f/53)*7}%,#292622 0%,#111012 36%,#050506 77%)`,overflow:"hidden"}}><div style={{position:"absolute",inset:"-20%",background:"repeating-linear-gradient(115deg,transparent 0 150px,rgba(242,184,75,.025) 151px 153px)",transform:`translateX(${Math.sin(f/50)*35}px) rotate(${Math.sin(f/90)*1.5}deg)`}}/><Texture/></AbsoluteFill>};
const enterExit=(f:number,d:number)=>({opacity:E(f,0,9)*O(f,d-10,d),transform:`scale(${.9+.1*E(f,0,13)+.1*(1-O(f,d-9,d))}) translateZ(0)`});

const Puck:React.FC<{x:number;y:number;color?:string;size?:number;glow?:number}>=({x,y,color=C.red,size=26,glow=36})=><div style={{position:"absolute",left:`${x}%`,top:`${y}%`,width:size,height:size,borderRadius:"50%",background:color,boxShadow:`0 0 ${glow}px ${color}`,transform:"translate(-50%,-50%)",zIndex:80}}/>;

const Signal=()=> <svg width="18" height="12" viewBox="0 0 19 12"><rect x="0" y="8" width="3" height="4" rx="1" fill="currentColor"/><rect x="5" y="6" width="3" height="6" rx="1" fill="currentColor"/><rect x="10" y="3" width="3" height="9" rx="1" fill="currentColor"/><rect x="15" width="3" height="12" rx="1" fill="currentColor"/></svg>;
const Wifi=()=> <svg width="17" height="13" viewBox="0 0 20 15" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"><path d="M1 4.5c5.7-4.5 12.3-4.5 18 0"/><path d="M4.3 8c3.7-2.8 7.7-2.8 11.4 0"/><path d="M8.2 11.3c1.2-.8 2.4-.8 3.6 0"/></svg>;
const Battery=()=> <svg width="26" height="13" viewBox="0 0 29 14"><rect x="1" y="1" width="24" height="12" rx="3" fill="none" stroke="currentColor" strokeWidth="1.4"/><rect x="3" y="3" width="18" height="8" rx="1.5" fill="currentColor"/><path d="M27 5v4" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>;
const Status:React.FC<{dark?:boolean}>=({dark})=><div style={{height:52,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 27px",fontFamily:UI,fontSize:15,fontWeight:700,color:dark?C.ink:C.paper,position:"relative",zIndex:15}}><span>9:41</span><span style={{display:"flex",gap:7,alignItems:"center"}}><Signal/><Wifi/><Battery/></span></div>;

const Device:React.FC<{vertical:boolean;children:React.ReactNode;light?:boolean;frame?:number;angle?:number}>=({vertical,children,light,frame=0,angle=0})=>{const w=vertical?718:444,h=vertical?1555:962;const float=Math.sin(frame/16)*(vertical?7:4);const yaw=angle+Math.sin(frame/31)*.32;return <div style={{position:"relative",width:w,height:h,transformStyle:"preserve-3d",transform:`translateY(${float}px) perspective(2200px) rotateY(${yaw}deg) rotateX(${Math.sin(frame/27)*.25}deg)`,filter:"drop-shadow(0 52px 70px rgba(0,0,0,.72))"}}><div style={{position:"absolute",inset:0,borderRadius:vertical?106:66,background:"linear-gradient(115deg,#D1CDC5 0%,#4E4E51 16%,#A5A39F 34%,#3C3D40 68%,#C5C0B8 100%)",boxShadow:"inset 0 0 0 1px rgba(255,255,255,.7),inset 0 0 0 5px #323235"}}/><div style={{position:"absolute",inset:vertical?11:7,borderRadius:vertical?96:60,overflow:"hidden",background:light?C.mail:"#000",boxShadow:"inset 0 0 0 3px #050506"}}>{children}<div style={{position:"absolute",top:vertical?18:11,left:"50%",transform:"translateX(-50%)",width:vertical?126:78,height:vertical?37:24,borderRadius:30,background:"#000",zIndex:20,boxShadow:"inset 0 -1px rgba(255,255,255,.11),0 0 0 1px rgba(255,255,255,.05)"}}/><div style={{position:"absolute",bottom:vertical?11:7,left:"50%",transform:"translateX(-50%)",width:vertical?126:78,height:vertical?5:3,borderRadius:5,background:light?C.ink:C.paper,opacity:.9,zIndex:20}}/></div><div style={{position:"absolute",left:vertical?-9:-6,top:"19%",width:vertical?9:6,height:"8%",background:"#66666A",borderRadius:"5px 0 0 5px"}}/><div style={{position:"absolute",left:vertical?-9:-6,top:"31%",width:vertical?9:6,height:"14%",background:"#66666A",borderRadius:"5px 0 0 5px"}}/><div style={{position:"absolute",right:vertical?-9:-6,top:"25%",width:vertical?9:6,height:"16%",background:"#66666A",borderRadius:"0 5px 5px 0"}}/><div style={{position:"absolute",inset:vertical?5:3,borderRadius:vertical?101:63,pointerEvents:"none",background:"linear-gradient(118deg,transparent 0 34%,rgba(255,255,255,.13) 38%,transparent 44% 100%)",transform:`translateX(${interpolate(frame,[0,90],[-35,45],clamp)}%)`}}/></div>};

const Hook:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const words=["the most irritating","assistant.","for them."];return <AbsoluteFill style={{color:C.paper,overflow:"hidden",...enterExit(f,66)}}>{words.map((w,i)=>{const a=S(f,fps,i*13),x=(i===1?1:-1)*(1-a)*(vertical?620:900);return <div key={w} style={{position:"absolute",left:vertical?66:140,top:(vertical?[560,690,885]:[250,355,500])[i],fontFamily:i===2?serif:display,fontStyle:i===2?"italic":"normal",fontWeight:i===1?800:600,fontSize:(vertical?[72,158,82]:[82,170,78])[i],lineHeight:.9,color:i===2?C.red:C.paper,transform:`translateX(${x}px) skewX(${(1-a)*-8}deg)`,opacity:a}}>{w}</div>})}<Puck x={vertical?82:77} y={vertical?47:55} size={24+E(f,48,62)*14}/><div style={{position:"absolute",left:0,right:0,top:`${interpolate(f,[48,65],[56,-8],clamp)}%`,height:4,background:C.gold,opacity:O(f,60,66),transform:"skewY(-5deg)"}}/></AbsoluteFill>};

const ChannelCard:React.FC<{vertical:boolean;kind:string;label:string;state:string;active:number}>=({vertical,kind,label,state,active})=>{const color=kind==="call"?C.green:kind==="text"?C.blue:C.blue2;return <div style={{width:vertical?620:650,height:vertical?330:250,borderRadius:vertical?54:42,background:kind==="mail"?C.mail:"linear-gradient(155deg,#252529,#0B0B0D)",color:kind==="mail"?C.ink:C.paper,border:`2px solid ${active>.5?color:"rgba(255,255,255,.15)"}`,boxShadow:`0 35px 100px rgba(0,0,0,.55),0 0 ${active*55}px ${color}44`,padding:vertical?44:34,fontFamily:UI,boxSizing:"border-box",position:"relative",overflow:"hidden"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{width:vertical?86:66,height:vertical?86:66,borderRadius:kind==="mail"?18:24,background:color,display:"grid",placeItems:"center",fontSize:vertical?44:34,color:"white"}}>{kind==="call"?"☎":kind==="text"?"●":"✉"}</div><div style={{fontSize:vertical?20:16,fontWeight:700,color}}>{state}</div></div><div style={{fontSize:vertical?54:44,fontWeight:700,marginTop:vertical?55:36}}>{label}</div><div style={{fontSize:vertical?25:19,color:kind==="mail"?"#68686D":C.grey,marginTop:10}}>Mission Gym · GX-88214</div></div>};
const Relay:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const travel=interpolate(f,[0,92],[0,3],clamp);const cardW=vertical?660:690;const labels=[["call","call","voicemail"],["text","text","sent"],["mail","email","sent"],["call","call again","connected"]];return <AbsoluteFill style={{overflow:"hidden",color:C.paper,...enterExit(f,102)}}><div style={{position:"absolute",inset:0,transform:`perspective(1300px) translateX(${-(travel%1)*cardW}px) rotateY(${Math.sin(f/13)*1.2}deg)`}}>{labels.map((x,i)=>{const pos=i-travel;const active=Math.max(0,1-Math.abs(pos));return <div key={i} style={{position:"absolute",left:`calc(50% + ${pos*cardW}px)`,top:vertical?640:330,transform:`translate(-50%,-50%) scale(${.72+.28*active}) rotate(${pos*4}deg)`,opacity:.18+.82*active}}><ChannelCard vertical={vertical} kind={x[0]} label={x[1]} state={x[2]} active={active}/></div>})}</div><div style={{position:"absolute",left:vertical?58:120,top:vertical?140:70,fontFamily:display,fontWeight:800,fontSize:vertical?66:68,lineHeight:.94}}>she tries<br/><span style={{color:C.gold}}>every way in.</span></div><div style={{position:"absolute",right:vertical?52:120,bottom:vertical?145:66,textAlign:"right",fontFamily:serif,fontStyle:"italic",fontSize:vertical?58:54}}>until it’s done.</div><Puck x={interpolate(f,[0,92],[18,82],clamp)} y={vertical?69:66} color={f>70?C.green:C.red} size={vertical?32:25}/></AbsoluteFill>};

const tasks=[
 ["BOARDING PASS","reschedule my flight",C.blue],["DENTIST","book a dentist",C.paper],["CLAIM #318","chase my insurance claim",C.gold],["RECEIPT","fight this charge",C.red],["SAT 7:30","book saturday dinner",C.green],["PLUMBER","get someone here today",C.paper],["PASSPORT","renew before december",C.blue],["VET","find the first slot",C.green]
];
const Avalanche:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig();const lock=E(f,66,84);return <AbsoluteFill style={{overflow:"hidden",color:C.paper,...enterExit(f,102)}}><div style={{position:"absolute",left:vertical?48:105,top:vertical?80:46,fontFamily:display,fontSize:vertical?49:46,fontWeight:700,zIndex:10}}>anything annoying.<br/><span style={{color:C.gold}}>thrown at her.</span></div>{tasks.map((t,i)=>{const a=S(f,fps,i*3),ang=(i/tasks.length)*Math.PI*2+f*.011;const rad=(vertical?500:640)+(i%2)*130;const x=50+Math.cos(ang)*rad/(vertical?10.8:19.2);const y=54+Math.sin(ang)*rad/(vertical?19.2:10.8);const z=(i%3)*.12;return <div key={t[1]} style={{position:"absolute",left:`${x}%`,top:`${y}%`,width:vertical?390:360,minHeight:vertical?150:120,padding:vertical?25:20,background:i%2?"#F4F0E8":"#17171A",color:i%2?C.ink:C.paper,borderRadius:i%3===0?8:20,boxShadow:"0 24px 70px rgba(0,0,0,.45)",transform:`translate(-50%,-50%) perspective(900px) rotate(${Math.sin(i*3)*8+f*.08*(i%2?1:-1)}deg) scale(${(.55+a*.45)*(1-lock*.35)+z})`,opacity:a*O(f,72,91),fontFamily:UI}}><div style={{fontSize:vertical?16:13,fontWeight:800,color:t[2],marginBottom:12}}>{t[0]}</div><div style={{fontSize:vertical?28:24,fontWeight:650,lineHeight:1.12}}>{t[1]}</div></div>})}<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",opacity:lock,transform:`scale(${.5+.5*lock}) rotate(${(1-lock)*-8}deg)`}}><div style={{width:vertical?900:1080,background:`linear-gradient(180deg,${C.blue},${C.blue2})`,borderRadius:vertical?38:30,padding:vertical?"34px 39px":"28px 34px",fontFamily:UI,fontSize:vertical?44:43,lineHeight:1.2,boxShadow:"0 0 0 9px rgba(10,132,255,.1),0 42px 100px rgba(10,132,255,.32)"}}>they won’t let me cancel my gym. i’ve tried twice.</div></div><Puck x={50} y={52} size={28} /></AbsoluteFill>};

const Bubble:React.FC<{vertical:boolean;mine?:boolean;text:string;delay:number;small?:boolean}>=({vertical,mine,text,delay,small})=>{const f=useCurrentFrame(),{fps}=useVideoConfig(),a=S(f,fps,delay);return <div style={{alignSelf:mine?"flex-end":"flex-start",maxWidth:"83%",padding:vertical?"17px 22px":"11px 15px",borderRadius:vertical?28:18,background:mine?`linear-gradient(${C.blue},${C.blue2})`:"#29292D",color:C.paper,fontFamily:UI,fontSize:vertical?(small?28:34):(small?18:22),lineHeight:1.23,opacity:a,transform:`translateY(${(1-a)*24}px) scale(${.94+.06*a})`,position:"relative"}}>{text}<span style={{position:"absolute",bottom:0,[mine?"right":"left"]:-5,width:14,height:16,background:mine?C.blue2:"#29292D",borderRadius:8}}/></div>};
const ChatHead:React.FC<{vertical:boolean;name?:string}>=({vertical,name="asmi"})=><><Status/><div style={{height:vertical?94:59,borderBottom:"1px solid #29292D",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:UI,color:C.paper}}><span style={{position:"absolute",left:vertical?24:15,color:C.blue,fontSize:vertical?38:26}}>‹</span><div style={{textAlign:"center"}}><div style={{width:vertical?45:29,height:vertical?45:29,borderRadius:"50%",background:name==="asmi"?"linear-gradient(145deg,#E66956,#B23F32)":"#5A5A60",display:"grid",placeItems:"center",fontSize:vertical?20:13,fontWeight:700,margin:"auto"}}>{name==="asmi"?"a":"MG"}</div><div style={{fontSize:vertical?15:10}}>{name} ›</div></div></div></>;
const Composer:React.FC<{vertical:boolean}>=({vertical})=><div style={{position:"absolute",left:vertical?24:15,right:vertical?24:15,bottom:vertical?26:16,height:vertical?58:37,border:"1px solid #4B4B50",borderRadius:40,color:C.grey,fontFamily:UI,fontSize:vertical?18:12,padding:vertical?"17px 19px":"10px 12px",boxSizing:"border-box"}}>iMessage</div>;

const Ask:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),a=E(f,0,18);return <AbsoluteFill style={{display:"grid",placeItems:"center",overflow:"hidden",...enterExit(f,72)}}><div style={{transform:`translateX(${(1-a)*(vertical?750:1050)}px) rotateY(${(1-a)*64}deg) rotateZ(${(1-a)*8}deg) scale(${vertical?.9:1.03})`}}><Device vertical={vertical} frame={f} angle={interpolate(a,[0,1],[24,0])}><AbsoluteFill style={{background:"#000",color:C.paper}}><ChatHead vertical={vertical}/><div style={{padding:vertical?"40px 28px":"25px 18px",display:"flex",flexDirection:"column",gap:vertical?21:13}}><Bubble vertical={vertical} mine delay={4} text="they won’t let me cancel my gym. i’ve tried twice."/><Bubble vertical={vertical} delay={17} text="send me your member ID."/><Bubble vertical={vertical} mine delay={30} text="GX-88214"/><Bubble vertical={vertical} delay={43} text="got it. don’t think about it again."/></div><Composer vertical={vertical}/></AbsoluteFill></Device></div><div style={{position:"absolute",left:vertical?48:76,bottom:vertical?56:36,fontFamily:display,fontSize:vertical?40:34,fontWeight:700,color:C.paper}}>one message. that’s it.</div></AbsoluteFill>};

const CallUI:React.FC<{vertical:boolean;phase:number;local:number}>=({vertical,phase,local})=><AbsoluteFill style={{background:"linear-gradient(180deg,#28282C,#09090B 72%)",color:C.paper,fontFamily:UI}}><Status/><div style={{textAlign:"center",paddingTop:vertical?130:76}}><div style={{fontSize:vertical?52:34,fontWeight:520}}>Mission Gym</div><div style={{fontSize:vertical?24:16,marginTop:12,color:phase===3?C.green:C.grey}}>{phase===3?"connected  00:18":local<30?"calling…":local<50?"on hold  06:04":"voicemail"}</div><div style={{width:vertical?160:104,height:vertical?160:104,borderRadius:"50%",background:"linear-gradient(145deg,#6D6D73,#343438)",display:"grid",placeItems:"center",margin:`${vertical?112:65}px auto ${vertical?135:76}px`,fontSize:vertical?46:30,fontWeight:650}}>MG</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:vertical?42:27,padding:`0 ${vertical?100:63}px`}}>{["mute","keypad","audio","add call","FaceTime","contacts"].map((x,i)=><div key={x} style={{display:"grid",gap:8,justifyItems:"center",fontSize:vertical?16:10}}><span style={{width:vertical?86:56,height:vertical?86:56,borderRadius:"50%",background:"rgba(255,255,255,.14)",display:"grid",placeItems:"center",fontSize:vertical?29:19}}>{i===1?"•••":i===4?"▰":"○"}</span>{x}</div>)}</div></div><div style={{position:"absolute",left:"50%",bottom:vertical?76:45,transform:"translateX(-50%)",width:vertical?96:62,height:vertical?96:62,borderRadius:"50%",background:C.red,display:"grid",placeItems:"center",fontSize:vertical?40:25}}>☎</div></AbsoluteFill>;
const TextUI:React.FC<{vertical:boolean}>=({vertical})=><AbsoluteFill style={{background:"#000",color:C.paper}}><ChatHead vertical={vertical} name="Mission Gym"/><div style={{fontFamily:UI,color:C.grey,textAlign:"center",fontSize:vertical?16:10,paddingTop:18}}>Today 9:47 AM</div><div style={{padding:vertical?"28px 26px":"18px 16px",display:"flex",flexDirection:"column",gap:vertical?20:13}}><Bubble vertical={vertical} mine delay={0} small text="Hi - confirming cancellation for membership GX-88214, effective today. Please send written confirmation."/><Bubble vertical={vertical} delay={10} small text="Cancellations have to be completed in person."/><Bubble vertical={vertical} mine delay={20} small text="Your agreement allows written notice. I’ve emailed it now."/></div><Composer vertical={vertical}/></AbsoluteFill>;
const MailUI:React.FC<{vertical:boolean}>=({vertical})=><AbsoluteFill style={{background:C.mail,color:C.ink,fontFamily:UI}}><Status dark/><div style={{height:vertical?75:48,display:"flex",justifyContent:"space-between",alignItems:"center",padding:vertical?"0 25px":"0 16px",borderBottom:"1px solid #D4D4D8",fontSize:vertical?24:15,color:C.blue}}><span>Cancel</span><b style={{color:C.ink}}>New Message</b><span>↑</span></div><div style={{fontSize:vertical?25:16}}>{[["To:","cancellations@missiongym.com"],["Subject:","Cancellation notice - GX-88214"]].map(x=><div key={x[0]} style={{display:"flex",gap:14,padding:vertical?"20px 24px":"13px 15px",borderBottom:"1px solid #D8D8DC"}}><span style={{color:C.grey}}>{x[0]}</span><span>{x[1]}</span></div>)}</div><div style={{padding:vertical?"30px 28px":"19px 18px",fontSize:vertical?27:17,lineHeight:1.42}}><p>Hello,</p><p>Please accept this as written notice to cancel membership GX-88214, effective today, under section 4.2 of the agreement.</p><p>Please confirm in writing and refund the final $59 charge.</p><p>Thank you.</p></div></AbsoluteFill>;

const Track:React.FC<{vertical:boolean;phase:number;progress:number}>=({vertical,phase,progress})=>{const labels=["call","text","email","call again"];return <div style={vertical?{position:"absolute",left:27,top:170,bottom:130,width:166,zIndex:50}:{position:"absolute",left:"50%",top:24,width:1160,transform:"translateX(-50%)",zIndex:50}}><div style={{display:"flex",flexDirection:vertical?"column":"row",alignItems:"center",justifyContent:"space-between",height:vertical?"100%":"auto",background:"rgba(7,7,8,.95)",border:"1px solid rgba(255,255,255,.18)",borderRadius:vertical?28:24,padding:vertical?"27px 15px":"16px 24px",boxShadow:"0 24px 70px rgba(0,0,0,.5)"}}>{labels.map((x,i)=><React.Fragment key={x}><div style={{display:"flex",flexDirection:vertical?"row":"column",alignItems:"center",gap:8,color:i<phase?C.green:i===phase?C.paper:C.grey,minWidth:vertical?130:130}}><span style={{width:vertical?44:38,height:vertical?44:38,borderRadius:"50%",border:`3px solid ${i<phase?C.green:i===phase?C.red:C.grey}`,background:i<phase?C.green:"#111",color:i<phase?C.ink:C.paper,display:"grid",placeItems:"center",fontFamily:UI,fontWeight:800,boxShadow:i===phase?`0 0 ${22+progress*18}px ${C.red}`:"none"}}>{i<phase?"✓":i+1}</span><div style={{fontFamily:UI,fontSize:vertical?17:14,fontWeight:750,whiteSpace:"nowrap"}}>{x}</div></div>{i<3&&<div style={vertical?{width:3,flex:1,background:i<phase?C.green:"#3D3D42",marginLeft:21}:{height:3,flex:1,background:i<phase?C.green:"#3D3D42",margin:"0 12px"}}/>}</React.Fragment>)}</div></div>};
const Chase:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const cuts=[0,60,120,180,246];const phase=f<60?0:f<120?1:f<180?2:3;const local=f-cuts[phase];const p=E(local,0,10)*O(local,(cuts[phase+1]-cuts[phase])-10,cuts[phase+1]-cuts[phase]);const angle=[-8,5,-5,7][phase];return <AbsoluteFill style={{overflow:"hidden",...enterExit(f,246)}}><Track vertical={vertical} phase={phase} progress={E(local,0,22)}/><div style={{position:"absolute",inset:0,display:"flex",justifyContent:vertical?"flex-end":"center",alignItems:"center",padding:vertical?"120px 28px 45px 205px":"105px 0 0",boxSizing:"border-box",opacity:p,transform:`translateX(${(1-E(local,0,10))*(phase%2?260:-260)}px) scale(${.96+.04*E(local,0,10)})`}}><Device vertical={vertical} frame={f} angle={angle}>{phase===0||phase===3?<CallUI vertical={vertical} phase={phase} local={local}/>:phase===1?<TextUI vertical={vertical}/>:<MailUI vertical={vertical}/>}</Device></div><div style={{position:"absolute",left:vertical?220:68,bottom:vertical?62:27,color:C.paper,fontFamily:display,fontSize:vertical?31:25,fontWeight:700,zIndex:52}}>{["first call - voicemail","text - they push back","email - agreement attached","second call - connected"][phase]}</div><div style={{position:"absolute",left:vertical?38:"50%",top:vertical?106:110,transform:vertical?"none":"translateX(-50%)",background:C.paper,color:C.ink,padding:"8px 14px",borderRadius:15,fontFamily:UI,fontWeight:800,fontSize:vertical?16:12,zIndex:55}}>GX-88214</div>{[51,111,171].map((at,i)=>{const q=E(f,at,at+10)*O(f,at+7,at+16);return <div key={at} style={{position:"absolute",left:"50%",top:"50%",width:vertical?1500:2200,height:vertical?1500:2200,borderRadius:"50%",border:`${vertical?19:13}px solid ${[C.red,C.blue,C.gold][i]}`,transform:`translate(-50%,-50%) scale(${q})`,opacity:q,zIndex:70}}/>})}</AbsoluteFill>};

const Proof:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),{fps}=useVideoConfig(),a=S(f,fps,2);return <AbsoluteFill style={{display:"grid",placeItems:"center",color:C.paper,overflow:"hidden",...enterExit(f,72)}}><div style={{width:vertical?900:1050,background:C.mail,color:C.ink,borderRadius:vertical?28:22,boxShadow:"0 45px 120px rgba(0,0,0,.72)",overflow:"hidden",transform:`translateY(${(1-a)*650}px) rotate(${(1-a)*8}deg) scale(${.72+a*.28})`}}><div style={{padding:vertical?"21px 28px":"16px 22px",background:"#E9E9EC",display:"flex",justifyContent:"space-between",fontFamily:UI,fontSize:vertical?22:17,color:C.grey}}><span>Mail</span><span>now</span></div><div style={{padding:vertical?"40px":"32px 36px",fontFamily:UI}}><div style={{fontSize:vertical?25:19,color:C.grey}}>Mission Gym Member Services</div><div style={{fontSize:vertical?48:42,fontWeight:750,marginTop:15}}>Your membership has been cancelled.</div><div style={{height:1,background:"#D1D1D5",margin:"27px 0"}}/><div style={{display:"flex",justifyContent:"space-between",fontSize:vertical?32:28,fontWeight:750}}><span style={{color:"#168A37"}}>$59 refunded</span><span>GX-88214</span></div></div></div><div style={{position:"absolute",bottom:vertical?82:48,fontFamily:serif,fontStyle:"italic",fontSize:vertical?57:52,opacity:E(f,22,35)}}>done. actually done.</div></AbsoluteFill>};

const translations=["Confirme la cancelación por escrito.","कृपया रद्दीकरण की पुष्टि करें।","请书面确认取消。","يرجى تأكيد الإلغاء كتابيًا.","Veuillez confirmer l’annulation.","解約を書面で確認してください。"];
const Language:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const lock=E(f,58,76);return <AbsoluteFill style={{overflow:"hidden",color:C.paper,...enterExit(f,87)}}>{translations.map((x,i)=>{const ang=(i/6)*Math.PI*2+f*.045;const rad=vertical?430:590;return <div key={x} style={{position:"absolute",left:`${50+Math.cos(ang)*rad/(vertical?10.8:19.2)}%`,top:`${50+Math.sin(ang)*rad/(vertical?19.2:10.8)}%`,width:vertical?650:720,background:`linear-gradient(${C.blue},${C.blue2})`,padding:vertical?"24px 28px":"19px 24px",borderRadius:28,fontFamily:UI,fontSize:vertical?30:27,textAlign:i===3?"right":"left",boxShadow:"0 20px 70px rgba(10,132,255,.25)",transform:`translate(-50%,-50%) perspective(900px) rotate(${Math.sin(i)*7}deg) scale(${O(f,58,76)})`,opacity:O(f,55,73)}}>{x}</div>})}<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",textAlign:"center",opacity:lock,transform:`scale(${.55+.45*lock}) rotate(${(1-lock)*-7}deg)`}}><div><div style={{fontFamily:display,fontWeight:900,fontSize:vertical?220:245,lineHeight:.72}}>50+</div><div style={{fontFamily:display,fontWeight:700,fontSize:vertical?88:88,color:C.gold}}>languages.</div><div style={{fontFamily:serif,fontStyle:"italic",fontSize:vertical?50:47,marginTop:26}}>same problem. still handled.</div></div></div></AbsoluteFill>};

const Confetti:React.FC<{vertical:boolean;mode:number}>=({vertical,mode})=>{const f=useCurrentFrame();return <>{Array.from({length:vertical?110:150}).map((_,i)=>{const col=i%(vertical?11:15),row=Math.floor(i/(vertical?11:15));const j=Math.sin(i*83.17)*.5+.5;const x=(col+.5)*(100/(vertical?11:15)),y=(row+.5)*(100/(vertical?10:10));const burst=E(f,i%12,24+i%12);return <div key={i} style={{position:"absolute",left:`${x}%`,top:`${y}%`,width:mode===0?(vertical?48:58):(vertical?28:32),height:mode===0?(vertical?30:32):(vertical?28:32),borderRadius:mode===0?4:"50%",background:i%9===0?C.red:i%7===0?C.gold:i%5===0?C.green:"rgba(246,242,233,.22)",transform:`translate(-50%,-50%) perspective(800px) rotate(${i*17+f*2}deg) scale(${(.2+.8*burst)*(mode?1:j+.4)})`,opacity:.22+.45*burst}}/>})}</>};
const Momentum:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const swap=E(f,77,92);const hit1=E(f,20,38)*O(f,70,85),hit2=E(f,88,107);return <AbsoluteFill style={{overflow:"hidden",color:C.paper,...enterExit(f,162)}}><div style={{opacity:1-swap,transform:`perspective(1000px) translateZ(${E(f,0,34)*100}px)`}}><Confetti vertical={vertical} mode={0}/></div><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",textAlign:"center",opacity:hit1,transform:`scale(${1.7-.7*E(f,20,38)})`}}><div><div style={{fontFamily:display,fontWeight:900,fontSize:vertical?258:300,lineHeight:.73,textShadow:"0 15px 60px rgba(0,0,0,.7)"}}>20,000</div><div style={{fontFamily:display,fontSize:vertical?52:49,fontWeight:700,marginTop:40}}>real-world tasks completed</div><div style={{fontFamily:UI,fontSize:vertical?22:18,fontWeight:850,color:C.gold,marginTop:13}}>IN THE PAST 30 DAYS</div></div></div><div style={{position:"absolute",inset:0,opacity:swap}}><Confetti vertical={vertical} mode={1}/><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",textAlign:"center",opacity:hit2,transform:`perspective(1000px) rotateY(${(1-hit2)*28}deg) scale(${1.75-.75*hit2})`}}><div><div style={{fontFamily:display,fontWeight:900,fontSize:vertical?330:370,lineHeight:.7}}>30M</div><div style={{fontFamily:display,fontSize:vertical?49:46,fontWeight:700,marginTop:45}}>people checked out asmi on socials</div><div style={{fontFamily:UI,fontSize:vertical?22:18,fontWeight:850,color:C.gold,marginTop:13}}>IN THE PAST 30 DAYS</div></div></div></div></AbsoluteFill>};

const End:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const logo=E(f,4,27),line=E(f,22,43),dest=E(f,42,59),sweep=interpolate(E(f,7,42),[0,1],[-40,140],clamp);return <AbsoluteFill style={{color:C.paper,overflow:"hidden"}}><div style={{position:"absolute",inset:0,background:`linear-gradient(112deg,transparent ${sweep-9}%,rgba(255,255,255,.18) ${sweep}%,transparent ${sweep+9}%)`}}/><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",textAlign:"center",padding:50}}><div style={{width:vertical?780:850,height:vertical?220:240,opacity:logo,transform:`perspective(900px) rotateY(${(1-logo)*50}deg) scale(${.62+.38*logo})`,filter:"drop-shadow(0 18px 45px rgba(255,255,255,.1))"}}><Img src={staticFile("brand/asmi-logo-white.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div style={{fontFamily:serif,fontStyle:"italic",fontSize:vertical?70:67,marginTop:vertical?42:32,opacity:line,transform:`translateY(${(1-line)*30}px)`}}>she doesn’t stop until it’s done.</div><div style={{display:"flex",alignItems:"center",gap:15,marginTop:vertical?55:38,opacity:dest,fontFamily:UI,fontSize:vertical?23:18,fontWeight:650}}><span>text asmi.</span><span style={{width:vertical?42:34,height:vertical?42:34,borderRadius:11,background:C.blue,display:"grid",placeItems:"center"}}>●</span><span style={{width:vertical?42:34,height:vertical?42:34,borderRadius:"50%",background:"#25D366",display:"grid",placeItems:"center"}}>☎</span></div></div><div style={{position:"absolute",left:"50%",bottom:vertical?70:40,width:E(f,10,47)*(vertical?320:390),height:3,background:C.red,transform:"translateX(-50%)"}}/></AbsoluteFill>};

export const HighlightVideo:React.FC<{vertical?:boolean}>=({vertical=false})=>{const f=useCurrentFrame();const puckX=interpolate(f,[0,66,156,246,540,675,825,900],[78,86,50,50,72,50,50,50],clamp);const puckY=interpolate(f,[0,66,156,246,540,675,825,900],[53,50,52,55,48,50,50,48],clamp);return <AbsoluteFill style={{background:C.ink}}><Stage/><Sequence from={0} durationInFrames={66}><Hook vertical={vertical}/></Sequence><Sequence from={54} durationInFrames={102}><Relay vertical={vertical}/></Sequence><Sequence from={144} durationInFrames={102}><Avalanche vertical={vertical}/></Sequence><Sequence from={234} durationInFrames={72}><Ask vertical={vertical}/></Sequence><Sequence from={294} durationInFrames={246}><Chase vertical={vertical}/></Sequence><Sequence from={528} durationInFrames={72}><Proof vertical={vertical}/></Sequence><Sequence from={588} durationInFrames={87}><Language vertical={vertical}/></Sequence><Sequence from={663} durationInFrames={162}><Momentum vertical={vertical}/></Sequence><Sequence from={813} durationInFrames={87}><End vertical={vertical}/></Sequence>{f<813&&<Puck x={puckX} y={puckY} size={f>540?18:24} glow={28}/>}<Sequence from={70} durationInFrames={18}><Audio src={staticFile("audio/sfx/wa-pop.mp3")} volume={.22}/></Sequence><Sequence from={248} durationInFrames={20}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.45}/></Sequence><Sequence from={525} durationInFrames={24}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.42}/></Sequence><Audio src={staticFile("audio/bgm-v7.wav")} volume={(x)=>interpolate(x,[0,7,TOTAL-12,TOTAL-1],[0,.92,.92,0],clamp)}/></AbsoluteFill>};
