import React from "react";
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {loadFont as loadBricolage} from "@remotion/google-fonts/BricolageGrotesque";
import {loadFont as loadMono} from "@remotion/google-fonts/NotoSansMono";

const {fontFamily:display}=loadBricolage("normal",{weights:["400","600","700","800"],subsets:["latin"]});
const {fontFamily:mono}=loadMono("normal",{weights:["400","600","700"],subsets:["latin"]});
const C={paper:"#F7F7F2",ink:"#111214",blue:"#1254FF",coral:"#FF4F3D",gold:"#E8CB78",green:"#35C98A",white:"#FFFFFF",soft:"#E9E9E2",muted:"#686A6D",night:"#111214"};
type V={vertical:boolean}; const clamp={extrapolateLeft:"clamp",extrapolateRight:"clamp"} as const;
const q=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],clamp);
const enter=(f:number,at:number,d=18)=>spring({frame:f-at,fps:30,config:{damping:20,stiffness:180},durationInFrames:d});
const exit=(f:number,at:number,d=12)=>1-q(f,at,at+d);
const sceneOpacity=(f:number,a:number,b:number,fade=10)=>q(f,a,a+fade)*exit(f,b-fade,fade);

const Grain=()=> <AbsoluteFill style={{pointerEvents:"none",opacity:.15,backgroundImage:"url(\"data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.14'/%3E%3C/svg%3E\")"}}/>;
const Progress=({frame,vertical}:{frame:number,vertical:boolean})=>{
 const steps=["request","choose","call","email","done"]; const active=frame<105?0:frame<195?1:frame<420?2:frame<540?3:4;
 return <div style={{position:"absolute",top:vertical?52:38,left:vertical?54:76,right:vertical?54:76,display:"flex",alignItems:"center",gap:10,zIndex:30}}>
  <div style={{fontFamily:display,fontSize:vertical?29:25,fontWeight:800}}>asmi</div><div style={{height:1,flex:1,background:C.soft}}/>
  {steps.map((s,i)=><div key={s} style={{display:"flex",alignItems:"center",gap:7,opacity:i<=active?1:.28}}><div style={{width:i===active?22:7,height:7,borderRadius:8,background:i<=active?C.blue:C.muted}}/><span style={{display:vertical&&i!==active?"none":"block",fontFamily:mono,fontSize:vertical?13:12,fontWeight:700,textTransform:"uppercase"}}>{s}</span></div>)}
 </div>;
};
const MessageBubble=({vertical,frame}:{vertical:boolean,frame:number})=>{
 const p=enter(frame,10,22); return <div style={{position:"absolute",right:vertical?48:130,top:vertical?290:230,width:vertical?790:720,background:C.blue,color:C.white,borderRadius:vertical?44:36,padding:vertical?"34px 38px":"28px 34px",fontFamily:"-apple-system, BlinkMacSystemFont, sans-serif",fontSize:vertical?38:32,lineHeight:1.22,boxShadow:"0 24px 60px rgba(18,84,255,.24)",transform:`translateY(${(1-p)*80}px) scale(${.93+.07*p})`,opacity:p}}>
  find a great wine shop in paris that can deliver four bottles to my colleagues tomorrow
  <div style={{position:"absolute",right:-8,bottom:3,width:28,height:32,background:C.blue,clipPath:"polygon(0 0,100% 100%,0 86%)"}}/>
 </div>;
};
const RequestScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=sceneOpacity(f,0,112);const words=["NEW YORK","→","PARIS","4 GIFTS","TOMORROW"];
 return <AbsoluteFill style={{opacity:op}}><div style={{position:"absolute",left:vertical?54:100,top:vertical?180:190,fontFamily:mono,fontSize:vertical?18:16,fontWeight:700,color:C.coral}}>ONE MESSAGE. REAL WORLD.</div><MessageBubble vertical={vertical} frame={f}/><div style={{position:"absolute",left:vertical?60:150,right:vertical?60:150,top:vertical?700:555,display:"flex",flexWrap:"wrap",gap:12}}>{words.map((w,i)=><span key={w} style={{padding:"10px 14px",background:i===1?C.coral:C.gold,fontFamily:mono,fontWeight:700,fontSize:vertical?19:16,transform:`translateY(${(1-enter(f,42+i*5))*30}px)`,opacity:enter(f,42+i*5)}}>{w}</span>)}</div><div style={{position:"absolute",left:vertical?60:150,top:vertical?920:750,fontFamily:display,fontSize:vertical?72:64,fontWeight:800,lineHeight:.98,maxWidth:vertical?900:1000}}>asmi turns the ask<br/>into a live task.</div></AbsoluteFill>;
};
const OptionCard=({name,sub,selected,frame,at,vertical}:{name:string,sub:string,selected?:boolean,frame:number,at:number,vertical:boolean})=>{const p=enter(frame,at,20); return <div style={{display:"flex",alignItems:"center",gap:18,padding:vertical?"24px 24px":"18px 22px",borderRadius:22,border:`2px solid ${selected?C.blue:C.soft}`,background:selected?"rgba(18,84,255,.06)":C.white,boxShadow:selected?"0 16px 40px rgba(18,84,255,.14)":"none",opacity:p,transform:`translateX(${(1-p)*110}px)`}}><div style={{width:vertical?66:54,height:vertical?66:54,borderRadius:18,background:selected?C.blue:C.gold,display:"grid",placeItems:"center",fontSize:vertical?30:25}}>🍷</div><div style={{flex:1}}><div style={{fontFamily:display,fontSize:vertical?31:27,fontWeight:750}}>{name}</div><div style={{fontFamily:mono,fontSize:vertical?15:13,color:C.muted,marginTop:4}}>{sub}</div></div><div style={{width:30,height:30,borderRadius:18,border:`2px solid ${selected?C.blue:C.muted}`,background:selected?C.blue:"transparent",color:C.white,display:"grid",placeItems:"center",fontWeight:800}}>{selected?"✓":""}</div></div>};
const ChoicesScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=sceneOpacity(f,96,204); const pick=enter(f,164,15);
 return <AbsoluteFill style={{opacity:op}}><div style={{position:"absolute",left:"50%",top:vertical?690:520,width:vertical?900:980,transform:`translate(-50%,-50%) scale(${.94+.06*enter(f,100,20)})`,background:"rgba(255,255,255,.78)",border:"1px solid #DFDFD7",borderRadius:28,padding:vertical?28:24,boxShadow:"0 40px 100px rgba(17,18,20,.12)"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",marginBottom:22}}><div><div style={{fontFamily:mono,fontSize:13,fontWeight:700,color:C.blue}}>PARIS WINE DELIVERY</div><div style={{fontFamily:display,fontSize:vertical?42:38,fontWeight:800,marginTop:7}}>found 3. tap the one you like.</div></div><div style={{padding:"8px 12px",background:C.soft,fontFamily:mono,fontSize:12}}>LOCAL NOW</div></div>
  <div style={{display:"grid",gap:12}}><OptionCard name="Legrand Filles et Fils" sub="2e · independent · delivery by request" frame={f} at={112} vertical={vertical}/><OptionCard name="Caves Bernard" sub="5e · family caviste · can deliver tomorrow" selected frame={f} at={123} vertical={vertical}/><OptionCard name="La Dernière Goutte" sub="6e · natural wines · phone orders" frame={f} at={134} vertical={vertical}/></div>
  <div style={{position:"absolute",right:vertical?62:100,top:vertical?313:250,width:74,height:74,borderRadius:50,border:`4px solid ${C.coral}`,transform:`scale(${pick})`,opacity:pick,boxShadow:`0 0 0 ${18*pick}px rgba(255,79,61,.14)`}}/>
 </div></AbsoluteFill>;
};
const GlobeScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=sceneOpacity(f,188,264,8);const p=q(f,194,252);const terms=[["great wine","grands vins"],["four colleagues","quatre collègues"],["Paris","Paris"],["tomorrow","demain"]];
 const W=vertical?1320:2100,H=vertical?900:1050;return <AbsoluteFill style={{opacity:op,background:C.night,color:C.white}}><svg width="100%" height="100%" viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="xMidYMid slice" style={{position:"absolute",inset:0}}><defs><pattern id="grid" width="80" height="80" patternUnits="userSpaceOnUse"><path d="M 80 0 L 0 0 0 80" fill="none" stroke="#FFFFFF" strokeOpacity=".10"/></pattern></defs><rect width={W} height={H} fill="url(#grid)"/><path d={vertical?"M 80 650 C 380 160, 870 120, 1250 590":"M 100 710 C 650 80, 1450 80, 2020 690"} fill="none" stroke={C.blue} strokeWidth="10" strokeDasharray="20 14" strokeDashoffset={(1-p)*1200}/><circle cx={vertical?80:100} cy={vertical?650:710} r="16" fill={C.coral}/><circle cx={vertical?1250:2020} cy={vertical?590:690} r="16" fill={C.gold}/></svg><div style={{position:"absolute",left:vertical?42:100,top:vertical?1190:750,fontFamily:mono,fontWeight:700,fontSize:vertical?19:16}}>NYC · ENGLISH</div><div style={{position:"absolute",right:vertical?42:100,top:vertical?1190:750,fontFamily:mono,fontWeight:700,fontSize:vertical?19:16}}>PARIS · FRANÇAIS</div>{terms.map(([en,fr],i)=>{const local=q(p,i*.1,.48+i*.1);const x=interpolate(local,[0,1],[vertical?60:120,vertical?700:1160]);const y=(vertical?420:330)+i*(vertical?165:125)+Math.sin(local*Math.PI)*-130;return <div key={en} style={{position:"absolute",left:x,top:y,padding:"12px 18px",background:local>.5?C.gold:C.white,color:C.ink,fontFamily:display,fontSize:vertical?31:26,fontWeight:800,transform:`scale(${.88+.12*Math.sin(local*Math.PI)})`,boxShadow:"0 18px 50px rgba(0,0,0,.28)"}}>{local>.52?fr:en}</div>})}</AbsoluteFill>;
};
const Wave=({frame,vertical}:{frame:number,vertical:boolean})=><div style={{height:vertical?78:58,display:"flex",gap:vertical?8:6,alignItems:"center",justifyContent:"center"}}>{Array.from({length:34},(_,i)=>{const h=10+Math.abs(Math.sin(i*.8+frame*.18))*((frame>294&&frame<405)?55:12);return <div key={i} style={{width:vertical?7:5,height:h,borderRadius:9,background:i%4===0?C.coral:C.blue}}/>})}</div>;
const CallScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=sceneOpacity(f,250,418,8);const status=f<282?"DIALING":f<302?"RINGING":f<402?"CONNECTED":"WRAPPING"; const statusColor=f<302?C.gold:f<402?C.green:C.blue;
 return <AbsoluteFill style={{opacity:op}}><div style={{position:"absolute",left:"50%",top:vertical?820:555,width:vertical?900:1120,transform:"translate(-50%,-50%)",background:C.white,border:"1px solid #D9D9D2",borderRadius:30,boxShadow:"0 40px 120px rgba(17,18,20,.13)",padding:vertical?34:30}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontFamily:mono,fontSize:13,color:C.muted,fontWeight:700}}>LIVE TASK · CAVES BERNARD</div><div style={{fontFamily:display,fontSize:vertical?48:43,fontWeight:800,marginTop:8}}>wine delivery for four</div></div><div style={{padding:"10px 14px",background:statusColor,fontFamily:mono,fontWeight:800,fontSize:vertical?15:13,color:statusColor===C.gold?C.ink:C.white}}>{status}</div></div>
  <div style={{marginTop:vertical?42:30,padding:vertical?"28px 24px":"22px 24px",background:C.paper,borderRadius:22}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18,fontFamily:mono,fontSize:vertical?16:14,lineHeight:1.55}}><div><b>merchant</b><br/>Caves Bernard · Paris 5e</div><div><b>brief</b><br/>4 bottles · deliver tomorrow</div></div></div>
  <div style={{marginTop:vertical?45:30}}><Wave frame={f} vertical={vertical}/></div>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:20}}><span style={{fontFamily:mono,fontSize:vertical?15:13,color:C.muted}}>live transcript stays private</span><span style={{fontFamily:mono,fontSize:vertical?15:13,fontWeight:800}}>FR · 00:{Math.max(0,Math.floor((f-302)/30)).toString().padStart(2,"0")}</span></div>
 </div><div style={{position:"absolute",left:vertical?70:150,top:vertical?1320:880,fontFamily:display,fontSize:vertical?64:54,fontWeight:800,lineHeight:1}}>she speaks to the shop.<br/><span style={{color:C.blue}}>you just see progress.</span></div></AbsoluteFill>;
};
const EmailScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=sceneOpacity(f,414,552,10);const line=q(f,434,510);return <AbsoluteFill style={{opacity:op}}><div style={{position:"absolute",left:"50%",top:vertical?780:540,width:vertical?900:1040,transform:"translate(-50%,-50%)",background:C.white,border:"1px solid #D9D9D2",borderRadius:28,padding:vertical?34:30,boxShadow:"0 38px 110px rgba(17,18,20,.12)"}}><div style={{display:"flex",alignItems:"center",gap:16}}><div style={{width:58,height:58,borderRadius:18,background:C.coral,color:C.white,display:"grid",placeItems:"center",fontFamily:display,fontSize:30,fontWeight:800}}>@</div><div><div style={{fontFamily:display,fontSize:vertical?37:34,fontWeight:800}}>order details sent in French</div><div style={{fontFamily:mono,fontSize:vertical?14:13,color:C.muted,marginTop:4}}>EMAIL ARTIFACT · 10:48 AM</div></div></div><div style={{height:2,background:C.soft,margin:"28px 0"}}/><div style={{fontFamily:mono,fontSize:vertical?17:15,lineHeight:1.65}}><b>À :</b> commandes@cavesbernard.fr<br/><b>Objet :</b> Confirmation de livraison — demain<br/><br/>Bonjour,<br/>Voici les quatre adresses de livraison et les coordonnées des destinataires…</div><div style={{marginTop:28,height:9,width:`${line*100}%`,background:C.blue}}/><div style={{marginTop:20,display:"flex",justifyContent:"space-between",fontFamily:mono,fontSize:vertical?14:12,color:C.muted}}><span>saved to task</span><b style={{color:C.green}}>SENT ✓</b></div></div><div style={{position:"absolute",left:vertical?70:160,top:vertical?1310:870,fontFamily:display,fontWeight:800,fontSize:vertical?68:56}}>then follows up<br/><span style={{color:C.coral}}>with every detail.</span></div></AbsoluteFill>};
const ResultScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=sceneOpacity(f,536,644,8);const p=enter(f,548,24);return <AbsoluteFill style={{opacity:op,background:C.green}}><div style={{position:"absolute",left:"50%",top:"50%",width:vertical?880:1100,transform:`translate(-50%,-50%) scale(${.7+.3*p}) rotate(${(1-p)*-4}deg)`,background:C.paper,border:`4px solid ${C.ink}`,boxShadow:`${vertical?22:18}px ${vertical?22:18}px 0 ${C.ink}`,padding:vertical?"46px 40px":"40px 46px"}}><div style={{fontFamily:mono,fontSize:vertical?16:14,fontWeight:800}}>TASK COMPLETE · PARIS</div><div style={{fontFamily:display,fontSize:vertical?72:65,fontWeight:800,lineHeight:.95,marginTop:24}}>four bottles.<br/>four colleagues.<br/>tomorrow.</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginTop:38,fontFamily:mono,fontSize:vertical?16:14}}>{["merchant confirmed","email sent","addresses verified","delivery 2–5 PM"].map((x,i)=><div key={x} style={{padding:"16px 14px",background:i===3?C.gold:C.white,border:`1px solid ${C.ink}`}}>✓ {x}</div>)}</div></div></AbsoluteFill>};
const languages=["français","español","हिन्दी","العربية","português","日本語","Deutsch","한국어","italiano","ਪੰਜਾਬੀ","বাংলা","Türkçe","中文","தமிழ்","Nederlands","polski"];
const LanguageScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=sceneOpacity(f,640,738,8);const p=q(f,652,716);return <AbsoluteFill style={{opacity:op,background:C.night,color:C.white,overflow:"hidden"}}><div style={{position:"absolute",inset:0,transform:`rotate(-6deg) scale(1.18) translateX(${interpolate(p,[0,1],[130,-180])}px)`}}>{languages.map((l,i)=><div key={l} style={{position:"absolute",left:(i%4)*(vertical?300:540)-80,top:Math.floor(i/4)*(vertical?310:235)+120,padding:vertical?"17px 25px":"14px 22px",background:[C.blue,C.coral,C.gold,C.green][i%4],color:i%4===2?C.ink:C.white,fontFamily:display,fontSize:vertical?40:35,fontWeight:800,transform:`translateY(${Math.sin(i*1.7+p*7)*26}px)`}}>{l}</div>)}</div><div style={{position:"absolute",left:vertical?55:105,bottom:vertical?270:145}}><div style={{fontFamily:display,fontSize:vertical?190:170,fontWeight:800,lineHeight:.75,letterSpacing:0}}>50+</div><div style={{fontFamily:display,fontSize:vertical?60:52,fontWeight:800,marginTop:32}}>languages.</div><div style={{fontFamily:mono,fontSize:vertical?21:18,fontWeight:700,marginTop:18,color:C.gold}}>TALKS · TEXTS · EMAILS</div></div></AbsoluteFill>};
const MessagesIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><rect width="64" height="64" rx="15" fill="#34C759"/><path d="M13 31c0-10 8.5-18 19-18s19 8 19 18-8.5 18-19 18c-3.1 0-6-.7-8.5-1.9L14 51l2.8-8C14.4 39.9 13 35.6 13 31z" fill="white"/></svg>;
const WhatsAppIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><rect width="64" height="64" rx="15" fill="#25D366"/><path fill="white" d="M32 12c-10.8 0-19.5 8.5-19.5 19 0 3.4.9 6.7 2.7 9.5L12 52l11.9-3.1A19.8 19.8 0 0032 50c10.8 0 19.5-8.5 19.5-19S42.8 12 32 12zm0 34.6c-2.7 0-5.4-.7-7.7-2l-.6-.3-7.1 1.9 1.9-6.7-.4-.7a15.2 15.2 0 01-2.3-7.9c0-8.6 7.2-15.6 16.1-15.6s16.1 7 16.1 15.6S40.9 46.6 32 46.6z"/><path fill="white" d="M41 35.2c-.5-.2-3-1.4-3.4-1.6-.5-.2-.8-.2-1.1.3-.3.5-1.3 1.6-1.6 2-.3.3-.6.4-1.1.1-3-1.4-5-2.5-7-5.7-.5-.9.5-.8 1.5-2.7.2-.3.1-.6 0-.8l-1.5-3.6c-.4-.9-.8-.8-1.1-.8h-1c-.3 0-.9.1-1.4.6-.5.5-1.8 1.7-1.8 4.2s1.9 4.9 2.1 5.2c.2.3 3.7 5.5 9 7.7 3.3 1.4 4.6 1.5 6.3 1.3 1-.2 3-1.2 3.4-2.4.4-1.2.4-2.2.3-2.4-.1-.2-.5-.3-1-.5z"/></svg>;
const EndScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=q(f,734,742);const p=enter(f,741,28);return <AbsoluteFill style={{opacity:op}}><div style={{position:"absolute",left:"50%",top:vertical?680:315,width:vertical?820:920,height:vertical?270:270,transform:`translate(-50%,-50%) scale(${.7+.3*p})`,filter:"invert(1)"}}><Img src={staticFile("brand/asmi-logo-white.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div style={{position:"absolute",left:0,right:0,top:vertical?950:575,textAlign:"center",fontFamily:display,fontSize:vertical?65:58,fontWeight:800}}>the real world.<br/><span style={{color:C.blue}}>in its own language.</span></div><div style={{position:"absolute",left:0,right:0,top:vertical?1180:760,display:"flex",alignItems:"center",justifyContent:"center",gap:20,fontFamily:mono,fontSize:vertical?24:20,fontWeight:800}}><span>text asmi.</span><MessagesIcon size={vertical?62:52}/><WhatsAppIcon size={vertical?62:52}/></div><div style={{position:"absolute",left:"50%",top:vertical?1340:865,width:q(f,770,802)*(vertical?760:980),height:18,background:C.coral,transform:"translateX(-50%) rotate(-1deg)"}}/></AbsoluteFill>};

export const WineFranceFilmV3:React.FC<V>=({vertical})=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:C.paper,color:C.ink,overflow:"hidden"}}><Grain/><Progress frame={f} vertical={vertical}/><RequestScene vertical={vertical}/><ChoicesScene vertical={vertical}/><GlobeScene vertical={vertical}/><CallScene vertical={vertical}/><EmailScene vertical={vertical}/><ResultScene vertical={vertical}/><LanguageScene vertical={vertical}/><EndScene vertical={vertical}/><Audio src={staticFile("audio/wine-france-v3/score.wav")} volume={(af)=>interpolate(af,[0,15,260,278,420,438,650,700,790,809],[0,.9,.9,.36,.36,.86,.92,1,.72,0],clamp)}/><Sequence from={273} durationInFrames={28} premountFor={30}><Audio src={staticFile("audio/wine-france-v3/pickup-short.mp3")} volume={1.05}/></Sequence><Sequence from={301} durationInFrames={80} premountFor={30}><Audio src={staticFile("audio/wine-france-v3/asmi-short.mp3")} volume={1.08}/></Sequence><Sequence from={381} durationInFrames={58} premountFor={30}><Audio src={staticFile("audio/wine-france-v3/confirm-short.mp3")} volume={1.08}/></Sequence></AbsoluteFill>};
