import React from "react";
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame} from "remotion";
import {loadFont as loadDisplay} from "@remotion/google-fonts/BricolageGrotesque";

const {fontFamily:display}=loadDisplay("normal",{weights:["500","600","700","800"],subsets:["latin"]});
const ui='-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",Arial,sans-serif';
const mono='"Noto Sans Mono","SFMono-Regular",monospace';
const P={night:"#111A2E",cobalt:"#2D58FF",burgundy:"#6D1834",wine:"#A72C49",champagne:"#F1D58A",ivory:"#F8F3E9",ink:"#17161A",acid:"#C9F25F",steel:"#AEB9D0",white:"#FFFDFC",green:"#36C88A"};
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
const q=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],clamp);
const win=(f:number,a:number,b:number,c:number,d:number)=>q(f,a,b)*(1-q(f,c,d));
const pop=(f:number,at:number)=>spring({frame:f-at,fps:30,config:{damping:18,stiffness:260,mass:.75}});
type V={vertical:boolean};

const Grain=()=> <AbsoluteFill style={{opacity:.1,mixBlendMode:"multiply",backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.84' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.35'/%3E%3C/svg%3E\")"}}/>;
const Label:React.FC<{children:React.ReactNode;size:number;color?:string;style?:React.CSSProperties}>=({children,size,color=P.ivory,style})=><div style={{fontFamily:display,fontWeight:800,fontSize:size,lineHeight:.92,letterSpacing:0,color,...style}}>{children}</div>;

const Status:React.FC<{s:number;dark?:boolean;time?:string}>=({s,dark=false,time="6:42"})=><div style={{height:54*s,padding:`0 ${28*s}px`,display:"flex",alignItems:"center",justifyContent:"space-between",fontFamily:ui,fontWeight:700,fontSize:15*s,color:dark?P.ink:P.white,position:"relative",zIndex:5}}><span>{time}</span><span style={{display:"flex",gap:8*s}}><b>▮▮▮</b><b>◒</b><span style={{border:"1px solid currentColor",borderRadius:4*s,padding:`0 ${4*s}px`}}>87</span></span></div>;
const Bubble:React.FC<{s:number;mine?:boolean;children:React.ReactNode}>=({s,mine,children})=><div style={{maxWidth:"87%",alignSelf:mine?"flex-end":"flex-start",background:mine?P.cobalt:"#2A2C32",color:P.white,borderRadius:25*s,padding:`${14*s}px ${19*s}px`,fontFamily:ui,fontSize:24*s,lineHeight:1.25,boxShadow:"0 10px 28px rgba(0,0,0,.2)"}}>{children}</div>;
const Phone:React.FC<{vertical:boolean;children:React.ReactNode;frame:number;scale?:number}>=({vertical,children,frame,scale=1})=>{const w=vertical?650:430,h=vertical?1407:930,r=vertical?98:65;return <div style={{width:w,height:h,position:"relative",transform:`perspective(1800px) rotateY(${Math.sin(frame/37)*2.2}deg) rotateZ(${Math.sin(frame/31)*.3}deg) scale(${scale})`,filter:"drop-shadow(0 48px 48px rgba(0,0,0,.35))"}}><div style={{position:"absolute",inset:-9,borderRadius:r+9,background:"linear-gradient(110deg,#191A20,#D9D8D5 12%,#4A4B50 27%,#111216 58%,#E5E1D8 84%,#24252A)",boxShadow:"inset 0 0 0 2px rgba(255,255,255,.75),inset 0 0 0 8px #111216"}}/><div style={{position:"absolute",inset:6,borderRadius:r-4,overflow:"hidden",background:"#050609"}}>{children}<div style={{position:"absolute",top:vertical?18:12,left:"50%",transform:"translateX(-50%)",width:vertical?124:82,height:vertical?36:24,borderRadius:28,background:"#050609",zIndex:20}}/></div></div>};

const MapLine:React.FC<V&{progress:number}>=({vertical,progress})=><svg viewBox={vertical?"0 0 1080 1920":"0 0 1920 1080"} style={{position:"absolute",inset:0,width:"100%",height:"100%"}}><path d={vertical?"M130 1320 C 840 1260 250 660 870 510":"M230 760 C 690 250 1200 840 1690 330"} fill="none" stroke={P.champagne} strokeWidth={vertical?13:10} strokeLinecap="round" strokeDasharray="2200" strokeDashoffset={2200-progress*2200}/><circle cx={vertical?130:230} cy={vertical?1320:760} r={vertical?18:15} fill={P.cobalt}/><circle cx={vertical?870:1690} cy={vertical?510:330} r={vertical?18:15} fill={P.wine}/></svg>;

const Ask:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const p=pop(f,10),route=q(f,76,140);const s=vertical?1:.66;return <AbsoluteFill style={{opacity:win(f,0,8,150,164),background:`linear-gradient(145deg,${P.night},#21365E)`,overflow:"hidden"}}><Grain/><div style={{position:"absolute",left:vertical?55:88,top:vertical?85:70,fontFamily:mono,fontSize:vertical?21:18,color:P.steel}}>NEW YORK · 6:42 PM</div><div style={{position:"absolute",right:vertical?55:88,top:vertical?85:70,fontFamily:mono,fontSize:vertical?21:18,color:P.champagne}}>PARIS · 12:42 AM</div><MapLine vertical={vertical} progress={route}/><div style={{position:"absolute",left:vertical?"50%":"28%",top:vertical?"52%":"52%",transform:`translate(-50%,-50%) translateY(${(1-p)*80}px)`,opacity:p}}><Phone vertical={vertical} frame={f} scale={vertical ? .78 : .93}><Status s={s}/><div style={{height:82*s,borderBottom:"1px solid #2C2E34",display:"grid",placeItems:"center",fontFamily:ui,color:P.white,fontWeight:700,fontSize:17*s}}>asmi</div><div style={{padding:`${34*s}px ${24*s}px`,display:"flex",flexDirection:"column",gap:15*s}}><Bubble s={s} mine>need great wine delivered to 4 colleagues in paris tomorrow.</Bubble><Bubble s={s} mine>somewhere local — not a generic gift site.</Bubble><div style={{opacity:q(f,72,90)}}><Bubble s={s}>on it.</Bubble></div></div></Phone></div>{[0,1,2,3].map(i=>{const x=vertical?[760,890,735,930][i]:[1490,1710,1550,1770][i],y=vertical?[400,540,670,790][i]:[255,385,540,670][i],a=pop(f,92+i*7);return <div key={i} style={{position:"absolute",left:x,top:y,width:vertical?76:62,height:vertical?76:62,borderRadius:"50% 50% 50% 8px",background:i%2?P.champagne:P.ivory,border:`4px solid ${P.burgundy}`,display:"grid",placeItems:"center",fontFamily:mono,fontWeight:800,fontSize:vertical?26:21,color:P.burgundy,transform:`rotate(-45deg) scale(${a})`}}><span style={{transform:"rotate(45deg)"}}>{i+1}</span></div>})}</AbsoluteFill>};

const Search:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=win(f,145,158,248,260);const rows=["national gift marketplace","same-day wine app","generic hamper store","CAVES BERNARD · PARIS 11e"];return <AbsoluteFill style={{opacity:a,background:P.ivory,overflow:"hidden"}}><Grain/><div style={{position:"absolute",left:vertical?58:110,top:vertical?170:110,width:vertical?900:930}}><div style={{fontFamily:mono,fontSize:vertical?22:19,color:P.burgundy,marginBottom:25}}>SEARCHING PARIS · LOCAL DELIVERY · HUMAN ADVICE</div><Label size={vertical?90:96} color={P.ink}>not a checkout.<br/>a conversation.</Label><div style={{marginTop:vertical?90:55,display:"grid",gap:vertical?25:16}}>{rows.map((r,i)=>{const x=pop(f,160+i*14);const chosen=i===3;return <div key={r} style={{height:vertical?145:105,display:"flex",alignItems:"center",justifyContent:"space-between",padding:vertical?"0 28px":"0 30px",borderBottom:`${vertical?5:4}px solid ${chosen?P.burgundy:P.ink}`,fontFamily:display,fontSize:vertical?43:39,fontWeight:700,color:chosen?P.ivory:P.ink,background:chosen?P.burgundy:"transparent",opacity:x,transform:`translateX(${(1-x)*(i%2?-180:180)}px)`}}><span>{r}</span><span style={{fontFamily:mono,fontSize:vertical?18:15}}>{chosen?"CALL TO ARRANGE":"ONLINE CART"}</span></div>})}</div></div><div style={{position:"absolute",right:vertical?-170:95,bottom:vertical?90:75,width:vertical?500:410,height:vertical?780:600,background:P.champagne,clipPath:"polygon(42% 0,67% 0,69% 28%,83% 44%,80% 100%,22% 100%,18% 44%,39% 28%)",transform:`rotate(8deg) translateY(${(1-pop(f,205))*400}px)`,boxShadow:"0 35px 45px rgba(56,23,30,.25)"}}/></AbsoluteFill>};

const Wave:React.FC<{f:number;vertical:boolean}>=({f,vertical})=><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:vertical?8:6,height:vertical?120:76}}>{Array.from({length:38},(_,i)=>{const h=(.2+.8*Math.abs(Math.sin(i*1.37+f*.28)))*(vertical?92:58);return <span key={i} style={{width:vertical?7:5,height:h,background:i%7===0?P.acid:P.white,borderRadius:8}}/>})}</div>;
const Subtitle:React.FC<{vertical:boolean;fr:string;en:string;show:number}>=({vertical,fr,en,show})=><div style={{position:"absolute",left:"50%",bottom:vertical?165:72,width:vertical?930:1250,transform:`translate(-50%,${(1-show)*35}px)`,opacity:show,textAlign:"center"}}><div style={{display:"inline",background:P.ivory,color:P.ink,fontFamily:ui,fontWeight:700,fontSize:vertical?34:29,lineHeight:1.35,padding:"5px 12px",boxDecorationBreak:"clone"}}>{fr}</div><div style={{fontFamily:mono,color:P.champagne,fontSize:vertical?21:18,marginTop:16}}>{en}</div></div>;
const Call:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=win(f,240,252,580,596);const local=f-240;const second=local>205;const s=vertical?1:.66;const phone=pop(f,244);return <AbsoluteFill style={{opacity:a,background:`radial-gradient(circle at 68% 30%,#8C2B49 0%,${P.burgundy} 31%,#25111B 72%)`,overflow:"hidden"}}><Grain/><div style={{position:"absolute",left:vertical?45:85,top:vertical?85:70,fontFamily:mono,fontSize:vertical?20:17,color:P.champagne}}>PARIS · LIVE CALL · FRENCH</div><div style={{position:"absolute",left:vertical?"50%":"72%",top:vertical?"58%":"48%",transform:`translate(-50%,-50%) scale(${.72+.28*phone})`}}><Phone vertical={vertical} frame={f} scale={vertical ? .62 : .9}><Status s={s} time="12:49"/><div style={{fontFamily:ui,color:P.white,textAlign:"center",paddingTop:90*s}}><div style={{fontSize:42*s,fontWeight:700}}>Caves Bernard</div><div style={{fontSize:19*s,color:P.green,marginTop:10*s}}>connected · 00:{String(Math.max(1,Math.floor(local/30))).padStart(2,"0")}</div><div style={{width:150*s,height:150*s,borderRadius:"50%",margin:`${62*s}px auto ${35*s}px`,background:P.champagne,color:P.burgundy,display:"grid",placeItems:"center",fontFamily:display,fontSize:51*s,fontWeight:800}}>CB</div><Wave f={f} vertical={vertical}/><div style={{marginTop:28*s,fontFamily:mono,fontSize:15*s,color:P.steel}}>ASMI ↔ CAVISTE</div></div></Phone></div><div style={{position:"absolute",left:vertical?50:90,top:vertical?220:250,width:vertical?900:720}}><Label size={vertical?82:100} color={P.ivory}>asmi calls.<br/><span style={{color:P.champagne}}>in french.</span></Label><div style={{marginTop:35,fontFamily:mono,fontSize:vertical?20:19,color:P.steel}}>4 BOTTLES · 4 COLLEAGUES · TOMORROW</div></div>{!second?<Subtitle vertical={vertical} show={q(local,12,22)} fr="Bonjour. Je cherche quatre belles bouteilles à livrer demain à Paris, pour quatre collègues." en="Hi. I’m looking for four great bottles, delivered tomorrow in Paris, for four colleagues."/>:<Subtitle vertical={vertical} show={q(local,210,220)} fr="Bien sûr. Quatre cuvées de petits producteurs. Livraison demain après-midi." en="Of course. Four small-producer wines. Delivery tomorrow afternoon."/>}</AbsoluteFill>};

const Mail:React.FC<{s:number}>=({s})=><AbsoluteFill style={{background:"#F8F8FA",color:P.ink,fontFamily:ui}}><Status s={s} dark time="12:53"/><div style={{height:70*s,borderBottom:"1px solid #D3D3D7",display:"flex",alignItems:"center",justifyContent:"space-between",padding:`0 ${22*s}px`,fontSize:21*s,color:P.cobalt}}><span>Annuler</span><b style={{color:P.ink}}>Nouveau message</b><span style={{fontSize:29*s}}>↑</span></div>{[["À :","bonjour@cavesbernard.com"],["Objet :","Livraison de 4 bouteilles · demain"]].map(r=><div key={r[0]} style={{padding:`${15*s}px ${20*s}px`,borderBottom:"1px solid #D8D8DC",fontSize:19*s,display:"flex",gap:10*s}}><span style={{color:"#777"}}>{r[0]}</span><span>{r[1]}</span></div>)}<div style={{padding:`${22*s}px`,fontSize:21*s,lineHeight:1.4}}><p>Bonjour,</p><p>Je vous confirme la sélection de <b>quatre cuvées</b>, avec livraison demain après-midi.</p><p>Destinataires : Léa, Marc, Inès et Jules<br/>Message : « Merci de la part de l’équipe de New York. »</p><p>Référence : <b>PAR-0426</b></p><p>Merci !<br/>Asmi</p></div></AbsoluteFill>;
const Email:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=win(f,570,582,708,722),sent=q(f,680,700),s=vertical?1:.66;return <AbsoluteFill style={{opacity:a,background:P.champagne,overflow:"hidden"}}><Grain/><div style={{position:"absolute",left:vertical?50:90,top:vertical?80:70}}><Label size={vertical?84:92} color={P.burgundy}>then confirms<br/>every detail.</Label><div style={{fontFamily:mono,fontSize:vertical?21:18,color:P.burgundy,marginTop:22}}>WRITTEN IN FRENCH · NOTHING LOST IN TRANSLATION</div></div><div style={{position:"absolute",left:vertical?"50%":"70%",top:vertical?"60%":"52%",transform:`translate(-50%,-50%) translateY(${(1-pop(f,580))*130}px)`}}><Phone vertical={vertical} frame={f} scale={vertical ? .72 : .92}><Mail s={s}/></Phone></div><div style={{position:"absolute",inset:0,background:P.cobalt,clipPath:`circle(${sent*145}% at ${vertical?"78% 79%":"82% 82%"})`,opacity:sent}}/><div style={{position:"absolute",left:"50%",top:"50%",transform:`translate(-50%,-50%) scale(${.55+.45*sent})`,opacity:sent,fontFamily:display,fontWeight:800,fontSize:vertical?190:190,color:P.white}}>SENT.</div></AbsoluteFill>};

const Result:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=win(f,700,714,820,834);const items=["4 bottles selected.","delivery confirmed.","paris, tomorrow."];return <AbsoluteFill style={{opacity:a,background:P.ivory,overflow:"hidden"}}><Grain/><div style={{position:"absolute",left:vertical?55:125,top:vertical?200:120,right:vertical?55:125}}>{items.map((x,i)=>{const p=pop(f,714+i*18);return <Label key={x} size={vertical?[102,106,116][i]:[116,122,142][i]} color={i===1?P.wine:P.ink} style={{marginTop:i?vertical?80:45:0,textAlign:i===1?"right":"left",transform:`translateX(${(1-p)*(i%2?180:-180)}px)`,opacity:p,whiteSpace:"nowrap"}}>{x}</Label>})}</div><div style={{position:"absolute",left:"50%",bottom:vertical?220:95,width:vertical?900:1200,transform:`translateX(-50%) rotate(-2deg) scale(${pop(f,772)})`,padding:vertical?"27px 30px":"22px 34px",background:P.burgundy,color:P.ivory,border:`${vertical?7:5}px solid ${P.ink}`,boxShadow:`${vertical?13:9}px ${vertical?15:11}px 0 ${P.ink}`,fontFamily:display,fontSize:vertical?44:39,fontWeight:700,textAlign:"center"}}>sorted. four bottles, four colleagues,<br/><span style={{color:P.champagne}}>zero midnight french for you.</span></div></AbsoluteFill>};

const Languages:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const a=win(f,816,828,910,922);const words=["bonjour","hola","नमस्ते","你好","مرحباً","olá","こんにちは","hallo","안녕하세요","ciao","bonjour","привет","হ্যালো","merhaba"];return <AbsoluteFill style={{opacity:a,background:P.night,overflow:"hidden"}}><Grain/>{words.map((w,i)=>{const angle=(i/words.length)*Math.PI*2+f*.008;const rx=vertical?420:750,ry=vertical?730:390;const x=50+Math.cos(angle)*rx/(vertical?10.8:19.2),y=50+Math.sin(angle)*ry/(vertical?19.2:10.8);return <div key={`${w}-${i}`} style={{position:"absolute",left:`${x}%`,top:`${y}%`,fontFamily:ui,fontWeight:700,fontSize:vertical?38:34,color:i%3===0?P.champagne:i%3===1?P.steel:P.white,opacity:.62,transform:`translate(-50%,-50%) rotate(${Math.sin(i)*8}deg)`,whiteSpace:"nowrap"}}>{w}</div>})}<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",textAlign:"center"}}><div style={{transform:`scale(${.74+.26*pop(f,842)})`}}><Label size={vertical?102:126} color={P.ivory}>talks. texts. emails.</Label><Label size={vertical?175:210} color={P.acid} style={{marginTop:25}}>50+ languages.</Label><div style={{fontFamily:mono,color:P.champagne,fontSize:vertical?27:24,marginTop:40,fontWeight:700}}>ask in yours. asmi handles theirs.</div></div></div></AbsoluteFill>};

const MessagesIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#34C759"/><path d="M32 13c-12 0-21.5 8-21.5 18 0 6.1 3.7 11.5 9.3 14.8l-2.1 6.4c-.4 1.2.8 2.2 1.9 1.6l7-4.1c1.7.4 3.5.6 5.4.6 12 0 21.5-8 21.5-18S44 13 32 13Z" fill="white"/></svg>;
const WhatsAppIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><circle cx="32" cy="32" r="31" fill="#25D366"/><path d="M48.9 15.3A23.7 23.7 0 0 0 11.7 43.9L8.4 56l12.4-3.2A23.7 23.7 0 0 0 48.9 15.3Zm-16.8 34a19.6 19.6 0 0 1-10-2.7l-.7-.4-7.4 1.9 2-7.2-.5-.8a19.6 19.6 0 1 1 16.6 9.2Z" fill="#FFF"/></svg>;
const End:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const p=pop(f,912);return <AbsoluteFill style={{opacity:q(f,906,918),background:P.ivory}}><Grain/><div style={{position:"absolute",left:"50%",top:vertical?680:320,width:vertical?820:900,height:vertical?300:280,transform:`translate(-50%,-50%) scale(${.65+.35*p})`,filter:"invert(1)"}}><Img src={staticFile("brand/asmi-logo-white.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><Label size={vertical?66:64} color={P.ink} style={{position:"absolute",left:0,right:0,top:vertical?980:590,textAlign:"center",opacity:q(f,928,940)}}>your agent for the real world.</Label><div style={{position:"absolute",left:0,right:0,top:vertical?1160:720,display:"flex",justifyContent:"center",alignItems:"center",gap:vertical?24:20,opacity:q(f,940,952),fontFamily:mono,fontWeight:700,fontSize:vertical?27:22,color:P.ink}}><span>text asmi.</span><MessagesIcon size={vertical?62:50}/><WhatsAppIcon size={vertical?62:50}/></div></AbsoluteFill>};

export const WineFranceFilm:React.FC<V>=({vertical})=><AbsoluteFill style={{background:P.night,overflow:"hidden"}}><Ask vertical={vertical}/><Search vertical={vertical}/><Call vertical={vertical}/><Email vertical={vertical}/><Result vertical={vertical}/><Languages vertical={vertical}/><End vertical={vertical}/><Audio src={staticFile("audio/wine-france/score.mp3")} volume={(f)=>interpolate(f,[0,10,232,245,570,590,820,900,955,959],[.86,1,1,.28,.3,.95,1,1,.7,0],clamp)}/><Sequence from={252}><Audio src={staticFile("audio/wine-france/asmi-fr.mp3")} playbackRate={1.18} volume={1.08}/></Sequence><Sequence from={452}><Audio src={staticFile("audio/wine-france/caviste-fr.mp3")} playbackRate={1.18} volume={1.08}/></Sequence>{[72,158,238,680,714,732,750,842,912].map((at,i)=><Sequence key={at} from={at}><Audio src={staticFile(i%2?"audio/sfx/wa-pop.mp3":"audio/sfx/imessage-receive.mp3")} volume={i===7?.4:.18}/></Sequence>)}</AbsoluteFill>;