import React from "react";
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {loadFont as loadBricolage} from "@remotion/google-fonts/BricolageGrotesque";
import {loadFont as loadMono} from "@remotion/google-fonts/NotoSansMono";
import cellar1 from "../public/images/wine-v5/cellar-1.jpg";
import cellar2 from "../public/images/wine-v5/cellar-2.jpg";
import cellar3 from "../public/images/wine-v5/cellar-3.jpg";

const {fontFamily:display}=loadBricolage("normal",{weights:["600","700","800"],subsets:["latin"]});
const {fontFamily:mono}=loadMono("normal",{weights:["400","600","700"],subsets:["latin"]});
const ui="-apple-system,BlinkMacSystemFont,'Helvetica Neue',Arial,sans-serif";
const C={paper:"#F6F7F2",ink:"#111513",green:"#0D3028",blue:"#1671FF",wine:"#9B173D",gold:"#F3CF6D",mint:"#58D4AA",white:"#FFFFFF",soft:"#E8EAE5",muted:"#69706B"};
type V={vertical:boolean};
const clamp={extrapolateLeft:"clamp",extrapolateRight:"clamp"} as const;
const Q=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],clamp);
const S=(f:number,at:number,d=20)=>spring({frame:f-at,fps:30,durationInFrames:d,config:{damping:24,stiffness:190}});
const vis=(f:number,a:number,b:number,fade=8)=>Q(f,a,a+fade)*(1-Q(f,b-fade,b));

const MessagesIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><rect width="64" height="64" rx="15" fill="#34C759"/><path d="M13 31c0-10 8.5-18 19-18s19 8 19 18-8.5 18-19 18c-3.1 0-6-.7-8.5-1.9L14 51l2.8-8C14.4 39.9 13 35.6 13 31z" fill="white"/></svg>;
const WhatsAppIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><rect width="64" height="64" rx="15" fill="#25D366"/><path fill="white" d="M32 12c-10.8 0-19.5 8.5-19.5 19 0 3.4.9 6.7 2.7 9.5L12 52l11.9-3.1A19.8 19.8 0 0032 50c10.8 0 19.5-8.5 19.5-19S42.8 12 32 12zm0 34.6c-2.7 0-5.4-.7-7.7-2l-.6-.3-7.1 1.9 1.9-6.7-.4-.7a15.2 15.2 0 01-2.3-7.9c0-8.6 7.2-15.6 16.1-15.6S48 22.3 48 30.9s-7.1 15.7-16 15.7z"/><path fill="white" d="M41 35.2c-.5-.2-3-1.4-3.4-1.6-.5-.2-.8-.2-1.1.3-.3.5-1.3 1.6-1.6 2-.3.3-.6.4-1.1.1-3-1.4-5-2.5-7-5.7-.5-.9.5-.8 1.5-2.7.2-.3.1-.6 0-.8l-1.5-3.6c-.4-.9-.8-.8-1.1-.8h-1c-.3 0-.9.1-1.4.6-.5.5-1.8 1.7-1.8 4.2s1.9 4.9 2.1 5.2c.2.3 3.7 5.5 9 7.7 3.3 1.4 4.6 1.5 6.3 1.3 1-.2 3-1.2 3.4-2.4.4-1.2.4-2.2.3-2.4-.1-.2-.5-.3-1-.5z"/></svg>;

const Phone=({vertical,children,scale=1}:{vertical:boolean,children:React.ReactNode,scale?:number})=>{
 const w=vertical?870:620,h=vertical?1590:990;
 return <div style={{position:"absolute",left:vertical?"50%":"70%",top:vertical?"59%":"50%",width:w,height:h,transform:`translate(-50%,-50%) scale(${scale})`,borderRadius:vertical?106:76,background:"#090B0B",padding:vertical?18:14,boxShadow:"0 60px 150px rgba(16,25,21,.25),0 0 0 2px #363A39",zIndex:2}}>
  <div style={{position:"relative",width:"100%",height:"100%",borderRadius:vertical?88:63,background:C.white,overflow:"hidden"}}>
   <div style={{height:vertical?62:45,display:"flex",alignItems:"center",justifyContent:"space-between",padding:vertical?"0 32px":"0 24px",fontFamily:ui,fontSize:vertical?18:13,fontWeight:700,color:C.ink}}><span>6:42</span><div style={{position:"absolute",left:"50%",top:vertical?12:9,transform:"translateX(-50%)",width:vertical?210:145,height:vertical?40:28,borderRadius:30,background:"#090B0B"}}/><span>5G&nbsp; ▰</span></div>
   <div style={{position:"absolute",left:0,right:0,top:vertical?62:45,bottom:0}}>{children}</div>
  </div>
 </div>
};

const StoryStart:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=vis(f,0,112);const b=S(f,28,22),r=S(f,68,20);return <AbsoluteFill style={{opacity:op,background:C.paper}}>
 <div style={{position:"absolute",left:vertical?54:105,top:vertical?90:105,width:vertical?950:650}}><div style={{fontFamily:mono,fontSize:vertical?17:14,fontWeight:700,color:C.muted}}>NEW YORK · 6:42 PM</div><div style={{fontFamily:display,fontSize:vertical?67:64,fontWeight:800,lineHeight:.98,marginTop:vertical?40:38}}>four teammates.<br/><span style={{color:C.wine}}>one good bottle each.</span><br/>paris. tomorrow.</div><div style={{fontFamily:ui,fontSize:vertical?27:23,lineHeight:1.35,color:C.muted,marginTop:vertical?32:28}}>you remembered the gift.<br/>not the French phone call.</div></div>
 <Phone vertical={vertical} scale={vertical?.82:.86}><div style={{height:vertical?86:62,display:"grid",placeItems:"center",borderBottom:`1px solid ${C.soft}`,fontFamily:ui,fontWeight:700,fontSize:vertical?24:18}}>asmi</div><div style={{padding:vertical?26:20}}><div style={{marginLeft:"auto",maxWidth:"86%",padding:vertical?"22px 25px":"16px 19px",borderRadius:vertical?32:24,background:C.blue,color:C.white,fontFamily:ui,fontSize:vertical?29:21,lineHeight:1.25,transform:`translateX(${(1-b)*110}px)`,opacity:b}}>send four great bottles to my team in paris. local shop. delivery tomorrow.</div><div style={{marginTop:vertical?40:28,maxWidth:"78%",padding:vertical?"21px 24px":"15px 18px",borderRadius:vertical?30:22,background:C.soft,fontFamily:ui,fontSize:vertical?28:20,lineHeight:1.25,transform:`translateX(${(1-r)*-90}px)`,opacity:r}}>on it. finding a proper local wine shop.</div></div></Phone>
 </AbsoluteFill>};

type Choice={name:string,image:string,rating:string,reviews:string,area:string,detail:string,badge:string};
const choices:Choice[]=[
 {name:"Legrand Filles et Fils",image:cellar1,rating:"4.7",reviews:"184 reviews",area:"2e",detail:"independent · delivery by request",badge:"LOCAL CLASSIC"},
 {name:"Caves Bernard",image:cellar2,rating:"4.9",reviews:"326 reviews",area:"5e",detail:"small producers · delivers tomorrow",badge:"ASMI PICK · PHONE ORDER"},
 {name:"La Dernière Goutte",image:cellar3,rating:"4.8",reviews:"211 reviews",area:"6e",detail:"natural wines · calls welcome",badge:"GREAT BACKUP"},
];
const ChoiceCard=({x,frame,at,selected,vertical}:{x:Choice,frame:number,at:number,selected?:boolean,vertical:boolean})=>{const p=S(frame,at,18),check=selected?Q(frame,238,252):0;return <div style={{height:vertical?265:176,borderRadius:vertical?28:20,background:selected?"#EDF3FF":C.white,border:`${selected?3:1}px solid ${selected?C.blue:C.soft}`,overflow:"hidden",display:"grid",gridTemplateColumns:vertical?"255px 1fr":"170px 1fr",boxShadow:selected?"0 18px 46px rgba(22,113,255,.16)":"0 8px 24px rgba(17,21,19,.06)",transform:`translateX(${(1-p)*420}px)`,opacity:p}}><Img src={x.image} style={{width:"100%",height:"100%",objectFit:"cover"}}/><div style={{padding:vertical?"24px 25px":"16px 18px",position:"relative"}}><div style={{fontFamily:ui,fontWeight:750,fontSize:vertical?28:20,paddingRight:40}}>{x.name}</div><div style={{display:"flex",gap:9,alignItems:"center",marginTop:vertical?12:8,fontFamily:ui,fontSize:vertical?17:12,color:C.muted}}><span style={{color:"#E49B16",fontWeight:800}}>★ {x.rating}</span><span>{x.reviews}</span><span>· {x.area}</span></div><div style={{fontFamily:ui,fontSize:vertical?18:13,color:C.muted,marginTop:vertical?11:7}}>{x.detail}</div><div style={{fontFamily:mono,fontSize:vertical?12:9,fontWeight:700,color:selected?C.wine:C.green,marginTop:vertical?15:10}}>{x.badge}</div><div style={{position:"absolute",right:18,top:18,width:vertical?36:26,height:vertical?36:26,borderRadius:"50%",border:`2px solid ${selected?C.blue:"#BFC4C0"}`,background:check>.5?C.blue:"transparent",color:C.white,display:"grid",placeItems:"center",fontSize:vertical?21:14}}>{check>.5?"✓":""}</div></div></div>};

const Research:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=vis(f,96,292,6);return <AbsoluteFill style={{opacity:op,background:C.paper}}><div style={{position:"absolute",left:vertical?50:105,top:vertical?90:160,width:vertical?940:550}}><div style={{fontFamily:mono,fontSize:vertical?17:14,fontWeight:700,color:C.blue}}>ASMI BUILDS THE SHORTLIST</div><div style={{fontFamily:display,fontSize:vertical?56:54,fontWeight:800,lineHeight:1.02,marginTop:18}}>three shops.<br/>one obvious call.</div><div style={{fontFamily:ui,fontSize:vertical?25:21,lineHeight:1.35,color:C.muted,marginTop:25}}>photos, ratings, reviews, delivery.<br/>the useful bits. nothing else.</div></div><Phone vertical={vertical} scale={vertical?.92:.86}><div style={{padding:vertical?"20px 22px":"14px 17px",borderBottom:`1px solid ${C.soft}`}}><div style={{fontFamily:display,fontSize:vertical?30:22,fontWeight:800}}>wine for the paris team</div><div style={{fontFamily:mono,fontSize:vertical?12:9,color:C.muted,marginTop:5}}>FROM IMESSAGE · TOMORROW · 4 RECIPIENTS</div></div><div style={{padding:vertical?"18px 18px":"13px 13px",display:"grid",gap:vertical?13:9}}>{choices.map((x,i)=><ChoiceCard key={x.name} x={x} frame={f} at={120+i*11} selected={i===1} vertical={vertical}/>)}</div><div style={{position:"absolute",left:vertical?22:17,right:vertical?22:17,bottom:vertical?24:18,padding:vertical?"17px 20px":"12px 15px",borderRadius:vertical?24:18,background:C.green,color:C.white,fontFamily:ui,fontSize:vertical?19:14,lineHeight:1.3,opacity:S(f,178,18)}}><b>why this one:</b> best small-producer selection. they take phone orders. delivery tomorrow.</div></Phone></AbsoluteFill>};

const Handoff:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=vis(f,278,348,6),p=Q(f,284,338);return <AbsoluteFill style={{opacity:op,background:C.green,color:C.white}}><div style={{position:"absolute",left:vertical?50:105,top:vertical?110:170,width:vertical?940:600}}><div style={{fontFamily:mono,fontSize:vertical?17:14,color:C.gold,fontWeight:700}}>NEW YORK → PARIS</div><div style={{fontFamily:display,fontSize:vertical?61:58,fontWeight:800,lineHeight:1,marginTop:20}}>you ask in English.<br/><span style={{color:C.mint}}>asmi handles the French.</span></div></div><Phone vertical={vertical} scale={vertical?.92:.86}><div style={{height:"100%",background:C.green,color:C.white,position:"relative",overflow:"hidden"}}><svg width="100%" height="100%" viewBox="0 0 700 1150"><path d="M-60 920 C180 580 390 510 760 240" fill="none" stroke={C.blue} strokeWidth="14" strokeDasharray="24 16" strokeDashoffset={(1-p)*1100}/><circle cx="40" cy="820" r="14" fill={C.gold}/><circle cx="640" cy="300" r="14" fill={C.wine}/></svg>{[["4 BOTTLES","4 BOUTEILLES"],["4 PEOPLE","4 PERSONNES"],["TOMORROW","DEMAIN"]].map((x,i)=>{const q=Q(p,i*.15,.66+i*.08);return <div key={x[0]} style={{position:"absolute",left:interpolate(q,[0,1],[25,390]),top:820-i*175-Math.sin(q*Math.PI)*130,padding:"12px 16px",background:[C.gold,C.blue,C.wine][i],color:i?C.white:C.ink,fontFamily:mono,fontWeight:800,fontSize:vertical?19:14,transform:`rotate(${interpolate(q,[0,1],[-5,3])}deg)`}}>{q>.5?x[1]:x[0]}</div>})}</div></Phone></AbsoluteFill>};

const Wave=({f,vertical}:{f:number,vertical:boolean})=><div style={{height:vertical?100:65,display:"flex",alignItems:"center",justifyContent:"center",gap:vertical?8:5}}>{Array.from({length:34},(_,i)=><div key={i} style={{width:vertical?7:5,height:14+Math.abs(Math.sin(i*.71+f*.19))*(vertical?70:45),borderRadius:8,background:i%7===0?C.gold:C.white}}/>)}</div>;
const Call:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=vis(f,332,532,7);const state=f<353?"dialing":f<376?"ringing":"on call";const line=f<376?"calling Caves Bernard…":f<405?"Caves Bernard, bonjour.":f<468?"Four excellent bottles. Four Paris addresses. Tomorrow.":"Oui, bien sûr. Livraison demain après-midi.";return <AbsoluteFill style={{opacity:op,background:C.green,color:C.white}}><div style={{position:"absolute",left:vertical?50:105,top:vertical?100:150,width:vertical?940:610}}><div style={{fontFamily:mono,fontSize:vertical?17:14,color:C.gold,fontWeight:700}}>THE CALL · IN FRENCH</div><div style={{fontFamily:display,fontSize:vertical?57:56,fontWeight:800,lineHeight:1,marginTop:18}}>no handoff.<br/>no script for you.</div><div style={{fontFamily:ui,fontSize:vertical?24:20,color:"#C7D9D2",marginTop:24}}>just the five seconds that matter.</div></div><Phone vertical={vertical} scale={vertical?.92:.86}><div style={{height:"100%",background:"#102B25",color:C.white,padding:vertical?"34px 28px":"25px 21px"}}><div style={{display:"flex",justifyContent:"space-between",fontFamily:mono,fontSize:vertical?13:10,color:C.mint}}><span>LIVE TASK</span><span>FR · {state}</span></div><div style={{marginTop:vertical?55:40,textAlign:"center"}}><div style={{width:vertical?150:105,height:vertical?150:105,borderRadius:vertical?42:30,background:C.gold,color:C.wine,display:"grid",placeItems:"center",margin:"0 auto",fontFamily:display,fontWeight:800,fontSize:vertical?53:38}}>CB</div><div style={{fontFamily:ui,fontSize:vertical?31:23,fontWeight:700,marginTop:20}}>Caves Bernard</div><div style={{fontFamily:ui,fontSize:vertical?18:13,color:"#9CB0A8",marginTop:7}}>Paris · working wine shop</div></div><div style={{marginTop:vertical?90:65}}><Wave f={f} vertical={vertical}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:vertical?70:50}}>{["queued","dialing","ringing","on call"].map((x,i)=>{const idx=state==="dialing"?1:state==="ringing"?2:3;return <div key={x} style={{textAlign:"center",fontFamily:mono,fontSize:vertical?11:8,color:i<=idx?C.white:"#60746C"}}><div style={{width:vertical?20:14,height:vertical?20:14,borderRadius:"50%",background:i<idx?C.mint:i===idx?C.blue:"#40534C",margin:"0 auto 8px"}}/>{x}</div>})}</div><div style={{position:"absolute",left:vertical?30:22,right:vertical?30:22,bottom:vertical?70:50,textAlign:"center",fontFamily:ui,fontSize:vertical?27:20,fontWeight:700,lineHeight:1.3}}>{line}</div></div></Phone></AbsoluteFill>};

const Followup:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=vis(f,516,660,7),sent=Q(f,610,630);return <AbsoluteFill style={{opacity:op,background:C.paper}}><div style={{position:"absolute",left:vertical?50:105,top:vertical?105:165,width:vertical?940:590}}><div style={{fontFamily:mono,fontSize:vertical?17:14,color:C.blue,fontWeight:700}}>CALL DONE. ASMI KEEPS GOING.</div><div style={{fontFamily:display,fontSize:vertical?57:55,fontWeight:800,lineHeight:1,marginTop:18}}>details confirmed.<br/><span style={{color:C.wine}}>French email sent.</span></div><div style={{fontFamily:ui,fontSize:vertical?24:20,color:C.muted,marginTop:24}}>four addresses. one clean follow-up.</div></div><Phone vertical={vertical} scale={vertical?.92:.86}><div style={{height:"100%",background:C.paper}}><div style={{padding:vertical?"22px 22px":"16px",borderBottom:`1px solid ${C.soft}`}}><div style={{fontFamily:display,fontSize:vertical?29:21,fontWeight:800}}>wine for the paris team</div><div style={{fontFamily:mono,fontSize:vertical?11:8,color:C.muted,marginTop:5}}>CALL COMPLETE · FOLLOWING UP</div></div><div style={{padding:vertical?"22px":"16px"}}><div style={{display:"grid",gap:vertical?14:10,marginBottom:vertical?24:18}}>{[["call complete","Caves Bernard"],["delivery confirmed","tomorrow · 2–5 PM"],["email sent in French","4 delivery addresses"]].map((x,i)=><div key={x[0]} style={{display:"flex",gap:12,alignItems:"center",fontFamily:ui,fontSize:vertical?18:13,opacity:S(f,535+i*10,16)}}><div style={{width:vertical?20:14,height:vertical?20:14,borderRadius:"50%",background:C.mint}}/><div><b>{x[0]}</b><div style={{fontFamily:mono,fontSize:vertical?11:8,color:C.muted,marginTop:3}}>{x[1]}</div></div></div>)}</div><div style={{background:C.white,border:`1px solid ${C.soft}`,borderRadius:vertical?26:18,padding:vertical?"22px":"16px",boxShadow:"0 12px 35px rgba(17,21,19,.08)"}}><div style={{fontFamily:ui,fontSize:vertical?22:16,fontWeight:750}}>confirmation de livraison</div><div style={{fontFamily:mono,fontSize:vertical?10:8,color:C.muted,marginTop:5}}>EMAIL · FRANÇAIS</div><div style={{height:1,background:C.soft,margin:vertical?"18px 0":"13px 0"}}/><div style={{fontFamily:ui,fontSize:vertical?16:12,lineHeight:1.5}}><b>À :</b> commandes@cavesbernard.fr<br/><b>Objet :</b> Livraison de quatre bouteilles — demain<br/><br/>Bonjour,<br/>Voici les quatre adresses de livraison à Paris.</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7,marginTop:15}}>{["Maya · 3e","Theo · 9e","Lina · 10e","Jules · 11e"].map((x,i)=><div key={x} style={{background:C.paper,padding:vertical?"10px":"7px",fontFamily:mono,fontSize:vertical?11:8,opacity:S(f,565+i*5,14)}}>✓ {x}</div>)}</div><div style={{height:6,width:`${sent*100}%`,background:C.blue,marginTop:16}}/></div></div></div></Phone></AbsoluteFill>};

const Completion:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=vis(f,646,742,7),p=S(f,658,20);return <AbsoluteFill style={{opacity:op,background:C.paper}}><div style={{position:"absolute",left:vertical?50:105,top:vertical?110:175,width:vertical?940:600}}><div style={{fontFamily:mono,fontSize:vertical?17:14,color:C.mint,fontWeight:700}}>DONE</div><div style={{fontFamily:display,fontSize:vertical?62:59,fontWeight:800,lineHeight:1,marginTop:18}}>four bottles.<br/>four doors.<br/><span style={{color:C.wine}}>tomorrow.</span></div></div><Phone vertical={vertical} scale={vertical?.92:.86}><div style={{height:vertical?86:62,display:"grid",placeItems:"center",borderBottom:`1px solid ${C.soft}`,fontFamily:ui,fontWeight:700,fontSize:vertical?24:18}}>asmi</div><div style={{padding:vertical?"27px":"20px"}}><div style={{maxWidth:"88%",padding:vertical?"22px 24px":"16px 18px",borderRadius:vertical?30:22,background:C.soft,fontFamily:ui,fontSize:vertical?28:20,lineHeight:1.28,transform:`translateY(${(1-p)*60}px)`,opacity:p}}>sorted. four local bottles. four paris addresses. delivery tomorrow afternoon.<br/><b style={{display:"inline-block",color:C.wine,marginTop:10}}>zero midnight french for you.</b></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:vertical?12:9,marginTop:vertical?34:25}}>{["Maya · 3e","Theo · 9e","Lina · 10e","Jules · 11e"].map((x,i)=><div key={x} style={{padding:vertical?"17px":"12px",borderRadius:vertical?18:13,background:i%2?C.green:C.gold,color:i%2?C.white:C.ink,fontFamily:mono,fontSize:vertical?12:9,opacity:S(f,680+i*6,16)}}><b>DELIVERY CONFIRMED</b><div style={{fontFamily:ui,fontSize:vertical?18:13,marginTop:7}}>{x} · 2–5 PM</div></div>)}</div></div></Phone></AbsoluteFill>};

const langs=[["français","livraison confirmée"],["español","entrega confirmada"],["हिन्दी","डिलीवरी पक्की"],["العربية","تم تأكيد التسليم"],["日本語","配達確認済み"],["português","entrega confirmada"],["Deutsch","Lieferung bestätigt"],["한국어","배송 확인 완료"]];
const Languages:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const op=vis(f,728,824,7),p=Q(f,738,810);return <AbsoluteFill style={{opacity:op,background:C.green,color:C.white,overflow:"hidden"}}><div style={{position:"absolute",inset:vertical?"40px -230px":"-75px 0",display:"grid",gridTemplateColumns:vertical?"repeat(2,1fr)":"repeat(4,1fr)",gap:15,transform:`rotate(-5deg) translateX(${interpolate(p,[0,1],[80,-120])}px)`,opacity:.5}}>{langs.map((x,i)=><div key={x[0]} style={{height:vertical?220:210,padding:vertical?"27px":"23px",background:[C.blue,C.wine,C.gold,C.mint][i%4],color:i%4>1?C.ink:C.white,transform:`translateY(${Math.sin(p*8+i)*30}px)`}}><b style={{fontFamily:display,fontSize:vertical?31:27}}>{x[0]}</b><div style={{fontFamily:ui,fontSize:vertical?19:16,marginTop:12}}>{x[1]}</div></div>)}</div><div style={{position:"absolute",left:vertical?55:110,bottom:vertical?260:105}}><div style={{fontFamily:mono,fontSize:vertical?20:17,color:C.gold,fontWeight:700}}>TALKS. TEXTS. EMAILS.</div><div style={{fontFamily:display,fontSize:vertical?165:145,fontWeight:800,lineHeight:.8,marginTop:25}}>50+</div><div style={{fontFamily:display,fontSize:vertical?61:54,fontWeight:800,marginTop:28}}>languages.</div><div style={{fontFamily:ui,fontSize:vertical?25:21,marginTop:18}}>ask in yours. asmi handles theirs.</div></div></AbsoluteFill>};

const End:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const wipe=Q(f,818,835),p=S(f,824,26);return <AbsoluteFill style={{background:C.ink,color:C.white,clipPath:`circle(${wipe*86}% at 50% 50%)`}}><div style={{position:"absolute",left:"50%",top:vertical?690:355,width:vertical?820:820,height:vertical?330:300,transform:`translate(-50%,-50%) scale(${.76+.24*p})`}}><Img src={staticFile("brand/asmi-logo-white.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div style={{position:"absolute",left:0,right:0,top:vertical?980:590,textAlign:"center",fontFamily:display,fontSize:vertical?54:48,fontWeight:700}}>your agent for the real world.</div><div style={{position:"absolute",left:0,right:0,top:vertical?1185:760,display:"flex",justifyContent:"center",alignItems:"center",gap:18,fontFamily:mono,fontSize:vertical?22:18,fontWeight:700,color:C.gold}}><span>text asmi.</span><MessagesIcon size={vertical?60:52}/><WhatsAppIcon size={vertical?60:52}/></div><div style={{position:"absolute",left:"50%",top:vertical?1390:890,width:Q(f,844,868)*(vertical?700:960),height:14,transform:"translateX(-50%)",background:C.blue}}/></AbsoluteFill>};

export const WineFranceFilmV5:React.FC<V>=({vertical})=>{const {durationInFrames}=useVideoConfig();return <AbsoluteFill style={{background:C.paper,color:C.ink,overflow:"hidden"}}><StoryStart vertical={vertical}/><Research vertical={vertical}/><Handoff vertical={vertical}/><Call vertical={vertical}/><Followup vertical={vertical}/><Completion vertical={vertical}/><Languages vertical={vertical}/><End vertical={vertical}/><Audio src={staticFile("audio/wine-france-v5/score.wav")} volume={(f)=>interpolate(f,[0,18,320,338,515,535,730,800,durationInFrames-1],[0,.9,.9,.34,.34,.92,.92,1,0],clamp)}/><Sequence from={350} durationInFrames={28} premountFor={30}><Audio src={staticFile("audio/wine-france-v5/pickup.mp3")} volume={1.06}/></Sequence><Sequence from={378} durationInFrames={84} premountFor={30}><Audio src={staticFile("audio/wine-france-v5/asmi.mp3")} volume={1.08}/></Sequence><Sequence from={462} durationInFrames={61} premountFor={30}><Audio src={staticFile("audio/wine-france-v5/confirm.mp3")} volume={1.08}/></Sequence></AbsoluteFill>};
