import React from "react";
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {loadFont as loadBricolage} from "@remotion/google-fonts/BricolageGrotesque";
import cellar1 from "../public/images/wine-v5/cellar-1.jpg";
import cellar2 from "../public/images/wine-v5/cellar-2.jpg";
import cellar3 from "../public/images/wine-v5/cellar-3.jpg";

const {fontFamily:display}=loadBricolage("normal",{weights:["600","700","800"],subsets:["latin"]});
const ui="-apple-system,BlinkMacSystemFont,'SF Pro Text','Helvetica Neue',Arial,sans-serif";
const mono="'SFMono-Regular',Consolas,monospace";
const C={paper:"#F7F5EF",ink:"#17151B",plum:"#282031",plum2:"#392E45",blue:"#1677FF",green:"#163D34",mint:"#54D5A7",gold:"#F2BF55",wine:"#A22146",white:"#FFFFFF",line:"#DEDCE2",muted:"#77737C",gmail:"#EA4335"};
const clamp={extrapolateLeft:"clamp",extrapolateRight:"clamp"} as const;
const q=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],clamp);
const pop=(f:number,at:number,d=20)=>spring({frame:f-at,fps:30,durationInFrames:d,config:{damping:22,stiffness:210}});
const windowed=(f:number,a:number,b:number,c:number,d:number)=>q(f,a,b)*(1-q(f,c,d));
type V={vertical:boolean};

const MessagesIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><rect width="64" height="64" rx="15" fill="#34C759"/><path d="M12 31c0-10 9-18 20-18s20 8 20 18-9 18-20 18c-3 0-6-.6-8.5-1.8L14 51l2.8-8C13.8 39.7 12 35.6 12 31z" fill="#fff"/></svg>;
const WhatsAppIcon=({size}:{size:number})=><svg width={size} height={size} viewBox="0 0 64 64"><circle cx="32" cy="32" r="31" fill="#25D366"/><path d="M49 15A24 24 0 0012 44L8 56l13-3a24 24 0 1028-38ZM32 49c-3 0-7-1-10-3l-7 2 2-7c-2-3-3-6-3-10a18 18 0 1136 0c0 10-8 18-18 18Z" fill="#fff"/><path d="M42 36c-1 0-4-2-4-2-1 0-1 0-2 1l-2 2c-4-2-7-4-9-8l2-2c1-1 0-2 0-2l-2-4c0-1-1-1-2-1-2 0-4 2-4 5 0 6 6 13 14 16 5 2 9 0 10-3 0-1 0-2-1-2Z" fill="#fff"/></svg>;

const Status=({light=true}:{light?:boolean})=><div style={{height:54,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 25px",fontFamily:ui,fontSize:15,fontWeight:700,color:light?C.ink:C.white,position:"relative",zIndex:20}}><span>6:42</span><span style={{fontSize:13}}>5G&nbsp; ▮▮▮</span></div>;

const Phone:React.FC<{vertical:boolean;children:React.ReactNode}>=({vertical,children})=>{
 const f=useCurrentFrame(); const w=650,h=1408,r=96; const scale=vertical?1.22:.69;
 return <div style={{position:"absolute",left:vertical?"50%":"74%",top:"50%",width:w,height:h,transform:`translate(-50%,-50%) perspective(2000px) rotateY(${vertical?0:-2.5}deg) rotateZ(${Math.sin(f/41)*.18}deg) scale(${scale})`,transformStyle:"preserve-3d",filter:"drop-shadow(0 54px 60px rgba(24,17,31,.36))",zIndex:10}}>
  <div style={{position:"absolute",inset:-9,borderRadius:r+10,background:"linear-gradient(105deg,#252428 0%,#E5E2DC 8%,#69676D 23%,#17171A 54%,#D8D3CA 83%,#333238 100%)",boxShadow:"inset 0 0 0 2px rgba(255,255,255,.8),inset 0 0 0 8px #18171B"}}/>
  <div style={{position:"absolute",left:-16,top:230,width:16,height:180,borderRadius:"8px 0 0 8px",background:"linear-gradient(90deg,#343238,#B0ADB0)"}}/><div style={{position:"absolute",right:-16,top:320,width:16,height:190,borderRadius:"0 8px 8px 0",background:"linear-gradient(90deg,#A9A5A8,#312F34)"}}/>
  <div style={{position:"absolute",inset:7,borderRadius:r-4,background:"#000",overflow:"hidden",boxShadow:"inset 0 0 0 2px #050506"}}>{children}<div style={{position:"absolute",top:15,left:"50%",transform:"translateX(-50%)",width:126,height:36,borderRadius:24,background:"#000",zIndex:80}}/><div style={{position:"absolute",bottom:10,left:"50%",transform:"translateX(-50%)",width:126,height:5,borderRadius:5,background:"rgba(255,255,255,.78)",zIndex:80}}/></div>
 </div>;
};

const Bubble=({mine,children}:{mine?:boolean;children:React.ReactNode})=><div style={{alignSelf:mine?"flex-end":"flex-start",maxWidth:"86%",padding:"15px 18px",borderRadius:25,background:mine?C.blue:"#E9E9ED",color:mine?C.white:C.ink,fontFamily:ui,fontSize:23,lineHeight:1.28}}>{children}</div>;
const MessageScreen=({f,done=false}:{f:number;done?:boolean})=><AbsoluteFill style={{background:"#F7F7F9"}}><Status/><div style={{height:82,borderBottom:"1px solid #D7D7DC",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:ui,color:C.ink,position:"relative"}}><span style={{position:"absolute",left:21,fontSize:35,color:C.blue}}>‹</span><div style={{textAlign:"center",fontSize:17,fontWeight:650}}><div style={{width:42,height:42,borderRadius:"50%",background:C.wine,color:C.white,display:"grid",placeItems:"center",margin:"0 auto 3px",fontFamily:display,fontWeight:800}}>a</div>asmi</div></div><div style={{padding:"28px 22px",display:"flex",flexDirection:"column",gap:16}}>{done?<><div style={{opacity:pop(f,612),transform:`translateY(${(1-pop(f,612))*35}px)`}}><Bubble>sorted. four bottles from a local paris shop, delivered to four addresses tomorrow afternoon.</Bubble></div><div style={{opacity:pop(f,630)}}><Bubble>you can keep your evening. i handled the french phone call.</Bubble></div><div style={{display:"grid",gap:9,marginTop:13}}>{["Maya — tomorrow, 2–5 PM","Theo — tomorrow, 2–5 PM","Lina — tomorrow, 2–5 PM","Jules — tomorrow, 2–5 PM"].map((x,i)=><div key={x} style={{padding:"13px 15px",borderRadius:14,background:C.white,border:"1px solid #D9D9DE",fontFamily:ui,fontSize:16,opacity:pop(f,646+i*6),display:"flex",gap:10}}><span style={{color:"#27A96C",fontWeight:800}}>✓</span><span><b>Delivery confirmed</b><br/><span style={{color:C.muted}}>{x}</span></span></div>)}</div></>:<><div style={{opacity:pop(f,8),transform:`translateX(${(1-pop(f,8))*60}px)`,display:"flex",flexDirection:"column"}}><Bubble mine>I want to send a great bottle of wine to each of my four teammates in Paris tomorrow. Find a local shop and arrange delivery.</Bubble></div><div style={{opacity:pop(f,61),transform:`translateX(${(1-pop(f,61))*-50}px)`,display:"flex",flexDirection:"column"}}><Bubble>on it. i’ll find a proper paris wine shop and handle the rest in french.</Bubble></div></>}</div></AbsoluteFill>;

type Shop={name:string,image:string,rating:string,reviews:string,address:string,meta:string,price:string,tags:string[]};
const shops:Shop[]=[
 {name:"Caves Bernard",image:cellar2,rating:"4.9",reviews:"326 reviews",address:"35 rue des Bernardins, 5e",meta:"Open · Closes 8 PM · Delivery tomorrow",price:"€35–€70 · 4 in",tags:["Local delivery","Phone order","Small producers"]},
 {name:"Legrand Filles et Fils",image:cellar1,rating:"4.7",reviews:"184 reviews",address:"1 rue de la Banque, 2e",meta:"Open · Closes 7:30 PM",price:"€40–€85 · 4 in",tags:["Independent","Delivery by request"]},
 {name:"La Dernière Goutte",image:cellar3,rating:"4.8",reviews:"211 reviews",address:"6 rue de Bourbon le Château, 6e",meta:"Open · Closes 8 PM",price:"€38–€75 · 4 in",tags:["Natural wine","Calls welcome"]}
];
const Chips=({items}:{items:string[]})=><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:11}}>{items.map(x=><span key={x} style={{padding:"6px 10px",border:"1px solid #D9D5DA",borderRadius:14,fontFamily:ui,fontSize:12,color:C.muted}}>{x}</span>)}</div>;
const OptionsScreen=({f}:{f:number})=>{const select=q(f,238,253);return <AbsoluteFill style={{background:C.plum,color:C.white}}><Status light={false}/><div style={{height:72,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 27px",fontFamily:ui,fontSize:18}}><span>‹ Back</span><span style={{fontSize:28}}>☰</span></div><div style={{position:"absolute",left:25,right:25,top:126,bottom:112,overflow:"hidden"}}><div style={{fontFamily:ui,fontSize:17,lineHeight:1.32,color:"#D8CFDE",padding:"0 4px 17px",opacity:pop(f,110)}}>Caves Bernard is the best fit. Independent, excellent reviews, and they can arrange local delivery by phone.</div><div style={{borderRadius:28,overflow:"hidden",background:"#FCFAF4",color:C.ink,border:`${select?4:0}px solid ${C.gold}`,transform:`scale(${1+select*.012})`,opacity:pop(f,122)}}><Img src={shops[0].image} style={{width:"100%",height:215,objectFit:"cover"}}/><div style={{padding:"19px 22px 21px"}}><div style={{display:"flex",justifyContent:"space-between",gap:15}}><div style={{fontFamily:ui,fontSize:27,fontWeight:800}}>{shops[0].name}</div><div style={{width:28,height:28,borderRadius:"50%",border:`2px solid ${select?C.blue:"#B9B6BC"}`,background:select?C.blue:"transparent",color:C.white,display:"grid",placeItems:"center"}}>{select>.55?"✓":""}</div></div><div style={{fontFamily:ui,fontSize:17,color:C.muted,lineHeight:1.42,marginTop:8}}>{shops[0].address} · <u>Website ↗</u><br/>{shops[0].meta}<br/><b style={{color:C.ink}}>{shops[0].price}</b></div><div style={{fontFamily:ui,fontSize:16,marginTop:10}}><span style={{color:C.gold}}>★</span> <b>{shops[0].rating}</b> <span style={{color:C.muted}}>({shops[0].reviews})</span></div><Chips items={shops[0].tags}/></div></div>{shops.slice(1).map((s,i)=><div key={s.name} style={{marginTop:14,borderRadius:25,background:C.white,color:C.ink,padding:18,display:"grid",gridTemplateColumns:"1fr 145px",gap:12,opacity:pop(f,145+i*13),transform:`translateX(${(1-pop(f,145+i*13))*100}px)`}}><div><div style={{fontFamily:ui,fontSize:21,fontWeight:800}}>{s.name}</div><div style={{fontFamily:ui,fontSize:14,color:C.muted,lineHeight:1.4,marginTop:5}}><span style={{color:C.gold}}>★</span> <b style={{color:C.ink}}>{s.rating}</b> ({s.reviews}) · {s.price}<br/>{s.address}<br/>{s.meta} · <u>Website ↗</u></div><Chips items={s.tags}/></div><Img src={s.image} style={{width:145,height:155,objectFit:"cover",borderRadius:18}}/></div>)}</div><div style={{position:"absolute",left:25,right:25,bottom:28,height:72,borderRadius:36,background:select>.5?C.blue:C.plum2,color:select>.5?C.white:"#9A909F",display:"grid",placeItems:"center",fontFamily:ui,fontSize:19,fontWeight:750}}>☎&nbsp;&nbsp;Pick one option to call</div></AbsoluteFill>};

const Wave=({f}:{f:number})=><div style={{height:100,display:"flex",alignItems:"center",justifyContent:"center",gap:7}}>{Array.from({length:34},(_,i)=><div key={i} style={{width:6,height:14+Math.abs(Math.sin(i*.65+f*.22))*69,borderRadius:5,background:i%6===0?C.gold:C.white}}/>)}</div>;
const CallScreen=({f}:{f:number})=>{const state=f<310?"calling":f<333?"ringing":"connected";return <AbsoluteFill style={{background:"linear-gradient(180deg,#254D42,#0C1916 76%)",color:C.white,fontFamily:ui}}><Status light={false}/><div style={{padding:"18px 25px",display:"flex",justifyContent:"space-between",fontFamily:mono,fontSize:12,color:C.mint}}><span>ASMI · LIVE TASK</span><span>FR</span></div><div style={{textAlign:"center",marginTop:94}}><div style={{width:140,height:140,borderRadius:42,overflow:"hidden",margin:"0 auto",border:"2px solid rgba(255,255,255,.35)"}}><Img src={cellar2} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><div style={{fontSize:31,fontWeight:750,marginTop:22}}>Caves Bernard</div><div style={{fontSize:18,color:"#A6BAB3",marginTop:7}}>Paris · {state}</div><div style={{fontFamily:mono,fontSize:14,color:C.gold,marginTop:10}}>{state==="connected"?"00:0"+Math.max(1,Math.floor((f-333)/30)):""}</div></div><div style={{marginTop:105}}><Wave f={f}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,margin:"80px 36px 0"}}>{["calling","ringing","connected"].map((x,i)=>{const idx=state==="calling"?0:state==="ringing"?1:2;return <div key={x} style={{textAlign:"center",fontFamily:mono,fontSize:11,color:i<=idx?C.white:"#60746C"}}><div style={{width:18,height:18,borderRadius:"50%",background:i<idx?C.mint:i===idx?C.blue:"#40534C",margin:"0 auto 9px"}}/>{x}</div>})}</div><div style={{position:"absolute",left:32,right:32,bottom:76,textAlign:"center",fontSize:23,fontWeight:700,lineHeight:1.3}}>{f<333?"Calling the shop in French…":f<364?"Caves Bernard, bonjour.":f<444?"Four bottles, four Paris deliveries, tomorrow.":"Confirmed for tomorrow afternoon."}</div></AbsoluteFill>};

const GmailMark=()=> <svg width="42" height="32" viewBox="0 0 52 40"><path d="M4 7l22 17L48 7v29H4z" fill="#fff" stroke="#C7C7CC"/><path d="M4 7l22 17L48 7" fill="none" stroke="#EA4335" strokeWidth="6"/><path d="M4 7v29" stroke="#4285F4" strokeWidth="6"/><path d="M48 7v29" stroke="#34A853" strokeWidth="6"/></svg>;
const GmailScreen=({f}:{f:number})=>{const sent=q(f,570,580);return <AbsoluteFill style={{background:"#FAFAFC",color:C.ink,fontFamily:ui}}><Status/><div style={{height:74,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 21px",borderBottom:"1px solid #DDDDE2"}}><span style={{fontSize:28}}>×</span><b style={{fontSize:20}}>Compose</b><div style={{display:"flex",alignItems:"center",gap:19}}><span style={{fontSize:25}}>⋮</span><span style={{fontSize:31,color:C.gmail,transform:"rotate(25deg)"}}>➤</span></div></div><div style={{padding:"0 22px"}}>{[["From","asmi@asmi.com"],["To","Caves Bernard <commandes@cavesbernard.fr>"]].map((x,i)=><div key={x[0]} style={{height:i?78:66,borderBottom:"1px solid #DDDDE2",display:"flex",alignItems:"center",gap:13,fontSize:17,opacity:pop(f,472+i*8)}}><span style={{color:C.muted,width:48}}>{x[0]}</span><span>{x[1]}</span></div>)}<div style={{padding:"18px 0",borderBottom:"1px solid #DDDDE2",fontSize:18,fontWeight:650,opacity:pop(f,491)}}>Confirmation — quatre livraisons demain après-midi</div><div style={{paddingTop:23,fontSize:18,lineHeight:1.48,opacity:pop(f,507)}}>Bonjour,<br/><br/>Merci de préparer quatre bouteilles pour livraison demain après-midi aux quatre adresses ci-dessous. Merci d’ajouter le mot joint à chaque commande.<div style={{display:"grid",gap:8,margin:"19px 0"}}>{["Maya — Paris 3e","Theo — Paris 9e","Lina — Paris 10e","Jules — Paris 11e"].map((x,i)=><div key={x} style={{padding:"10px 12px",borderRadius:10,background:"#F0EEF2",fontFamily:mono,fontSize:13,opacity:pop(f,520+i*6)}}>✓ {x}</div>)}</div>Bien à vous,<br/>Asmi</div></div><div style={{position:"absolute",left:20,bottom:22,height:50,padding:"0 16px",borderRadius:8,background:"#323238",color:C.white,display:"flex",alignItems:"center",gap:42,fontSize:15,opacity:sent}}><span>Message sent</span><b>Undo</b></div><div style={{position:"absolute",right:22,bottom:24,opacity:.35}}><GmailMark/></div></AbsoluteFill>};

const LanguageScene:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const p=q(f,725,834);const lines=["Livraison confirmée demain.","Delivery confirmed for tomorrow.","Entrega confirmada para mañana.","कल डिलीवरी की पुष्टि हुई।","تم تأكيد التسليم غداً.","明日の配達が確認されました。","Entrega confirmada para amanhã.","Lieferung für morgen bestätigt.","내일 배송이 확정되었습니다."];return <AbsoluteFill style={{opacity:windowed(f,710,724,846,858),background:C.green,color:C.white,overflow:"hidden"}}><div style={{position:"absolute",inset:"-10%",display:"grid",gap:16,transform:`rotate(-5deg) translateY(${interpolate(p,[0,1],[70,-90])}px)`,opacity:.38}}>{lines.concat(lines).map((x,i)=><div key={i} style={{height:vertical?88:72,background:[C.blue,C.wine,C.gold,C.mint][i%4],color:i%4>1?C.ink:C.white,display:"flex",alignItems:"center",padding:"0 30px",fontFamily:ui,fontSize:vertical?24:21,fontWeight:700,transform:`translateX(${Math.sin(p*6+i)*80}px)`}}>{x}</div>)}</div><div style={{position:"absolute",left:vertical?60:115,right:vertical?60:760,top:"50%",transform:"translateY(-50%)",padding:vertical?"42px 38px":"46px 52px",background:"rgba(13,31,27,.91)",borderLeft:`10px solid ${C.gold}`}}><div style={{fontFamily:display,fontSize:vertical?70:69,fontWeight:800,lineHeight:1.02}}>Asmi can call, text, and email in more than 50 languages.</div><div style={{fontFamily:ui,fontSize:vertical?27:24,lineHeight:1.35,marginTop:25,color:"#D2E2DC"}}>Ask in yours. Asmi handles theirs.</div></div></AbsoluteFill>};
const End:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const p=pop(f,850,26);return <AbsoluteFill style={{opacity:q(f,844,855),background:"linear-gradient(145deg,#1E1825,#0F0D12)",color:C.white}}><div style={{position:"absolute",left:"50%",top:vertical?680:350,width:vertical?800:820,height:280,transform:`translate(-50%,-50%) scale(${.72+.28*p})`}}><Img src={staticFile("brand/asmi-logo-white.png")} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div style={{position:"absolute",left:0,right:0,top:vertical?975:610,textAlign:"center",fontFamily:display,fontSize:vertical?55:50,fontWeight:700}}>your agent for the real world.</div><div style={{position:"absolute",left:0,right:0,top:vertical?1170:755,display:"flex",alignItems:"center",justifyContent:"center",gap:18,fontFamily:ui,fontSize:vertical?26:22,fontWeight:700,color:C.gold}}><span>text asmi.</span><MessagesIcon size={vertical?60:52}/><WhatsAppIcon size={vertical?60:52}/></div></AbsoluteFill>};

const StoryContext=({vertical,text}:{vertical:boolean;text:string})=>vertical?null:<div style={{position:"absolute",left:105,top:"50%",width:760,transform:"translateY(-50%)",fontFamily:display,fontSize:57,fontWeight:750,lineHeight:1.08,color:C.ink,zIndex:4}}>{text}</div>;
export const WineFranceFilmV6:React.FC<V>=({vertical})=>{const f=useCurrentFrame();const {durationInFrames}=useVideoConfig();const phase=f<108?0:f<276?1:f<462?2:f<600?3:f<710?4:5;return <AbsoluteFill style={{background:"radial-gradient(circle at 78% 40%,#FFFFFF 0%,#F4F0E8 42%,#E5DDEC 100%)",overflow:"hidden"}}>
 {phase<5&&<><StoryContext vertical={vertical} text={["A thoughtful gift, without the late-night logistics.","Asmi finds the right local shop and gives you real options.","You pick once. Asmi handles the French call.","Then Asmi sends every delivery detail through Gmail.","The answer comes back where the story started."][phase]}/><Phone vertical={vertical}>{phase===0?<MessageScreen f={f}/>:phase===1?<OptionsScreen f={f}/>:phase===2?<CallScreen f={f}/>:phase===3?<GmailScreen f={f}/>:<MessageScreen f={f} done/>}</Phone></>}
 <LanguageScene vertical={vertical}/><End vertical={vertical}/>
 <Audio src={staticFile("audio/wine-france-v5/score.wav")} volume={(x)=>interpolate(x,[0,15,280,300,456,470,700,735,840,durationInFrames-1],[0,.9,.9,.32,.32,.9,.9,1,.8,0],clamp)}/>
 <Sequence from={302} durationInFrames={28} premountFor={30}><Audio src={staticFile("audio/wine-france-v5/pickup.mp3")} volume={1.05}/></Sequence>
 <Sequence from={336} durationInFrames={84} premountFor={30}><Audio src={staticFile("audio/wine-france-v5/asmi.mp3")} volume={1.08}/></Sequence>
 <Sequence from={421} durationInFrames={61} premountFor={30}><Audio src={staticFile("audio/wine-france-v5/confirm.mp3")} volume={1.08}/></Sequence>
 <Sequence from={82} premountFor={20}><Audio src={staticFile("audio/sfx/imessage-receive.mp3")} volume={.2}/></Sequence>
 <Sequence from={574} premountFor={20}><Audio src={staticFile("audio/sfx/wa-pop.mp3")} volume={.18}/></Sequence>
 </AbsoluteFill>};
